using System;
using System.Data;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Utility;
using BusinessLogic;
using System.IO;
using System.Collections.Generic;
using BusinessLogic.Exceptions;
/// <summary>
/// "This class will display list of students and allows user to edit or add student information."
/// </summary>

public partial class StudAttendanceRankersListUIPopUp : SchoolBase
{
    #region constants

    const string S_BLANK_GRID_MESSAGE = "No attendance records available.";

    #endregion

    #region Data members

    bool mbIsOldAttendanceToppersScreen;
    int miStudentId;
    int miOldStdDivId;

    #endregion

    #region event handlers
    
    /// <summary>
    /// This function is called when the page gets  loaded
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="e"></param>
    protected void Page_Load(object sender, EventArgs e)
    {
        try
        {
            InitializeFields();
            GetDetailsOfSelectedYear();            
            if (!IsPostBack)
            {
                InitialiseAttributes();
                SetControlsDefaultValues();                
                ShowStudentAttendance();                
            }

			ApplyMouseHoverEffect(new List<Button>() { btnBack }); 
        }
        catch (Exception ex)
        {
            ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
        }
    }

    

    /// <summary>
    /// Function to get back to control panel
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="e"></param>
    protected void btnBack_Click(object sender, EventArgs e)
    {
        try
        {
        }
        catch (Exception ex)
        {
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
        }
    }

    protected void cmbAcademicYrId_SelectedIndexChanged(object sender, EventArgs e)
    {
        try
        {
            GetDetailsOfSelectedYear();
            ShowStudentAttendance();
            lblOldAcademicYear.Text = CommonUtility.DisplayAcademicYear(cmbAcademicYrId.SelectedItem.Text);
        }
        catch (Exception ex)
        {
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
        }
    }

    /// <summary>
    /// This event is used to show records of selected page.
    /// </summary>
    /// <param name="sender"></param>
    /// <param name="e"></param>
    protected void grdStudents_PageIndexChanging(object sender, GridViewPageEventArgs e)
    {
        try
        {
            grdStudents.PageIndex = e.NewPageIndex;
            ShowStudentAttendance();
        }
        catch (Exception ex)
        {
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
        }
    }

    #region grid events

    protected void grdStudents_Sorting(object sender, GridViewSortEventArgs e)
    {
		try
		{
			e.SortExpression = "[Present Days]";
			e.SortExpression = SortDirection.Ascending.ToString();
		}
		catch (Exception ex)
		{
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
		}
    }

    protected void grdStudents_RowDataBound(object sender, GridViewRowEventArgs e)
    {
		try
		{
			EncodeHtmlCells(e);
		}
		catch (Exception ex)
		{
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
		}
    }
    protected void grdStudentRank_RowDataBound(object sender, GridViewRowEventArgs e)
    {
		try
		{
			EncodeHtmlCells(e);
		}
		catch (Exception ex)
		{
			ExceptionHandler.WriteExceptionToErrorLog(ex, System.Reflection.MethodBase.GetCurrentMethod());
		}
    }

    /// <summary>
    /// This method is used to encode the cell text of autogenerated coloums.
    /// </summary>
    /// <param name="e"></param>
    private void EncodeHtmlCells(GridViewRowEventArgs e)
    {
        TableCellCollection cells = e.Row.Cells;
        int iCnt = 0;
        foreach (TableCell cell in cells)
        {
            if (e.Row.RowType == DataControlRowType.DataRow)
            {

                if (iCnt == 0)
                {

                    if (File.Exists(AppDomain.CurrentDomain.BaseDirectory + cell.Text.Substring(1)))
                    {
                        Image oImage = new Image();
                        oImage.ImageUrl = cell.Text;
                        cell.Controls.Add(oImage);
                        cell.HorizontalAlign = HorizontalAlign.Center;
                    }
                    else
                    {
                        cell.Visible = false;
                        grdStudentRank.HeaderRow.Cells[iCnt].Visible = false;
                    }

                }
                else
                {
                    if (iCnt == 2)
                    {                        
                        cell.Width = Unit.Pixel(360);
                        cell.HorizontalAlign = HorizontalAlign.Left;
                    }
                    else
                    {
                        cell.Width = Unit.Pixel(30);
                        cell.HorizontalAlign = HorizontalAlign.Center;
                    }

                    cell.Text = Server.HtmlDecode(cell.Text);
                    cell.CssClass = "Clspadding";
                }
            }else
                cell.HorizontalAlign = HorizontalAlign.Center;
            iCnt++;
        }
    }
    #endregion

    #endregion

    #region helper methods


    /// <summary>
    /// This method is used to get required details of selected academic year.
    /// </summary>
    private void GetDetailsOfSelectedYear()
    {
        if (mbIsOldAttendanceToppersScreen && !IsPostBack)
            miAcademicYearId = Convert.ToInt32(cmbAcademicYrId.SelectedValue);
        else if (mbIsOldAttendanceToppersScreen)
            miAcademicYearId = Convert.ToInt32(cmbAcademicYrId.SelectedValue);

		int iStudentId = Convert.ToInt32(Session[Constants.S_SESSION_STUDENT_ID]);
        miStudentId = StudentBL.GetYearwiseStudentId(miSchoolId, miAcademicYearId, iStudentId);
        miOldStdDivId = SchoolWiseStanderedDivisionTestMasterBL.GetStandardDivisionIdOfYear(miSchoolId, miAcademicYearId, miStudentId);
    }

    /// <summary>
    /// This method is used to fill academic year combo on page load.
    /// </summary>
    private void FillAcademicYearCombo()
    {        
        int iStudentId = Convert.ToInt32(Session[Constants.S_SESSION_STUDENT_ID]);
        if (miAcademicYearId == 0)
            miAcademicYearId = Convert.ToInt32(Session[Constants.S_SESSION_CURRENT_ACADEMIC_YEAR_ID]);
        miStudentId = StudentBL.GetYearwiseStudentId(miSchoolId, miAcademicYearId, iStudentId);
        DataTable oDtYearInfo = SchoolWiseAcademicYearMasterBL.GetPassedAcademicYears(miSchoolId, miStudentId,false);
        if (oDtYearInfo != null && oDtYearInfo.Rows.Count > 0 && oDtYearInfo.Rows[0][0] != DBNull.Value)
            ControlUtility.FillDropDownList(oDtYearInfo, ref cmbAcademicYrId,
                                         "Value_Member",
                                         "Display_Member",
                                         "");
             if (cmbAcademicYrId.Items.Count == 1)
            cmbAcademicYrId.Enabled = false;            
    }

    /// <summary>
    /// This function initialises the sort variables
    /// </summary>
    private void SetControlsDefaultValues()
    {
        hidSortDirection.Value = Constants.S_ASCENDING;
    }


    /// <summary>
    /// This function is used to set sort variables
    /// </summary>
    private void SetSortVariables()
    {
	    hidSortDirection.Value = hidSortDirection.Value == Constants.S_DESCENDING ? Constants.S_ASCENDING : Constants.S_DESCENDING;
    }

	private void InitialiseAttributes()
    {
       btnBack.Attributes.Add("onclick", "refreshParent()");
    }

    /// <summary>
    /// This function is used to initialise field values
    /// </summary>
    private void InitializeFields()
    {
		InitializeMemberVariables();
		grdStudents.PageSize = Constants.I_GRID_PAGE_COUNT;
        grdStudents.EmptyDataText = S_BLANK_GRID_MESSAGE;
        if (!IsPostBack)
        {
            FillAcademicYearCombo();
            SetControlsDefaultValues();
			hidStdDivId.Value = QueryString["iStandardDivisionId"] ?? "0";

			if (QueryString["bIsOldTopperScreen"] != null)
            {
				mbIsOldAttendanceToppersScreen = QueryString["bIsOldTopperScreen"].ToBool();
                hidmOldAttendanceToppers.Value = mbIsOldAttendanceToppersScreen.ToString();
                if (mbIsOldAttendanceToppersScreen)
                    lblOldAcademicYear.Text = CommonUtility.DisplayAcademicYear(cmbAcademicYrId.SelectedItem.Text);
            }
            else
                hidmOldAttendanceToppers.Value = "false";
        }
        else
        {
            mbIsOldAttendanceToppersScreen = Convert.ToBoolean(hidmOldAttendanceToppers.Value);
        }

        if (!mbIsOldAttendanceToppersScreen)
        {
            tdacademicYr.Visible = false;
            cmbAcademicYrId.Visible = false;
            if (cmbAcademicYrId.Items.Count > 0)
            {
               int iAcademicYearId = Convert.ToInt32(cmbAcademicYrId.SelectedValue);
               string sNewStudent = "True";
               if (Session[Constants.S_SESSION_IS_NEW_ADMISSION] != null)
                   sNewStudent = Session[Constants.S_SESSION_IS_NEW_ADMISSION].ToString();
            }            
        }
    }

    private void ShowStudentAttendance()
    {
        grdStudents.PageSize = Constants.I_GRID_PAGE_COUNT;
        grdStudents.DataSource = StudentBL.GetStudentsMonthWiseAttendance(miSchoolId,miAcademicYearId,miOldStdDivId, 3, 0, "Present Days DESC", 100, 0);
        grdStudents.DataBind();

        grdStudentRank.PageSize = Constants.I_GRID_PAGE_COUNT;
        grdStudentRank.DataSource = StudentBL.GetStudentsMonthWiseAttendance(miSchoolId, miAcademicYearId, miOldStdDivId, 3, miStudentId, "Present Days DESC", 100, 0);
        grdStudentRank.DataBind();
    }

    #endregion

    
}
