//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- TaskManagementDC
// Purpose          :- This class is used to manage TaskMaster details.
// Date Of creation :- 6/9/2011
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using TaskManagementEntities;
using Utility;

namespace DataCommunicator
{
    public class TaskManagementDC
    {
        #region "Data Members"

        public int miSchoolId = 0;
        public int miAcademicYearId = 0;

        private DesignationwiseUserTaskDetails moDesignationwiseUserTaskDetails = null;
        private UserAssignedTaskDetails moUserAssignedTaskDetails = null;
        public  List<DesignationwiseUserTaskDetails> olstDesignationwiseUserTaskDetails = new List<DesignationwiseUserTaskDetails>();
        public List<UserAssignedTaskDetails> olstUserAssignedTaskDetails = new List<UserAssignedTaskDetails>();
        
        #endregion "Data Members"

        #region "Constructors"

        public TaskManagementDC()
        {
            moDesignationwiseUserTaskDetails = new DesignationwiseUserTaskDetails();
            moUserAssignedTaskDetails = new UserAssignedTaskDetails();
        }

        public TaskManagementDC(int iSchoolId, int iAcademicYearId)
        {
            miSchoolId = iSchoolId;
            miAcademicYearId = iAcademicYearId;
            moDesignationwiseUserTaskDetails = new DesignationwiseUserTaskDetails();
            moUserAssignedTaskDetails = new UserAssignedTaskDetails();
        }

        #endregion "Constructors"

        #region "Properties"

        public DesignationwiseUserTaskDetails oDesignationwiseUserTaskDetails
        {
            get { return moDesignationwiseUserTaskDetails; }
            set { moDesignationwiseUserTaskDetails = value; }
        }
        public UserAssignedTaskDetails oUserAssignedTaskDetails
        {
            set { moUserAssignedTaskDetails = value; }
            get { return moUserAssignedTaskDetails; }
        }
       
        #endregion "Properties"

        /// <summary>
        /// This method is used to get all the designations which are configured for logged user.
        /// </summary>
        /// <returns></returns>
        public DataTable GetDesignationsDetails(int aiUserId, int aiUserRoleId, int aiFilter)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UserRoleId", aiUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UserId", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Filter", aiFilter, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetUserDetailsForAssignTask");
            };
        }

        /// <summary>
        /// This method is used to get all the status list of task.
        /// </summary>
        /// <returns></returns>
        public DataTable GetTaskStatusList()
        {
            string sQryStmt = " SELECT TaskStatusId, StatusName " +
                              " FROM TaskStatusMaster " +
                              " WHERE Is_Deleted = N'N' ";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sQryStmt);

        }

        /// <summary>
        /// This method is used to get task status details.
        /// </summary>
        /// <returns></returns>
        public DataTable GetTaskStatusDetails(int aiTaskId, int aiTaskTypeId, int aiTaskDetailsId, int aiTaskAssignerUserId,int aiInsertedById,int aiFlag)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("TaskId", aiTaskId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskTypeId", aiTaskTypeId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskDetailsId", aiTaskDetailsId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskAssignerUserId", aiTaskAssignerUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Flag", aiFlag, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetTaskStatusDetails");
            };
        }

        /// <summary>
        /// This method is used to get all users as per the designations.
        /// </summary>
        /// <param name="aiDesignationId"></param>
        /// <returns></returns>
        public List<DesignationwiseUserTaskDetails> GetDesignationwiseUserList(int aiDesignationId, int aiTaskDetailId, int aiTaskId, int aiTaskTypeId, int aiInsertedById, int aiAssignFlag)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("DesignationId", aiDesignationId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskDetailId", aiTaskDetailId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskId", aiTaskId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskTypeId", aiTaskTypeId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AssignFlag", aiAssignFlag, SqlDbType.Int);
                using(SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetUserTaskDetailsAsPerUserAndDesignation"))
                return LoadUserDetails(oSqlDataReader);
            };
        }

        /// <summary>
        /// This method is used to load user details.
        /// </summary>
        /// <param name="aoSqlDataReader"></param>
        /// <returns></returns>
        public List<DesignationwiseUserTaskDetails> LoadUserDetails(SqlDataReader aoSqlDataReader)
        {
            DesignationwiseUserTaskDetails oDesignationwiseUserTaskDetails = null;
            while (aoSqlDataReader.Read())
            {
                oDesignationwiseUserTaskDetails = new DesignationwiseUserTaskDetails
                {
                    UserId = Convert.ToInt32(aoSqlDataReader["UserId"]),
                    UserName = Convert.ToString(aoSqlDataReader["UserName"]),
                    DesignationId = Convert.ToInt32(aoSqlDataReader["DesignationId"]),
                    DesignationName = Convert.ToString(aoSqlDataReader["DesignationName"]),
                    IsSelected = Convert.ToInt32(aoSqlDataReader["IsSelected"]),
                    TaskStatusId = Convert.ToInt32(aoSqlDataReader["TaskStatusId"]),
                    IsLoggedUser = Convert.ToInt32(aoSqlDataReader["IsLoggedUser"]),
                };
                olstDesignationwiseUserTaskDetails.Add(oDesignationwiseUserTaskDetails);
            }
            return olstDesignationwiseUserTaskDetails;
        }

        /// <summary>
        /// This method is used to save task details.
        /// </summary>
        /// <param name="asUserTaskDetailXML"></param>
        public void SaveUserTaskDetails(string asUserTaskDetailXML)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("UserTaskDetailXML", asUserTaskDetailXML, SqlDbType.Xml);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_InsertUserAssignedTaskDetail");
            };
        }

        /// <summary>
        /// This method is used to get task details.
        /// </summary>
        /// <param name="aiTaskId"></param>
        /// <param name="aiTaskDetailId"></param>
        /// <param name="aiTaskAssignerUserId"></param>
        /// <param name="aiTaskTypeId"></param>
        /// <param name="aiInsertedById"></param>
        public void GetTaskDetails(int aiTaskId, int aiTaskDetailId, int aiTaskAssignerUserId, int aiTaskTypeId, int aiInsertedById)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskId", aiTaskId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskDetailId", aiTaskDetailId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskAssignerUserId", aiTaskAssignerUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TaskTypeId", aiTaskTypeId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
                using(SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetUserTaskDetailsForUpdating"))
                LoadUserTaskDetails(oSqlDataReader);
            };
        }

        /****************Inner List View Methods*********/

        /// <summary>
        /// This method is used to get user task details.
        /// </summary>
        /// <param name="aiUserId"></param>
        /// <param name="aiDesignationId"></param>
        /// <returns></returns>
        public List<UserAssignedTaskDetails> GetUserTaskDetails(int aiUserId, int aiDesignationId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UserId", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("DesignationId", aiDesignationId, SqlDbType.Int);
                using(SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetUserAssignedTaskDetails"))
                return LoadUserAssignedTaskDetails(oSqlDataReader);
            };
        }

        /// <summary>
        /// This method is used to load user assigned task details.
        /// </summary>
        /// <param name="aoSqlDataReader"></param>
        /// <returns></returns>
        public List<UserAssignedTaskDetails> LoadUserAssignedTaskDetails(SqlDataReader aoSqlDataReader)
        {
            UserAssignedTaskDetails oUserAssignedTaskDetails = null;
            while (aoSqlDataReader.Read())
            {
                oUserAssignedTaskDetails = new UserAssignedTaskDetails
                {
                    //TaskDetailId = Convert.ToInt32(aoSqlDataReader["TaskDetailsId"]),   
                    TaskId = Convert.ToInt32(aoSqlDataReader["TaskId"]),
                    TaskName = Convert.ToString(aoSqlDataReader["TaskName"]),
                    TaskAssignerId = Convert.ToInt32(aoSqlDataReader["TaskAssignerUserId"]),
                    TaskAssignerName = Convert.ToString(aoSqlDataReader["TaskAssignerName"]),
                    StartDate = Convert.ToDateTime(aoSqlDataReader["StartDate"]),
                    StartTime = Convert.ToString(aoSqlDataReader["StartTime"]),
                    EndDate = Convert.ToDateTime(aoSqlDataReader["EndDate"]),
                    EndTime = Convert.ToString(aoSqlDataReader["EndTime"]),
                    BufferDate = Convert.ToDateTime(aoSqlDataReader["BufferDate"]),
                    BufferTime = Convert.ToString(aoSqlDataReader["BufferTime"]),
                };
                olstUserAssignedTaskDetails.Add(oUserAssignedTaskDetails);
            }
            return olstUserAssignedTaskDetails;
        }

        /// <summary>
        /// This method is used to load user task details.
        /// </summary>
        /// <param name="aoSqlDataReader"></param>
        /// <returns></returns>
        public List<UserAssignedTaskDetails> LoadUserTaskDetails(SqlDataReader aoSqlDataReader)
        {
            UserAssignedTaskDetails oUserAssignedTaskDetails = null;
            while (aoSqlDataReader.Read())
            {
                oUserAssignedTaskDetails = new UserAssignedTaskDetails
                {
                    TaskDetailId = Convert.ToInt32(aoSqlDataReader["DetailsId"]),
                    TaskId = Convert.ToInt32(aoSqlDataReader["TaskId"]),
                    TaskName = Convert.ToString(aoSqlDataReader["TaskName"]),
                    TaskDetails = Convert.ToString(aoSqlDataReader["TaskDetails"]),
                    Comments = Convert.ToString(aoSqlDataReader["Comment"]),
                    DesignationId = Convert.ToInt32(aoSqlDataReader["DesignationId"]),
                    StartDate = Convert.ToDateTime(aoSqlDataReader["StartDate"]),
                    StartTime = Convert.ToString(aoSqlDataReader["StartTime"]),
                    EndDate = Convert.ToDateTime(aoSqlDataReader["EndDate"]),
                    EndTime = Convert.ToString(aoSqlDataReader["EndTime"]),
                    BufferDate = Convert.ToDateTime(aoSqlDataReader["BufferDate"]),
                    BufferTime = Convert.ToString(aoSqlDataReader["BufferTime"]),
                    TaskTypeId = Convert.ToInt32(aoSqlDataReader["TaskTypeId"]),
                    TaskStatusId = Convert.ToInt32(aoSqlDataReader["TaskStatusId"]),
                    TaskCompletedDate = Convert.ToDateTime(aoSqlDataReader["TaskCompletedDate"]),
                    TaskCompletedCount = Convert.ToInt32(aoSqlDataReader["TaskCompletedCount"]),
                    TaskCompletedStTime = Convert.ToString(aoSqlDataReader["TaskCompletedStTime"]),
                    TaskCompletedEndTime = Convert.ToString(aoSqlDataReader["TaskCompletedEndTime"]),
                    IsLoggedUser = Convert.ToInt32(aoSqlDataReader["IsLoggedUser"]),  
					   
                };
                olstUserAssignedTaskDetails.Add(oUserAssignedTaskDetails);
            }
            return olstUserAssignedTaskDetails;
        }

        public DataTable GetUserDetails(string asXML, string asFilter,int aiFlag)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("asXML", asXML, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("Filter", asFilter, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("Flag", aiFlag, SqlDbType.Int);

                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetTaskUserDetailsForReport");
                
            };    
        }
    }
}
