//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSMSBalanceService.Client
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://businesssms.co.in/", ConfigurationName="BusinessSMSBalanceService.Client.BSWSSoap")]
    public interface BSWSSoap
    {
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/BSAcIsDynamicSenderID", ReplyAction="*")]
        BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDResponse BSAcIsDynamicSenderID(BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequest request);
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/BSAcBalance", ReplyAction="*")]
        BusinessSMSBalanceService.Client.BSAcBalanceResponse BSAcBalance(BusinessSMSBalanceService.Client.BSAcBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/BSAcBalanceExt", ReplyAction="*")]
        BusinessSMSBalanceService.Client.BSAcBalanceExtResponse BSAcBalanceExt(BusinessSMSBalanceService.Client.BSAcBalanceExtRequest request);
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/BSChangePwd", ReplyAction="*")]
        BusinessSMSBalanceService.Client.BSChangePwdResponse BSChangePwd(BusinessSMSBalanceService.Client.BSChangePwdRequest request);
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/SubmitSMS", ReplyAction="*")]
        BusinessSMSBalanceService.Client.SubmitSMSResponse SubmitSMS(BusinessSMSBalanceService.Client.SubmitSMSRequest request);
        
        // CODEGEN: Generating message contract since element name strID from namespace http://businesssms.co.in/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://businesssms.co.in/SubmitSMSI", ReplyAction="*")]
        BusinessSMSBalanceService.Client.SubmitSMSIResponse SubmitSMSI(BusinessSMSBalanceService.Client.SubmitSMSIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcIsDynamicSenderIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcIsDynamicSenderID", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequestBody Body;
        
        public BSAcIsDynamicSenderIDRequest()
        {
        }
        
        public BSAcIsDynamicSenderIDRequest(BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcIsDynamicSenderIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        public BSAcIsDynamicSenderIDRequestBody()
        {
        }
        
        public BSAcIsDynamicSenderIDRequestBody(string strID, string strPwd)
        {
            this.strID = strID;
            this.strPwd = strPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcIsDynamicSenderIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcIsDynamicSenderIDResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDResponseBody Body;
        
        public BSAcIsDynamicSenderIDResponse()
        {
        }
        
        public BSAcIsDynamicSenderIDResponse(BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcIsDynamicSenderIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement BSAcIsDynamicSenderIDResult;
        
        public BSAcIsDynamicSenderIDResponseBody()
        {
        }
        
        public BSAcIsDynamicSenderIDResponseBody(System.Xml.XmlElement BSAcIsDynamicSenderIDResult)
        {
            this.BSAcIsDynamicSenderIDResult = BSAcIsDynamicSenderIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcBalance", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcBalanceRequestBody Body;
        
        public BSAcBalanceRequest()
        {
        }
        
        public BSAcBalanceRequest(BusinessSMSBalanceService.Client.BSAcBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        public BSAcBalanceRequestBody()
        {
        }
        
        public BSAcBalanceRequestBody(string strID, string strPwd)
        {
            this.strID = strID;
            this.strPwd = strPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcBalanceResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcBalanceResponseBody Body;
        
        public BSAcBalanceResponse()
        {
        }
        
        public BSAcBalanceResponse(BusinessSMSBalanceService.Client.BSAcBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement BSAcBalanceResult;
        
        public BSAcBalanceResponseBody()
        {
        }
        
        public BSAcBalanceResponseBody(System.Xml.XmlElement BSAcBalanceResult)
        {
            this.BSAcBalanceResult = BSAcBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcBalanceExtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcBalanceExt", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcBalanceExtRequestBody Body;
        
        public BSAcBalanceExtRequest()
        {
        }
        
        public BSAcBalanceExtRequest(BusinessSMSBalanceService.Client.BSAcBalanceExtRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcBalanceExtRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        public BSAcBalanceExtRequestBody()
        {
        }
        
        public BSAcBalanceExtRequestBody(string strID, string strPwd)
        {
            this.strID = strID;
            this.strPwd = strPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSAcBalanceExtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSAcBalanceExtResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSAcBalanceExtResponseBody Body;
        
        public BSAcBalanceExtResponse()
        {
        }
        
        public BSAcBalanceExtResponse(BusinessSMSBalanceService.Client.BSAcBalanceExtResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSAcBalanceExtResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement BSAcBalanceExtResult;
        
        public BSAcBalanceExtResponseBody()
        {
        }
        
        public BSAcBalanceExtResponseBody(System.Xml.XmlElement BSAcBalanceExtResult)
        {
            this.BSAcBalanceExtResult = BSAcBalanceExtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSChangePwdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSChangePwd", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSChangePwdRequestBody Body;
        
        public BSChangePwdRequest()
        {
        }
        
        public BSChangePwdRequest(BusinessSMSBalanceService.Client.BSChangePwdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSChangePwdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNewPwd;
        
        public BSChangePwdRequestBody()
        {
        }
        
        public BSChangePwdRequestBody(string strID, string strPwd, string strNewPwd)
        {
            this.strID = strID;
            this.strPwd = strPwd;
            this.strNewPwd = strNewPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BSChangePwdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BSChangePwdResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.BSChangePwdResponseBody Body;
        
        public BSChangePwdResponse()
        {
        }
        
        public BSChangePwdResponse(BusinessSMSBalanceService.Client.BSChangePwdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class BSChangePwdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement BSChangePwdResult;
        
        public BSChangePwdResponseBody()
        {
        }
        
        public BSChangePwdResponseBody(System.Xml.XmlElement BSChangePwdResult)
        {
            this.BSChangePwdResult = BSChangePwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSMS", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.SubmitSMSRequestBody Body;
        
        public SubmitSMSRequest()
        {
        }
        
        public SubmitSMSRequest(BusinessSMSBalanceService.Client.SubmitSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class SubmitSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPhNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSchedule;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intRetryMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strSenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strSenderNo;
        
        public SubmitSMSRequestBody()
        {
        }
        
        public SubmitSMSRequestBody(string strID, string strPwd, string strPhNo, string strText, string strSchedule, int intRetryMin, string strSenderID, string strSenderNo)
        {
            this.strID = strID;
            this.strPwd = strPwd;
            this.strPhNo = strPhNo;
            this.strText = strText;
            this.strSchedule = strSchedule;
            this.intRetryMin = intRetryMin;
            this.strSenderID = strSenderID;
            this.strSenderNo = strSenderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSMSResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.SubmitSMSResponseBody Body;
        
        public SubmitSMSResponse()
        {
        }
        
        public SubmitSMSResponse(BusinessSMSBalanceService.Client.SubmitSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class SubmitSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement SubmitSMSResult;
        
        public SubmitSMSResponseBody()
        {
        }
        
        public SubmitSMSResponseBody(System.Xml.XmlElement SubmitSMSResult)
        {
            this.SubmitSMSResult = SubmitSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSMSIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSMSI", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.SubmitSMSIRequestBody Body;
        
        public SubmitSMSIRequest()
        {
        }
        
        public SubmitSMSIRequest(BusinessSMSBalanceService.Client.SubmitSMSIRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class SubmitSMSIRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPhNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strSchedule;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int intRetryMin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strSenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strSenderNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strSubInterface;
        
        public SubmitSMSIRequestBody()
        {
        }
        
        public SubmitSMSIRequestBody(string strID, string strPwd, string strPhNo, string strText, string strSchedule, int intRetryMin, string strSenderID, string strSenderNo, string strSubInterface)
        {
            this.strID = strID;
            this.strPwd = strPwd;
            this.strPhNo = strPhNo;
            this.strText = strText;
            this.strSchedule = strSchedule;
            this.intRetryMin = intRetryMin;
            this.strSenderID = strSenderID;
            this.strSenderNo = strSenderNo;
            this.strSubInterface = strSubInterface;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitSMSIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitSMSIResponse", Namespace="http://businesssms.co.in/", Order=0)]
        public BusinessSMSBalanceService.Client.SubmitSMSIResponseBody Body;
        
        public SubmitSMSIResponse()
        {
        }
        
        public SubmitSMSIResponse(BusinessSMSBalanceService.Client.SubmitSMSIResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://businesssms.co.in/")]
    public partial class SubmitSMSIResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement SubmitSMSIResult;
        
        public SubmitSMSIResponseBody()
        {
        }
        
        public SubmitSMSIResponseBody(System.Xml.XmlElement SubmitSMSIResult)
        {
            this.SubmitSMSIResult = SubmitSMSIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BSWSSoapChannel : BusinessSMSBalanceService.Client.BSWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSWSSoapClient : System.ServiceModel.ClientBase<BusinessSMSBalanceService.Client.BSWSSoap>, BusinessSMSBalanceService.Client.BSWSSoap
    {
        
        public BSWSSoapClient()
        {
        }
        
        public BSWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BSWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BSWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BSWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDResponse BusinessSMSBalanceService.Client.BSWSSoap.BSAcIsDynamicSenderID(BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequest request)
        {
            return base.Channel.BSAcIsDynamicSenderID(request);
        }
        
        public System.Xml.XmlElement BSAcIsDynamicSenderID(string strID, string strPwd)
        {
            BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequest inValue = new BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            BusinessSMSBalanceService.Client.BSAcIsDynamicSenderIDResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).BSAcIsDynamicSenderID(inValue);
            return retVal.Body.BSAcIsDynamicSenderIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.BSAcBalanceResponse BusinessSMSBalanceService.Client.BSWSSoap.BSAcBalance(BusinessSMSBalanceService.Client.BSAcBalanceRequest request)
        {
            return base.Channel.BSAcBalance(request);
        }
        
        public System.Xml.XmlElement BSAcBalance(string strID, string strPwd)
        {
            BusinessSMSBalanceService.Client.BSAcBalanceRequest inValue = new BusinessSMSBalanceService.Client.BSAcBalanceRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.BSAcBalanceRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            BusinessSMSBalanceService.Client.BSAcBalanceResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).BSAcBalance(inValue);
            return retVal.Body.BSAcBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.BSAcBalanceExtResponse BusinessSMSBalanceService.Client.BSWSSoap.BSAcBalanceExt(BusinessSMSBalanceService.Client.BSAcBalanceExtRequest request)
        {
            return base.Channel.BSAcBalanceExt(request);
        }
        
        public System.Xml.XmlElement BSAcBalanceExt(string strID, string strPwd)
        {
            BusinessSMSBalanceService.Client.BSAcBalanceExtRequest inValue = new BusinessSMSBalanceService.Client.BSAcBalanceExtRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.BSAcBalanceExtRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            BusinessSMSBalanceService.Client.BSAcBalanceExtResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).BSAcBalanceExt(inValue);
            return retVal.Body.BSAcBalanceExtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.BSChangePwdResponse BusinessSMSBalanceService.Client.BSWSSoap.BSChangePwd(BusinessSMSBalanceService.Client.BSChangePwdRequest request)
        {
            return base.Channel.BSChangePwd(request);
        }
        
        public System.Xml.XmlElement BSChangePwd(string strID, string strPwd, string strNewPwd)
        {
            BusinessSMSBalanceService.Client.BSChangePwdRequest inValue = new BusinessSMSBalanceService.Client.BSChangePwdRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.BSChangePwdRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            inValue.Body.strNewPwd = strNewPwd;
            BusinessSMSBalanceService.Client.BSChangePwdResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).BSChangePwd(inValue);
            return retVal.Body.BSChangePwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.SubmitSMSResponse BusinessSMSBalanceService.Client.BSWSSoap.SubmitSMS(BusinessSMSBalanceService.Client.SubmitSMSRequest request)
        {
            return base.Channel.SubmitSMS(request);
        }
        
        public System.Xml.XmlElement SubmitSMS(string strID, string strPwd, string strPhNo, string strText, string strSchedule, int intRetryMin, string strSenderID, string strSenderNo)
        {
            BusinessSMSBalanceService.Client.SubmitSMSRequest inValue = new BusinessSMSBalanceService.Client.SubmitSMSRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.SubmitSMSRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            inValue.Body.strPhNo = strPhNo;
            inValue.Body.strText = strText;
            inValue.Body.strSchedule = strSchedule;
            inValue.Body.intRetryMin = intRetryMin;
            inValue.Body.strSenderID = strSenderID;
            inValue.Body.strSenderNo = strSenderNo;
            BusinessSMSBalanceService.Client.SubmitSMSResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).SubmitSMS(inValue);
            return retVal.Body.SubmitSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusinessSMSBalanceService.Client.SubmitSMSIResponse BusinessSMSBalanceService.Client.BSWSSoap.SubmitSMSI(BusinessSMSBalanceService.Client.SubmitSMSIRequest request)
        {
            return base.Channel.SubmitSMSI(request);
        }
        
        public System.Xml.XmlElement SubmitSMSI(string strID, string strPwd, string strPhNo, string strText, string strSchedule, int intRetryMin, string strSenderID, string strSenderNo, string strSubInterface)
        {
            BusinessSMSBalanceService.Client.SubmitSMSIRequest inValue = new BusinessSMSBalanceService.Client.SubmitSMSIRequest();
            inValue.Body = new BusinessSMSBalanceService.Client.SubmitSMSIRequestBody();
            inValue.Body.strID = strID;
            inValue.Body.strPwd = strPwd;
            inValue.Body.strPhNo = strPhNo;
            inValue.Body.strText = strText;
            inValue.Body.strSchedule = strSchedule;
            inValue.Body.intRetryMin = intRetryMin;
            inValue.Body.strSenderID = strSenderID;
            inValue.Body.strSenderNo = strSenderNo;
            inValue.Body.strSubInterface = strSubInterface;
            BusinessSMSBalanceService.Client.SubmitSMSIResponse retVal = ((BusinessSMSBalanceService.Client.BSWSSoap)(this)).SubmitSMSI(inValue);
            return retVal.Body.SubmitSMSIResult;
        }
    }
}
