//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- StandardwiseAssessmentMasterBL
// Purpose          :- This class is used to manage StandardwiseAssessmentMaster details.
// Date Of creation :- 5/25/2011
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;
using Utility;
using XseedReportEntities;


namespace BusinessLogic
{
    public class StandardwiseAssessmentMasterBL
    {
        #region "Data Members"

        private StandardwiseAssessmentMasterDC moStandardwiseAssessmentMasterDC = null;
        public SchoolwiseAcademicYrDates moSchoolwiseAcademicYrDates = null;
        
        #endregion "Data Members"

        #region "Constructors"

        public StandardwiseAssessmentMasterBL()
        {
            moStandardwiseAssessmentMasterDC = new StandardwiseAssessmentMasterDC();
            moSchoolwiseAcademicYrDates = new SchoolwiseAcademicYrDates();
        }

        public StandardwiseAssessmentMasterBL(int iSchoolId, int iAcademicYearId)
        {
            moStandardwiseAssessmentMasterDC = new StandardwiseAssessmentMasterDC(iSchoolId, iAcademicYearId);
        }

        #endregion "Constructors"

        #region "Properties"

        public SchoolwiseAcademicYrDates SchoolwiseAcademicYrDates
        {
            get { return moStandardwiseAssessmentMasterDC.moSchoolwiseAcademicYrDates; }
            set { moStandardwiseAssessmentMasterDC.moSchoolwiseAcademicYrDates = value; }
        }

        public List<StandardwiseAssessmentMaster> lstStandardwiseAssessmentDetails
        {
            get { return moStandardwiseAssessmentMasterDC.molstStandardwiseAssessmentDetails; }
            set { moStandardwiseAssessmentMasterDC.molstStandardwiseAssessmentDetails = value; }
        }
              
        #endregion "Properties"

        #region "Public Methods"

        /// <summary>
        /// This method is used to get Standardwise Assessment Details.
        /// </summary>
        /// <param name="aiStandardId"></param>
        public void GetStandardwiseAssessmentDetails(int aiStandardId)
        {
            moStandardwiseAssessmentMasterDC.GetStandardwiseAssessmentDetails(aiStandardId);
        }

        /// <summary>
        /// This method is used to save standardwise assessment details.
        /// </summary>  
        public void SaveStandardwiseAssessmentDetails(string asStdAssXml, int aiInsertedById, int aiStandardId)
        {
            moStandardwiseAssessmentMasterDC.SaveStandardwiseAssessmentDetails(asStdAssXml, aiInsertedById, aiStandardId);
        }
        /// <summary>
        /// This method is used to get standardwise assement details list.
        /// </summary>
        /// <param name="aiStandardId"></param>
        /// <returns></returns>
        public List<StandardwiseAssessmentMaster> GetStandardwiseAssementDetailsList(int aiStandardId)
        {
            return moStandardwiseAssessmentMasterDC.GetStandardwiseAssementDetailsList(aiStandardId);
        }

        public static List<StandardwiseAssessmentMaster> GetStandardAndAssessment(int aiSchoolId, int aiAcademicYearId)
        {
            return StandardwiseAssessmentMasterDC.GetStandardAndAssessment(aiSchoolId, aiAcademicYearId);
        }
        #endregion "Public Methods"
    }
}
