//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- ItemCategoryMasterBL
// Purpose          :- This class is used to manage ItemCategoryMaster details.
// Date Of creation :- 3/8/2010
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;
using Utility;
using CategoryEntities;




namespace BusinessLogic
{


    public class ItemCategoryMasterBL
    {
        #region "CONSTANTS"
        
        private const string S_DUPLICATE_CATEGORY_NAME = "Item Category already exists.";
        #endregion "CONSTANTS"
        private ItemCategoryMasterDC.ItemCategoryMasterStruct moItemCategoryMasterStruct;

        private ItemCategoryMasterDC moItemCategoryMasterDC;

        public ItemCategoryMasterBL()
        {
            moItemCategoryMasterDC = new ItemCategoryMasterDC();
        }

        public ItemCategoryMasterBL(int aiItemCategoryID,int aiSchoolID)
        {
            moItemCategoryMasterDC = new ItemCategoryMasterDC(aiItemCategoryID, aiSchoolID);
            moItemCategoryMasterStruct = moItemCategoryMasterDC.ItemCategoryMasterStructDetails;
        }

        public virtual int ItemCategoryID
        {
            get
            {
                return moItemCategoryMasterStruct.miItemCategoryID;
            }
            set
            {
                moItemCategoryMasterStruct.miItemCategoryID = value;
            }
        }

        public virtual string ItemCategoryName
        {
            get
            {
                return moItemCategoryMasterStruct.msItemCategoryName;
            }
            set
            {
                moItemCategoryMasterStruct.msItemCategoryName = value;
            }
        }

        public virtual decimal UOMPieceCount
        {
            get
            {
                return moItemCategoryMasterStruct.msUOMPieceCount;
            }
            set
            {
                moItemCategoryMasterStruct.msUOMPieceCount = value;
            }
        }

        public virtual int School_Id
        {
            get
            {
                return moItemCategoryMasterStruct.miSchoolId;
            }
            set
            {
                moItemCategoryMasterStruct.miSchoolId = value;
            }
        }

        public virtual bool Is_Deleted
        {
            get
            {
                return moItemCategoryMasterStruct.mblnIsDeleted;
            }
            set
            {
                moItemCategoryMasterStruct.mblnIsDeleted = value;
            }
        }

        public virtual System.DateTime InsertDate
        {
            get
            {
                return moItemCategoryMasterStruct.mdtInsertDate;
            }
            set
            {
                moItemCategoryMasterStruct.mdtInsertDate = value;
            }
        }

        public virtual int InsertedById
        {
            get
            {
                return moItemCategoryMasterStruct.miInsertedById;
            }
            set
            {
                moItemCategoryMasterStruct.miInsertedById = value;
            }
        }

        public virtual System.DateTime UpdateDate
        {
            get
            {
                return moItemCategoryMasterStruct.mdtUpdateDate;
            }
            set
            {
                moItemCategoryMasterStruct.mdtUpdateDate = value;
            }
        }

        public virtual int UpdatedById
        {
            get
            {
                return moItemCategoryMasterStruct.miUpdatedById;
            }
            set
            {
                moItemCategoryMasterStruct.miUpdatedById = value;
            }
        }

        public virtual int InsertItemCategoryMaster()
        {
            moItemCategoryMasterDC.ItemCategoryMasterStructDetails = moItemCategoryMasterStruct;
            return moItemCategoryMasterDC.InsertItemCategoryMaster();
        }

        public virtual void UpdateItemCategoryMaster(int aiCategoryId)
        {
            moItemCategoryMasterDC.ItemCategoryMasterStructDetails = moItemCategoryMasterStruct;
             moItemCategoryMasterDC.UpdateItemCategoryMaster(aiCategoryId);
        }

        public virtual string DeleteItemCategoryMaster(int aiSchoolID, int aiCategoryId)
        {
            moItemCategoryMasterDC.ItemCategoryMasterStructDetails = moItemCategoryMasterStruct;
            return moItemCategoryMasterDC.DeleteItemCategoryMaster(aiSchoolID,aiCategoryId);
        }

        public static DataTable GetAll(int aiSchoolId)
        {
            return ItemCategoryMasterDC.GetAll(aiSchoolId);
        }

        /// <summary>
        /// This method is used to return all Item Categories.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <returns></returns>
        public static List<ItemCategory> GetAllCategory(int aiSchoolId)
        {
            return ItemCategoryMasterDC.GetAllCategory(aiSchoolId);
        }

        public bool IsDuplicateItemCategory()
        {
            moItemCategoryMasterDC.ItemCategoryMasterStructDetails = moItemCategoryMasterStruct;
            bool bIsDuplicate = moItemCategoryMasterDC.IsDuplicateItemCategory();
            if (bIsDuplicate == false)
                throw new BusinessLogic.Exceptions.DuplicateEntityException(S_DUPLICATE_CATEGORY_NAME);
            return bIsDuplicate;
        }
    }
}
