//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- UOMMasterBL
// Purpose          :- This class is used to manage UOMMaster details.
// Date Of creation :- 3/8/2010
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;




namespace BusinessLogic
{


    public class UOMMasterBL
    {
        #region "CONSTANTS"
        private const string S_DUPLICATE_UOM_NAME = "Unit of Measurment already exists.";
        #endregion "CONSTANTS"

        private UOMMasterDC.UOMMasterStruct moUOMMasterStruct;

        private UOMMasterDC moUOMMasterDC;

        public UOMMasterBL()
        {
            moUOMMasterDC = new UOMMasterDC();
        }

        public UOMMasterBL(int aiUOMID,int aiSchoolId)
        {
            moUOMMasterDC = new UOMMasterDC(aiUOMID, aiSchoolId);
            moUOMMasterStruct = moUOMMasterDC.UOMMasterStructDetails;
        }

        public virtual int UOMID
        {
            get
            {
                return moUOMMasterStruct.miUOMID;
            }
            set
            {
                moUOMMasterStruct.miUOMID = value;
            }
        }

        public virtual string UOMUnit
        {
            get
            {
                return moUOMMasterStruct.msUOMUnit;
            }
            set
            {
                moUOMMasterStruct.msUOMUnit = value;
            }
        }

        public virtual decimal UOMPieceCount
        {
            get
            {
                return moUOMMasterStruct.msUOMPieceCount;
            }
            set
            {
                moUOMMasterStruct.msUOMPieceCount = value;
            }
        }

        public virtual int School_Id
        {
            get
            {
                return moUOMMasterStruct.miSchoolId;
            }
            set
            {
                moUOMMasterStruct.miSchoolId = value;
            }
        }

        public virtual bool Is_Deleted
        {
            get
            {
                return moUOMMasterStruct.mblnIsDeleted;
            }
            set
            {
                moUOMMasterStruct.mblnIsDeleted = value;
            }
        }

        public virtual System.DateTime InsertDate
        {
            get
            {
                return moUOMMasterStruct.mdtInsertDate;
            }
            set
            {
                moUOMMasterStruct.mdtInsertDate = value;
            }
        }

        public virtual int InsertedById
        {
            get
            {
                return moUOMMasterStruct.miInsertedById;
            }
            set
            {
                moUOMMasterStruct.miInsertedById = value;
            }
        }

        public virtual System.DateTime UpdateDate
        {
            get
            {
                return moUOMMasterStruct.mdtUpdateDate;
            }
            set
            {
                moUOMMasterStruct.mdtUpdateDate = value;
            }
        }

        public virtual int UpdatedById
        {
            get
            {
                return moUOMMasterStruct.miUpdatedById;
            }
            set
            {
                moUOMMasterStruct.miUpdatedById = value;
            }
        }

        public virtual int InsertUOMMaster()
        {
            moUOMMasterDC.UOMMasterStructDetails = moUOMMasterStruct;
            return moUOMMasterDC.InsertUOMMaster();
        }

        public virtual void UpdateUOMMaster(int aiUOMID)
        {
            moUOMMasterDC.UOMMasterStructDetails = moUOMMasterStruct;
             moUOMMasterDC.UpdateUOMMaster(aiUOMID);
        }

        public virtual string DeleteUOMMaster(int aiSchoolId,int aiUOMID)
        {
            moUOMMasterDC.UOMMasterStructDetails = moUOMMasterStruct;
            return moUOMMasterDC.DeleteUOMMaster(aiSchoolId, aiUOMID);
        }

        public static DataTable GetAll(int aiSchoolId)
        {
            return UOMMasterDC.GetAll(aiSchoolId);
        }

        public bool IsDuplicateUOM()
        {
            moUOMMasterDC.UOMMasterStructDetails = moUOMMasterStruct;
            //return moUOMMasterDC.IsDuplicateUOM();
            bool bIsDuplicate = moUOMMasterDC.IsDuplicateUOM();
            if (bIsDuplicate == false)
                throw new BusinessLogic.Exceptions.DuplicateEntityException(S_DUPLICATE_UOM_NAME);
            return bIsDuplicate;
        }
    }
}
