//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- ShiftMasterDC
// Purpose          :- This class is used to manage TShiftMaster details.
// Date Of creation :- 12-Jul-2010
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using Utility;




namespace DataCommunicator
{
    public class ShiftMasterDC
    {
        private ShiftMasterStruct moShiftMasterStruct;
        #region " Constructors "
        public ShiftMasterDC() 
        {
        }

        public ShiftMasterDC(int miTransportShiftId,int miSchoolId,int miAcademicYearId)
        {
            LoadShiftMasterDetails(miTransportShiftId, miSchoolId, miAcademicYearId);
        }
        #endregion " Constructors "

        #region " Properties "
        public virtual ShiftMasterStruct ShiftMasterStructDetails
        {
            get {
                return moShiftMasterStruct;
            }
            set {
                moShiftMasterStruct = value;
            }
        }
        #endregion " Properties "
        ///<summary>
        /// This function is used to insert the ShiftMaster Details
        ///</summary>
       
        public virtual int InsertShiftMaster()
        {
            string sInsertStatement="INSERT INTO Transport.ShiftMaster("+
            "TransportShiftName"+
            ",SchoolId"+
            ",Academic_Year_Id"+
            ",Is_Deleted"+
            ",InsertDate"+
            ",InsertedById"+
            ",UpdateDate"+
            ",UpdatedById"+
            ",JourneyTypeId" +
            ")VALUES("+
            " N'" + StringUtility.ReplaceSingleQuoteInString(moShiftMasterStruct.msTransportShiftName, false) + "' " +
             " , " + moShiftMasterStruct.miSchoolId +
             " , " + moShiftMasterStruct.miAcademicYearId +
             " , N'" + moShiftMasterStruct.mblnIsDeleted + "' " +
             " , N'" + moShiftMasterStruct.mdtInsertDate + "' " +
             " , " + moShiftMasterStruct.miInsertedById +
             " , N'" + moShiftMasterStruct.mdtUpdateDate + "' " +
             " , " + moShiftMasterStruct.miUpdatedById +
              " , " + moShiftMasterStruct.miJourneyTypeId + 
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }
        
        ///<summary>
        /// This function is used to update the ShiftMaster Details
        ///</summary>
       
        public virtual void UpdateShiftMaster()
        {
            string sUpdateStatement = "UPDATE Transport.ShiftMaster SET " +
            "TransportShiftName= N'" + StringUtility.ReplaceSingleQuoteInString(moShiftMasterStruct.msTransportShiftName, false) + "' " +
            ",UpdateDate= N'" + DateTime.Now.ToShortDateString() + "' " +
            ",UpdatedById= " + moShiftMasterStruct.miInsertedById+
            ",JourneyTypeId= " + moShiftMasterStruct.miJourneyTypeId + 
            ""+
            " WHERE TransportShiftId=" + moShiftMasterStruct.miTransportShiftId+
            " AND "+
            "Academic_Year_Id=" + moShiftMasterStruct.miAcademicYearId+
            " AND Is_Deleted=0";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }
       ///<summary>
        /// This function is used to delete the ShiftMaster Details
       ///</summary>
      
        public virtual void DeleteShiftMaster(int aiTransportShiftId, int aiSchoolId, int aiAcademicYearId)
        {
            string sDeleteStatement = "UPDATE Transport.ShiftMaster" +
                                     " SET "+
                                     "Is_Deleted=1" +
                                     " WHERE " +
                                     " TransportShiftId=" + aiTransportShiftId +
                                     " AND SchoolId=" + aiSchoolId +
                                     " AND Academic_Year_Id=" + aiAcademicYearId +
                                     " AND Is_Deleted = 0";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);
        }
        ///<summary>
        /// This function is used to load the ShiftMaster Details
        ///</summary>
        
        private void LoadShiftMasterDetails(int miTransportShiftId, int miSchoolId, int miAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchShiftMasterDetailsFromDatabase(miTransportShiftId, miSchoolId, miAcademicYearId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    if (oDR != null)
                    {
                        while (oDR.Read())
                        {
                            if (oDR["TransportShiftId"] != DBNull.Value)
                                moShiftMasterStruct.miTransportShiftId = Convert.ToInt32(oDR["TransportShiftId"]);
                            if (oDR["TransportShiftName"] != DBNull.Value)
                                moShiftMasterStruct.msTransportShiftName = Convert.ToString(oDR["TransportShiftName"]);
                            if (oDR["SchoolId"] != DBNull.Value)
                                moShiftMasterStruct.miSchoolId = Convert.ToInt32(oDR["SchoolId"]);
                            if (oDR["Academic_Year_Id"] != DBNull.Value)
                                moShiftMasterStruct.miAcademicYearId = Convert.ToInt32(oDR["Academic_Year_Id"]);
                            if (oDR["Is_Deleted"] != DBNull.Value)
                                moShiftMasterStruct.mblnIsDeleted = Convert.ToBoolean(oDR["Is_Deleted"]);
                            if (oDR["InsertDate"] != DBNull.Value)
                                moShiftMasterStruct.mdtInsertDate = Convert.ToDateTime(oDR["InsertDate"]);
                            if (oDR["InsertedById"] != DBNull.Value)
                                moShiftMasterStruct.miInsertedById = Convert.ToInt32(oDR["InsertedById"]);
                            if (oDR["UpdateDate"] != DBNull.Value)
                                moShiftMasterStruct.mdtUpdateDate = Convert.ToDateTime(oDR["UpdateDate"]);
                            if (oDR["UpdatedById"] != DBNull.Value)
                                moShiftMasterStruct.miUpdatedById = Convert.ToInt32(oDR["UpdatedById"]);
                            if (oDR["JourneyTypeId"] != DBNull.Value)
                                moShiftMasterStruct.miJourneyTypeId = Convert.ToInt32(oDR["JourneyTypeId"]);
                        }
                    }
                }
            }
        }

        ///<summary>
        ///This function is used to fetch the ShiftMaster Details
        ///</summary>
        
        private String FetchShiftMasterDetailsFromDatabase(int miTransportShiftId, int miSchoolId, int miAcademicYearId)
        {
            string sSelectStatement = " SELECT  " + 
            "TransportShiftId"+
            ",TransportShiftName"+
            ",SchoolId"+
            ",Academic_Year_Id"+
            ",Is_Deleted"+
            ",InsertDate"+
            ",InsertedById"+
            ",UpdateDate"+
            ",UpdatedById"+
            ",JourneyTypeId" +
            " FROM Transport.ShiftMaster" +
            " WHERE TransportShiftId="+miTransportShiftId+
            " AND SchoolId=" + miSchoolId+
            " AND Academic_Year_Id=" + miAcademicYearId;
            return sSelectStatement;
        }

        
        public struct ShiftMasterStruct 
        {
            public int miTransportShiftId;
            
            public string msTransportShiftName;
            
            public int miSchoolId;
            
            public int miAcademicYearId;
            
            public bool mblnIsDeleted;
            
            public System.DateTime mdtInsertDate;
            
            public int miInsertedById;
            
            public System.DateTime mdtUpdateDate;
            
            public int miUpdatedById;

            public int miJourneyTypeId;
        }
        /// <summary>
        /// This function is used to get all Shift Name details and bind to object data source. 
        /// </summary>
        public static DataTable GetAll(int aiSchoolId, int aiAcademicYearId, String sSortExpression, int iEndIndex, int startRowIndex)
        {
            if (sSortExpression == string.Empty || sSortExpression == "Name" || sSortExpression == "Name ASC")
                sSortExpression = "TransportShiftName";
            else if (sSortExpression == "Name DESC")
                sSortExpression = "TransportShiftName DESC";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StartIndex", startRowIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EndIndex", iEndIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SortExp", " ORDER BY " + sSortExpression, SqlDbType.NVarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("Transport.usp_GetPagedShiftMaster");
            }

        }
        /// <summary>
        /// This function is used to get total count of Shift Names and bind to object data source. 
        /// </summary>
        public static int CountTotalShiftMaster(Int32 aiSchoolId, int aiAcademicYearId, String sortExpression, int maximumRows, int startRowIndex)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("Transport.usp_GetCountShiftMaster");
                return Convert.ToInt32(oSqlParameter.Value);
            }
        }
        /// <summary>
        /// This function is used to get total count, used to Configure Screen.
        /// </summary>
        public static DataTable GetAll(int aiSchoolId, int aiAcademicYearId)
        {
            string sStatement = " SELECT  * " +

              " FROM Transport.ShiftMaster" +
              "  WHERE " +
              " SchoolId = " + aiSchoolId +
              " AND Academic_Year_Id = " + aiAcademicYearId +
              " AND Is_Deleted=0";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sStatement);

        }
        /// <summary>
        /// This function is used to duplicate entry of Stop Name.
        /// </summary>
        /// <returns></returns>
        public bool IsDuplicateShiftName()
        {
            string sWhere = "";
            bool bFlag = true;
            if (moShiftMasterStruct.miTransportShiftId != 0)
            {
                sWhere = " AND TransportShiftId<> N'" + moShiftMasterStruct.miTransportShiftId + "'";
            }
            string sSelectStatement= "SELECT COUNT(*) "+
                " FROM Transport.ShiftMaster " +
                "  WHERE " +
                " SchoolId = " + moShiftMasterStruct.miSchoolId +
                " AND Academic_Year_Id = " + moShiftMasterStruct.miAcademicYearId +
                " AND Is_Deleted=0 " +
                " AND TransportShiftName=N'" + StringUtility.ReplaceSingleQuoteInString(moShiftMasterStruct.msTransportShiftName, false) + "'" +
                  sWhere;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                int i = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
                if(i>0)
                 bFlag = false;
            }
            return bFlag;
        }
        public int CheckDependencyForShiftName(int aiTransportShiftId, int aiSchoolId, int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("TransportShiftId", aiTransportShiftId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("Transport.usp_CheckDependencyForShiftName");
                return Convert.ToInt32(oSqlParameter.Value);
            }
        }

    }
}
