//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- ImageGalleryBL
// Purpose          :- This class is used to manage ImageGallery details.
// Date Of creation :- 15/11/2008
// Author Name      :- Pallavi


using System.Data;
using DataCommunicator;
using System.Collections.Generic;
using SchoolEntities;
using Utility;
using System;

namespace BusinessLogic
{

    public class ImageGalleryBL
    {

        private ImageGalleryDC.ImageGalleryStruct moImageGalleryStruct;

        private ImageGalleryDC moImageGalleryDC;

        public ImageGalleryBL()
        {
            moImageGalleryDC = new ImageGalleryDC();
        }
        public string ClassesIds
        {
            get
            {
                return moImageGalleryStruct.miClassesIds;
            }
            set
            {
                moImageGalleryStruct.miClassesIds = value;
            }
        }
       
        public int GalleryId
        {
            get
            {
                return moImageGalleryStruct.miGalleryId;
            }
            set
            {
                moImageGalleryStruct.miGalleryId = value;
            }
        }

        public int SchoolId
        {
            get
            {
                return moImageGalleryStruct.miSchoolId;
            }
            set
            {
                moImageGalleryStruct.miSchoolId = value;
            }
        }

        public int AcademicYrId
        {
            get
            {
                return moImageGalleryStruct.miAcademicYrId;
            }
            set
            {
                moImageGalleryStruct.miAcademicYrId = value;
            }
        }

        public string GalleryName
        {
            get
            {
                return moImageGalleryStruct.msGalleryName;
            }
            set
            {
                moImageGalleryStruct.msGalleryName = value;
            }
        }

        public string OrgGalleryName
        {
            get
            {
                return moImageGalleryStruct.msOrgGalleryName;
            }
            set
            {
                moImageGalleryStruct.msOrgGalleryName = value;
            }
        }



        public string ImageDetails
        {
            get
            {
                return moImageGalleryStruct.msPhotoDetails;
            }
            set
            {
                moImageGalleryStruct.msPhotoDetails = value;
            }
        }

        public string Comment
        {
            get
            {
                return moImageGalleryStruct.msComment;
            }
            set
            {
                moImageGalleryStruct.msComment = value;
            }
        }

        public int Inserted_By_id
        {
            get
            {
                return moImageGalleryStruct.miInsertedByid;
            }
            set
            {
                moImageGalleryStruct.miInsertedByid = value;
            }
        }

        public string AssociatedSection
        {
            get
            {
                return moImageGalleryStruct.msAssociatedSection;
            }
            set
            {
                moImageGalleryStruct.msAssociatedSection = value;
            }
        }
        

        /// <summary>
        /// This method is used to insert/update photo gallery.
        /// </summary>
        public void SavePhotoGallery()
        {
            moImageGalleryDC.ImageGalleryStructDetails = moImageGalleryStruct;
            moImageGalleryDC.SavePhotoGallery();

        }

        /// <summary>
        /// This method is used to count photos of selected gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <returns></returns>
        public int GetPhotoCount(string asGalleryName)
        {
            moImageGalleryDC.ImageGalleryStructDetails = moImageGalleryStruct;
            return moImageGalleryDC.GetPhotoCount(asGalleryName);
        }

        /// <summary>
        /// This method is used to get all the images of selected gallery.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="asGalleryName"></param>
        /// <returns></returns>
        public static DataTable GetImages(int aiSchoolId, string asGalleryName)
        {
            return ImageGalleryDC.GetImages(aiSchoolId, asGalleryName);
        }
        public static DataSet GetAllImages(int aiSchoolId)
        {
            return ImageGalleryDC.GetAllImages(aiSchoolId);
        }

        public static void UpdateGalleryName(string asOldName, string asNewName, int aiUpdatedById, string asSectionIds, string asClassesIds)
        {
            ImageGalleryDC.UpdateGalleryName(asOldName, asNewName, aiUpdatedById, asSectionIds, asClassesIds);
        }

        /// <summary>
        /// This method 
        /// </summary>
        public void UpdateComment()
        {
            moImageGalleryDC.ImageGalleryStructDetails = moImageGalleryStruct;
            moImageGalleryDC.UpdateComment();
        }

        /// <summary>
        /// This method is used to retrieve all sections for photo gallery.
        /// </summary>
        /// <returns></returns>
        public List<ImageGallery> GetAllCategories()
        {
            return moImageGalleryDC.GetAllCategories();
        }
        public List<StandardDivisions>GetStandrdDiVision(int aiSchoolId,int aiAcademicYearId)
        {
            return moImageGalleryDC.GetStandrdDiVision(aiSchoolId,aiAcademicYearId);
        }
        /// <summary>
        /// This method is used to retrieve sections for particular photo gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <returns></returns>
        public List<int> GetSectionsForParticularPhotoGallery(string asGalleryName, int aiSchoolId)
        {
            return moImageGalleryDC.GetSectionsForParticularPhotoGallery(asGalleryName,aiSchoolId);
        }
        /// <summary>
        /// This method is used to retrieve StandardDivisions for particular photo gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <param name="aiSchoolId"></param>
        /// <returns></returns>
        public List<int> GetStandardDivisionsPhotoGallery(string asGalleryName, int aiSchoolId)
        {
            return moImageGalleryDC.GetStandardDivisionsPhotoGallery(asGalleryName, aiSchoolId);
        }
        /// <summary>
        /// This method is used to retrieve sections for particular photo gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <returns></returns>
        public List<PhotoGallerySectionAssociation> GetPhotoGalleryForParticularSection(int aiSectionId, int aiSchoolId)
        {
            return moImageGalleryDC.GetPhotoGalleryForParticularSection(aiSectionId,aiSchoolId);
        }

        /// <summary>
        /// This method is used to delete perticular photo.
        /// </summary>
        /// <param name="aiGalleryId"></param>
        public static void DeletePhoto(int aiGalleryId)
        {
            ImageGalleryDC.DeletePhoto(aiGalleryId);
        }
        /// <summary>
        /// This method is used to delete photo gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        public static void DeletePhotoGallery(string asGalleryName)
        {
            ImageGalleryDC.DeletePhotoGalleryName(asGalleryName);
        }
        /// <summary>
        /// This method is used to check duplication for gallery name.
        /// </summary>
        /// <param name="asOperation"></param>
        /// <returns></returns>
        public bool IsDuplicatePhotoGalleryName(string asOperation)
        {
            moImageGalleryDC.ImageGalleryStructDetails = moImageGalleryStruct;
            DataTable oDataTable = moImageGalleryDC.IsDuplicatePhotoGalleryName(asOperation);
            if (oDataTable != null)
            {
                int iRowCount = Convert.ToInt32(oDataTable.Rows[0][0]);
                if (iRowCount > 0)
                    return true;
                else
                    return false;
            }
            else
                return false;
        }

        public List<PhotoGallerySectionAssociation> GetAllPhotoGallery(int aiSchoolId, int aiGalleryTypeId)
        {
            ImageGalleryCollectionDC oImageGalleryCollectionDC = new ImageGalleryCollectionDC();
            return oImageGalleryCollectionDC.GetAllPhotoGallery(aiSchoolId, aiGalleryTypeId);
        }

    }

    public class ImageGalleryCollectionBL
    {

        /// <summary>
        /// This method is used to Fetch all photos of selected gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYrId"></param>
        /// <returns></returns>
        public static DataTable FetchPhotosForGallery(string asGalleryName, int aiSchoolId, int aiAcademicYrId)
        {
            return ImageGalleryCollectionDC.FetchImagesForGallery(asGalleryName, aiSchoolId, aiAcademicYrId);
        }

        /// <summary>
        /// This method is used to Fetch all photos of selected gallery.
        /// </summary>
        /// <param name="asGalleryName"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYrId"></param>
        /// <returns></returns>
        public static DataTable FetchVideosForGallery(int aiVideoId, int aiSchoolId, int aiSubjectId)
        {
            return ImageGalleryCollectionDC.FetchVideosForGallery(aiVideoId, aiSchoolId, aiSubjectId);
        }

        /// <summary>
        /// This table is used to fetch all galleries with count.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYrId"></param>
        /// <returns></returns>
        public static DataTable GetAllGallriesWithCount(int aiSchoolId)
        {
            return ImageGalleryCollectionDC.GetAllGallriesWithCount(aiSchoolId);
        }

        //public static DataTable FetchAllGalleries(int aiSchoolId, int aiAcademicYrId)
        //{
        //    return ImageGalleryCollectionDC.FetchAllGalleries(aiSchoolId, aiAcademicYrId);
        //}

        /// <summary>
        /// This method is used to fetch all galleries details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAccYrId"></param>
        /// <param name="sortExp"></param>
        /// <param name="maximumRows"></param>
        /// <param name="startRowIndex"></param>
        /// <returns></returns>
        public DataTable GetPhotoGalleryDetails(int aiSchoolId, int aiAccYrId, string sortExp, int maximumRows, int startRowIndex)
        {
            return ImageGalleryCollectionDC.GetPhotoGalleryDetails(Convert.ToInt32(System.Web.HttpContext.Current.Session[Constants.S_SESSION_SCHOOL_ID]), Convert.ToInt32(System.Web.HttpContext.Current.Session[Constants.S_SESSION_CURRENT_ACADEMIC_YEAR_ID]), sortExp, Constants.I_GRID_PAGE_COUNT, startRowIndex);
        }
        /// <summary>
        /// This method is used to get count of total galleries.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAccYrId"></param>
        /// <param name="sortExp"></param>
        /// <returns></returns>
        public int CountPhotoGalleries(int aiSchoolId, int aiAccYrId, string sortExp)
        {
            return ImageGalleryCollectionDC.CountPhotoGalleries(Convert.ToInt32(System.Web.HttpContext.Current.Session[Constants.S_SESSION_SCHOOL_ID]), Convert.ToInt32(System.Web.HttpContext.Current.Session[Constants.S_SESSION_CURRENT_ACADEMIC_YEAR_ID]));
        }


       
    }
}
