//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- InternalFeeDetailsBL
// Purpose          :- This class is used to manage InternalFeeDetails details.
// Date Of creation :- 5/5/2010
// Author Name      :- 


using System;
using System.Data;
using DataCommunicator;
using FeeEntities;
using System.Collections.Generic;

namespace BusinessLogic
{


    public class InternalFeeDetailsBL
    {

        private InternalFeeDetailsDC.InternalFeeDetailsStruct moInternalFeeDetailsStruct;

        private InternalFeeDetailsDC moInternalFeeDetailsDC;

        private int miStudentCountForInternalFee;

        public InternalFeeDetailsBL()
        {
            moInternalFeeDetailsDC = new InternalFeeDetailsDC();
        }

        public InternalFeeDetailsBL(int miInternalFeeDetailsId)
        {
            moInternalFeeDetailsDC = new InternalFeeDetailsDC(miInternalFeeDetailsId);
            moInternalFeeDetailsStruct = moInternalFeeDetailsDC.InternalFeeDetailsStructDetails;
        }

        public virtual int InternalFeeDetailsId
        {
            get
            {
                return moInternalFeeDetailsStruct.miInternalFeeDetailsId;
            }
            set
            {
                moInternalFeeDetailsStruct.miInternalFeeDetailsId = value;
            }
        }

        public virtual int ReceiptNo
        {
            get
            {
                return moInternalFeeDetailsStruct.miReceiptNo;
            }
            set
            {
                moInternalFeeDetailsStruct.miReceiptNo = value;
            }
        }

        public virtual int Schoolwise_Student_Id
        {
            get
            {
                return moInternalFeeDetailsStruct.miSchoolwiseStudentId;
            }
            set
            {
                moInternalFeeDetailsStruct.miSchoolwiseStudentId = value;
            }
        }

        public virtual int Amount
        {
            get
            {
                return moInternalFeeDetailsStruct.miAmount;
            }
            set
            {
                moInternalFeeDetailsStruct.miAmount = value;
            }
        }

        public virtual System.DateTime PaidDate
        {
            get
            {
                return moInternalFeeDetailsStruct.mdtPaidDate;
            }
            set
            {
                moInternalFeeDetailsStruct.mdtPaidDate = value;
            }
        }

        public virtual string Remark
        {
            get
            {
                return moInternalFeeDetailsStruct.msRemark;
            }
            set
            {
                moInternalFeeDetailsStruct.msRemark = value;
            }
        }

        public virtual int SchoolId
        {
            get
            {
                return moInternalFeeDetailsStruct.miSchoolId;
            }
            set
            {
                moInternalFeeDetailsStruct.miSchoolId = value;
            }
        }

        public virtual int AcademicYearId
        {
            get
            {
                return moInternalFeeDetailsStruct.miAcademicYearId;
            }
            set
            {
                moInternalFeeDetailsStruct.miAcademicYearId = value;
            }
        }

        public virtual int InsertedById
        {
            get
            {
                return moInternalFeeDetailsStruct.miInsertedById;
            }
            set
            {
                moInternalFeeDetailsStruct.miInsertedById = value;
            }
        }

        public virtual System.DateTime InsertDate
        {
            get
            {
                return moInternalFeeDetailsStruct.mdtInsertDate;
            }
            set
            {
                moInternalFeeDetailsStruct.mdtInsertDate = value;
            }
        }

        public virtual int UpdatedById
        {
            get
            {
                return moInternalFeeDetailsStruct.miUpdatedById;
            }
            set
            {
                moInternalFeeDetailsStruct.miUpdatedById = value;
            }
        }

        public virtual System.DateTime UpdateDate
        {
            get
            {
                return moInternalFeeDetailsStruct.mdtUpdateDate;
            }
            set
            {
                moInternalFeeDetailsStruct.mdtUpdateDate = value;
            }
        }

        public string InternalFeeDetailsIds
        {
            get
            {
                return moInternalFeeDetailsStruct.msInternalFeeDetailsIds;
            }
            set
            {
                moInternalFeeDetailsStruct.msInternalFeeDetailsIds = value;
            }
        }

        public bool ShowConsolidatedPartialPayments
        {
            get
            {
                return moInternalFeeDetailsStruct.mbShowConsolidatedPartialPayments;
            }
            set
            {
                moInternalFeeDetailsStruct.mbShowConsolidatedPartialPayments = value;
            }
        }

        public DataTable InsertInternalFeeDetails(string asInternalFeeDebitDetails, int aiUserId, int aiSchoolId, int aiAcademicYearId, DateTime aDtSelectedDate, int aiStudentId, string asChequeDetailsXml, int aiPaymentTypeId, bool abIsNextYearPayment, string asElectronicDetailsXml)
        {
            //moInternalFeeDetailsDC.InternalFeeDetailsStructDetails = moInternalFeeDetailsStruct;
            return moInternalFeeDetailsDC.InsertInternalFeeDetails(asInternalFeeDebitDetails, aiUserId, aiSchoolId, aiAcademicYearId, aDtSelectedDate, aiStudentId, asChequeDetailsXml, aiPaymentTypeId, abIsNextYearPayment, asElectronicDetailsXml);
        }

        public DataTable InsertDuplicateInternalFeeReceiptDetails()
        {
            moInternalFeeDetailsDC.InternalFeeDetailsStructDetails = moInternalFeeDetailsStruct;
            return moInternalFeeDetailsDC.InsertDuplicateInternalFeeReceiptDetails();
        }

        public virtual void UpdateInternalFeeDetails()
        {
            moInternalFeeDetailsDC.InternalFeeDetailsStructDetails = moInternalFeeDetailsStruct;
            moInternalFeeDetailsDC.UpdateInternalFeeDetails();
        }

        public virtual void DeleteInternalFeeDetails(int aiInternalFeeDetailsId)
        {
            moInternalFeeDetailsDC.InternalFeeDetailsStructDetails = moInternalFeeDetailsStruct;
            moInternalFeeDetailsDC.DeleteInternalFeeDetails(aiInternalFeeDetailsId);
        }

        public void DeleteInternalFeeDetails(int aiInternalFeeDetailsId, int aiSchoolId, int aiAcademicYearId, int aiStudentId, int aiUpdatedById, bool abIsNextYearPayment, int aiInternalFeeMasterId)
        {
            moInternalFeeDetailsDC.DeleteInternalFeeDetails(aiInternalFeeDetailsId, aiSchoolId, aiAcademicYearId, aiStudentId, aiUpdatedById, abIsNextYearPayment, aiInternalFeeMasterId);
        }

        public DataTable GetStudentInternalFeeDetails(int aiSchoolId, int aiAcademicYearId, string asRegNo, String sortExpression, int maximumRows, int startRowIndex)
        {
            DataTable oDT = moInternalFeeDetailsDC.GetStudentInternalFeeDetails(aiSchoolId, aiAcademicYearId, asRegNo, sortExpression, maximumRows, startRowIndex);
            if (oDT != null && oDT.Rows.Count > 0)
                miStudentCountForInternalFee = Convert.ToInt32(oDT.Rows[0]["TotalRows"]);
            return oDT;
        }
        public int CountStudents(int aiSchoolId, int aiAcademicYearId, string asRegNo)
        {
            return miStudentCountForInternalFee;
        }

        public static DataTable GetInternalFeesStudentForSMS(int aiSchoolId, int aiAcademicYearId, string asRegNo, bool abIncludePaid, bool abIsPayForNextYear, string adtFromDate, string adtToDate, string asFeeTypeID)
        {
            return InternalFeeDetailsDC.GetInternalFeesStudentForSMS(aiSchoolId, aiAcademicYearId, asRegNo, abIncludePaid, abIsPayForNextYear, adtFromDate, adtToDate, asFeeTypeID);
        }

        public static bool IsMidGenreated(int aiAcademicYearId, int aiSchoolID)
        {
            return InternalFeeDetailsDC.IsMidGenreated(aiAcademicYearId, aiSchoolID);
        }

        public static DataTable GetRemark(int aiSchoolId, int aiAcademicYearId, int aiInternalFeeDetailsId)
        {
            return InternalFeeDetailsDC.GetRemark(aiSchoolId, aiAcademicYearId, aiInternalFeeDetailsId);
        }

        /// <summary>
        /// This is used to get the Internal Fee debit/credit details of selected student.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStudentId"></param>
        /// <returns></returns>
        public List<InternalFeeDebitDetails> GetInternalFeeDebitDetails(int aiSchoolId, int aiAcademicYearId, int aiStudentId, bool abIsNextYearFeePayment = false)
        {
            InternalFeeDetailsDC oInternalFeeDetailsDC = new InternalFeeDetailsDC();
            return oInternalFeeDetailsDC.GetInternalFeeDebitDetails(aiSchoolId, aiAcademicYearId, aiStudentId, abIsNextYearFeePayment);
        }

        /// <summary>
        /// This is used to get the Internal Fee debit/credit details of selected student.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStudentId"></param>
        /// <returns></returns>
        public List<InternalFeeDebitDetails> GetInternalFeeDebitDetailsForOnlinePayment(int aiSchoolId, int aiAcademicYearId, int aiStudentId, bool abIsNextYearFeePayment = false)
        {
            InternalFeeDetailsDC oInternalFeeDetailsDC = new InternalFeeDetailsDC();
            return oInternalFeeDetailsDC.GetInternalFeeDebitDetailsForOnlinePayment(aiSchoolId, aiAcademicYearId, aiStudentId, abIsNextYearFeePayment);
        }

        public static List<InternalFeeDetails> GetInternalFeeDetailsForPayment(int aiSchoolId, int aiAcademicYearId, int aiStudentId)
        {
            return InternalFeeDetailsDC.GetInternalFeeDetailsForPayment(aiSchoolId, aiAcademicYearId, aiStudentId);
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear, int aiStandardID)
        {
            return InternalFeeDetailsDC.GetInternalFee(aiSchoolId, aiAcademicYear, aiStandardID);
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear, int aiStandardID, int aiDivisionID)
        {
            return InternalFeeDetailsDC.GetInternalFee(aiSchoolId, aiAcademicYear, aiStandardID, aiDivisionID);
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear)
        {
            return InternalFeeDetailsDC.GetInternalFee(aiSchoolId, aiAcademicYear);
        }

        public static DataSet GetRecieptDetails(int aiSchoolId, int aiReceiptId, int aiInternalFeeDetailsId, int aiCurrAcadYerId, int aiAcademicYear, int aiStudentId, int aiDuplicateInternalFeeDetailsId, bool abIsNextYearPayment, int aiSerialNumber)
        {
            return InternalFeeDetailsDC.GetRecieptDetails(aiSchoolId, aiReceiptId, aiInternalFeeDetailsId, aiCurrAcadYerId, aiAcademicYear, aiStudentId, aiDuplicateInternalFeeDetailsId, abIsNextYearPayment, aiSerialNumber);
        }

        public bool IsDuplicateChequeNumber(int aiSchoolId, int aiAcademicYearId, string asChequeNumber, int aiStudentId, int aiBankId, bool abIsNextYearPayment)
        {
            return moInternalFeeDetailsDC.IsDuplicateChequeNumber(aiSchoolId, aiAcademicYearId, asChequeNumber, aiStudentId, aiBankId, abIsNextYearPayment);
        }

        public bool IsDuplicateTransactionNumber(int aiSchoolId, int aiAcademicYearId, string asTransactionNo, int aiStudentId, int aiBankId, bool abIsNextYearPayment, int aiElectronicTypeId)
        {
            return moInternalFeeDetailsDC.IsDuplicateTransactionNumber(aiSchoolId, aiAcademicYearId, asTransactionNo, aiStudentId, aiBankId, abIsNextYearPayment, aiElectronicTypeId);
        }
    }
}
