//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- LCDetailsBL
// Purpose          :- This class is used to manage LCDetails details.
// Date Of creation :- 3/8/2008
// Author Name      :- 


using System;
using DataCommunicator;
namespace BusinessLogic
{
    public class LCDetailsBL
    {
      private LCDetailsDC.LCDetailsStruct moLCDetailsStruct;

        private LCDetailsDC moLCDetailsDC;

        public LCDetailsBL()
        {
            moLCDetailsDC = new LCDetailsDC();
        }

        public LCDetailsBL( int miSchoolId, int miStudentId)
        {
            moLCDetailsDC = new LCDetailsDC(miSchoolId , miStudentId);
            moLCDetailsStruct = moLCDetailsDC.LCDetailsStructDetails;
        }
        public LCDetailsBL(int miSchoolId, string msStudentId)
        {
            moLCDetailsDC = new LCDetailsDC(miSchoolId, msStudentId);
            moLCDetailsStruct = moLCDetailsDC.LCDetailsStructDetails;
        }

         public int LC_Details_Id
        {
            get
            {
                return moLCDetailsStruct.miLCDetailsId;
            }
            set
            {
                moLCDetailsStruct.miLCDetailsId = value;
            }
        }

        public string PENNo
        {
            get
            {
                return moLCDetailsStruct.msPENNo;
            }
            set
            {
                moLCDetailsStruct.msPENNo = value;
            }
        }

        public string ApaarId
        {
            get
            {
                return moLCDetailsStruct.msApaarId;
            }
            set
            {
                moLCDetailsStruct.msApaarId = value;
            }
        }


        public int School_Id
        {
            get
            {
                return moLCDetailsStruct.miSchoolId;
            }
            set
            {
                moLCDetailsStruct.miSchoolId = value;
            }
        }

        public int Student_Id
        {
            get
            {
                return moLCDetailsStruct.miStudentId;
            }
            set
            {
                moLCDetailsStruct.miStudentId = value;
            }
        }

        public string Birthplace
        {
            get
            {
                return moLCDetailsStruct.msBirthplace;
            }
            set
            {
                moLCDetailsStruct.msBirthplace = value;
            }
        }

        public string Birthtaluka
        {
            get
            {
                return moLCDetailsStruct.msBirthTaluka;
            }
            set
            {
                moLCDetailsStruct.msBirthTaluka = value;
            }
        }

        public string Birthdistrict
        {
            get
            {
                return moLCDetailsStruct.msBirthDistrict;
            }
            set
            {
                moLCDetailsStruct.msBirthDistrict = value;
            }
        }

        public string State
        {

            get
            {
                return moLCDetailsStruct.msState;
            }
            set
            {
                moLCDetailsStruct.msState = value;
            }

        }

        public string Country
        {

            get
            {
                return moLCDetailsStruct.msCountry;
            }
            set
            {
                moLCDetailsStruct.msCountry = value;
            }

        }


        public string AadharCardNo
        {

            get
            {
                return moLCDetailsStruct.msAadharCardNo;
            }
            set
            {
                moLCDetailsStruct.msAadharCardNo = value;
            }

        }

        public string UDISENumber
        {
            get
            {
                return moLCDetailsStruct.msUDISENumber;
            }
            set
            {
                moLCDetailsStruct.msUDISENumber = value;
            }
        }

        public string Last_school_name
        {
            get
            {
                return moLCDetailsStruct.msLastSchoolName;
            }
            set
            {
                moLCDetailsStruct.msLastSchoolName = value;
            }
        }

        public string Last_school_attended
        {
            get
            {
                return moLCDetailsStruct.msLastschoolattended;
            }
            set
            {
                moLCDetailsStruct.msLastschoolattended = value;
            }
        }

        public string Last_School_Standard
        {
            get
            {
                return moLCDetailsStruct.msLastSchoolStandard;
            }
            set
            {
                moLCDetailsStruct.msLastSchoolStandard = value;
            }
        }

        public string Progress_Details
        {
            get
            {
                return moLCDetailsStruct.msProgressDetails;
            }
            set
            {
                moLCDetailsStruct.msProgressDetails = value;
            }
        }

        public string Behavior_Details
        {
            get
            {
                return moLCDetailsStruct.msBehaviorDetails;
            }
            set
            {
                moLCDetailsStruct.msBehaviorDetails = value;
            }
        }

        public string Class_Name_While_Leaving
        {
            get
            {
                return moLCDetailsStruct.msClassNameWhileLeaving;
            }
            set
            {
                moLCDetailsStruct.msClassNameWhileLeaving = value;
            }
        }

        public string Academic_Year_While_Leaving
        {
            get
            {
                return moLCDetailsStruct.msAcademicYearWhileLeaving;
            }
            set
            {
                moLCDetailsStruct.msAcademicYearWhileLeaving = value;
            }
        }

        public System.DateTime Date_of_Leaving
        {
            get
            {
                return moLCDetailsStruct.mdtDateofLeaving;
            }
            set
            {
                moLCDetailsStruct.mdtDateofLeaving = value;
            }
        }

        public string DateOfLeavingInWord
        {
            get
            {
                return moLCDetailsStruct.msDateOfLeavingInWord;
            }
            set
            {
                moLCDetailsStruct.msDateOfLeavingInWord = value;
            }
        }

        public string Reason_Of_Leaving
        {
            get
            {
                return moLCDetailsStruct.msReasonOfLeaving;
            }
            set
            {
                moLCDetailsStruct.msReasonOfLeaving = value;
            }
        }

        public string Remarks
        {
            get
            {
                return moLCDetailsStruct.msRemarks;
            }
            set
            {
                moLCDetailsStruct.msRemarks = value;
            }
        }

        public string LC_Note
        {
            get
            {
                return moLCDetailsStruct.msLCNote;
            }
            set
            {
                moLCDetailsStruct.msLCNote = value;
            }
        }

        public DateTime LC_Creation_Date
        {
            get
            {
                return moLCDetailsStruct.mdtLCCreationDate;
            }
            set
            {
                moLCDetailsStruct.mdtLCCreationDate = value;
            }
        }

        public DateTime Insert_Date
        {
            get
            {
                return moLCDetailsStruct.mdtInsertDate;
            }
            set
            {
                moLCDetailsStruct.mdtInsertDate = value;
            }
        }

        public int Inserted_By_Id
        {
            get
            {
                return moLCDetailsStruct.miInsertedById;
            }
            set
            {
                moLCDetailsStruct.miInsertedById = value;
            }
        }

        public DateTime Update_Date
        {
            get
            {
                return moLCDetailsStruct.mdtUpdateDate;
            }
            set
            {
                moLCDetailsStruct.mdtUpdateDate = value;
            }
        }

        public int Updated_By_Id
        {
            get
            {
                return moLCDetailsStruct.miUpdatedById;
            }
            set
            {
                moLCDetailsStruct.miUpdatedById = value;
            }
        }

        public int SerialNumber
        {
            get
            {
                return moLCDetailsStruct.miSerialNumber;
            }
            set
            {
                moLCDetailsStruct.miSerialNumber = value;
            }
        }

        public string EnrolmentNumber
        {
            get
            {
                return moLCDetailsStruct.msEnrolmentNumber;
            }
            set
            {
                moLCDetailsStruct.msEnrolmentNumber = value;
            }
        }

        public string LCEnrolmentNumber
        {
            get
            {
                return moLCDetailsStruct.msLCEnrolmentNumbar;
            }
            set
            {
                moLCDetailsStruct.msLCEnrolmentNumbar = value;
            }
        }

        public string ClassNameWhileAdmission
        {
            get
            {
                return moLCDetailsStruct.msClassNameWhileAdmission;
            }
            set
            {
                moLCDetailsStruct.msClassNameWhileAdmission = value;
            }
        }

        public string StudentName
        {
            get
            {
                return moLCDetailsStruct.msStudentName;
            }
            set
            {
                moLCDetailsStruct.msStudentName = value;
            }
        }

        public string CasteAndSubCaste
        {
            get
            {
                return moLCDetailsStruct.msCasteAndSubCaste;
            }
            set
            {
                moLCDetailsStruct.msCasteAndSubCaste = value;
            }
        }

        public string MotherName
        {
            get
            {
                return moLCDetailsStruct.msMotherName;
            }
            set
            {
                moLCDetailsStruct.msMotherName = value;
            }
        }

        public string FatherName
        {
            get
            {
                return moLCDetailsStruct.msFatherName;
            }
            set
            {
                moLCDetailsStruct.msFatherName = value;
            }
        }


        public string ParentName
        {
            get
            {
                return moLCDetailsStruct.msParentName;
            }
            set
            {
                moLCDetailsStruct.msParentName = value;
            }
        }

        public DateTime AdmissionDate
        {
            get
            {
                return moLCDetailsStruct.mdtAdmissionDate;
            }
            set
            {
                moLCDetailsStruct.mdtAdmissionDate = value;
            }
        }

        public string Nationality
        {
            get
            {
                return moLCDetailsStruct.msNationality;
            }
            set
            {
                moLCDetailsStruct.msNationality = value;
            }
        }


        public string DOBText
        {
            get
            {
                return moLCDetailsStruct.msDOBText;
            }
            set
            {
                moLCDetailsStruct.msDOBText = value;
            }
        }
        

        public DateTime DOB
        {
            get
            {
                return moLCDetailsStruct.mdtDOB;
            }
            set
            {
                moLCDetailsStruct.mdtDOB = value;
            }
        }

        public bool IsFailed
        {
            get
            {
                return moLCDetailsStruct.IsFailed;
            }
            set
            {
                moLCDetailsStruct.IsFailed = value;
            }
        }

        public int IsAllDueSettled
        {
            get
            {
                return moLCDetailsStruct.IsAllDueSettled;
            }
            set
            {
                moLCDetailsStruct.IsAllDueSettled = value;
            }
        }

        public string Religion
        {
            get
            {
                return moLCDetailsStruct.msReligion;
            }
            set
            {
                moLCDetailsStruct.msReligion = value;
            }
        }

        public string MotherTongue
        {
            get { return moLCDetailsStruct.MotherTongue; }
            set { moLCDetailsStruct.MotherTongue=value; }
        }

        public string Conduct
        {
            get { return moLCDetailsStruct.Conduct; }
            set { moLCDetailsStruct.Conduct = value; }
        }

        public string Promotion
        {
            get { return moLCDetailsStruct.Promotion; }
            set { moLCDetailsStruct.Promotion = value; }
        }

        public bool IsPromotedToHigherClass
        {
            get { return moLCDetailsStruct.IsPromotedToHigherClass; }
            set { moLCDetailsStruct.IsPromotedToHigherClass = value; }
        }

        public DateTime ApplicationDate
        {
            get { return moLCDetailsStruct.mdtApplicationDate; }
            set { moLCDetailsStruct.mdtApplicationDate = value; }
        }

        public string StudentNo
        {
            get { return moLCDetailsStruct.msStudentNo; }
            set { moLCDetailsStruct.msStudentNo = value; }
        }

        public int PramotedToNextClassId
        {
            get { return moLCDetailsStruct.miPramotedToNextClassId; }
            set { moLCDetailsStruct.miPramotedToNextClassId = value; }
        }

        public int ExamStatusId
        {
            get { return moLCDetailsStruct.miExamStatusId; }
            set { moLCDetailsStruct.miExamStatusId = value; }
        }

        public string BookNo
        {
            get { return moLCDetailsStruct.msBookNo; }
            set { moLCDetailsStruct.msBookNo = value; }
        }

        public string BookSLNo
        {
            get { return moLCDetailsStruct.msSLNo; }
            set { moLCDetailsStruct.msSLNo = value; }
        }

        public string AnnualExaminationResult
        {
            get { return moLCDetailsStruct.msAnnualExaminaion; }
            set { moLCDetailsStruct.msAnnualExaminaion = value; }
        }

        public string WhetherFailed
        {
            get { return moLCDetailsStruct.msWhetherFailed; }
            set { moLCDetailsStruct.msWhetherFailed = value; }
        }

        public string ExtraCurricularActivities
        {
            get { return moLCDetailsStruct.msExtraCurricularActivities; }
            set { moLCDetailsStruct.msExtraCurricularActivities = value; }
        }

        public string CategoryName
        {
            get { return moLCDetailsStruct.msCategoryName; }
            set { moLCDetailsStruct.msCategoryName = value; }
        }
        public string AcademicPerformance
        {
            get { return moLCDetailsStruct.msAcademicPerformance; }
            set { moLCDetailsStruct.msAcademicPerformance = value; }
        }
        public string StudentUIDNo
        {
            get { return moLCDetailsStruct.msStudentUIDNo; }
            set { moLCDetailsStruct.msStudentUIDNo = value; }
        }
        public string DocumentInSupportOfDOB
        {
            get { return moLCDetailsStruct.msDocumentInSupportOfDOB; }
            set { moLCDetailsStruct.msDocumentInSupportOfDOB = value; }
        }
        public string SubjectStudied
        {
            get { return moLCDetailsStruct.msSubjectStudied; }
            set { moLCDetailsStruct.msSubjectStudied = value; }
        }
        public string SchoolDues
        {
            get { return moLCDetailsStruct.msSchoolDues; }
            set { moLCDetailsStruct.msSchoolDues = value; }
        }

        public int InsertLCDetails(bool abIsSaveAction)
        {
            moLCDetailsDC.LCDetailsStructDetails = moLCDetailsStruct;
            return moLCDetailsDC.InsertLCDetails(abIsSaveAction);
        }

        public void UpdateLCDetails(bool abIsSaveAction)
        {
            moLCDetailsDC.LCDetailsStructDetails = moLCDetailsStruct;
            moLCDetailsDC.UpdateLCDetails(abIsSaveAction);
        }

        public void DeleteLCDetails()
        {
            moLCDetailsDC.LCDetailsStructDetails = moLCDetailsStruct;
            moLCDetailsDC.DeleteLCDetails();
        }

        public static System.Data.DataTable GetStudentLCDetails(int aiSchoolId, string asRegNo, int aiStudentId = 0)
        {
            return LCDetailsDC.GetStudentLCDetails(aiSchoolId, asRegNo,aiStudentId);
        }

        public void AddLCPrintCount(int aiSchoolId, string asRegNo,int aiUserId,string sPrintDate)
        {
            moLCDetailsDC.AddLCPrintCount(aiSchoolId, asRegNo, aiUserId, sPrintDate);
        }
		
		public void AddLcGeneratedDetails(int aiSchoolId, string asRegNo, int aiGeneratedById)
        {
            moLCDetailsDC.AddLcGeneratedDetails(aiSchoolId, asRegNo, aiGeneratedById);
        }
    }

}
