//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- LecturesPerStandardBL
// Purpose          :- This class is used to manage LecturesPerStandardWeekdays details.
// Date Of creation :- 3/3/2008
// Author Name      :- 


using System.Data;
using System.Collections;
using DataCommunicator;
using Utility;


namespace BusinessLogic
{
    public class LecturesPerStandardBL
    {

        private LecturesPerStandardDC.LecturesPerStandardWeekdaysStruct moLecturesPerStandardWeekdaysStruct;

        private LecturesPerStandardDC moLecturesPerStandardDC;

        public LecturesPerStandardBL()
        {
            moLecturesPerStandardDC = new LecturesPerStandardDC();
        }

        public int School_Id
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.miSchoolId;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.miSchoolId = value;
            }
        }

        public int Academic_Year_ID
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.miAcademicYearID;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.miAcademicYearID = value;
            }
        }
        public int Id
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.miId;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.miId = value;
            }
        }

        public string MaxLecturesPerStandardWeekDay
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.msMaxLecturesPerStandardWeekDay;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.msMaxLecturesPerStandardWeekDay = value;
            }
        }

        public string MaxLecturesPerWeek
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.msMaxLecturesPerWeek;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.msMaxLecturesPerWeek = value;
            }
        }

        public int Inserted_By_Id
        {
            get
            {
                return moLecturesPerStandardWeekdaysStruct.miInsertedById;
            }
            set
            {
                moLecturesPerStandardWeekdaysStruct.miInsertedById = value;
            }
        }
        /// <summary>
        /// This method returns the message informing about the dependencies.
        /// </summary>
        /// <returns></returns>
        public string CheckDependencies(Hashtable aoHashWeekLyLimitIds, Hashtable aoHashWeekdayLimitIds)
        {
            string sReturnMsg = "";
            ReferenceBL oRefBL = new ReferenceBL();
            sReturnMsg = oRefBL.CheckDependencies(Constants.ReferenceId.MaxWeeklyLectures, aoHashWeekLyLimitIds, moLecturesPerStandardWeekdaysStruct.miAcademicYearID);
            sReturnMsg = sReturnMsg + oRefBL.CheckDependencies(Constants.ReferenceId.MaxWeekDayLectures, aoHashWeekdayLimitIds, moLecturesPerStandardWeekdaysStruct.miAcademicYearID);
            return sReturnMsg;
            
        }
        public void ManageStandardLectures(Hashtable aoHashWeekLyLimitIds, Hashtable aoHashWeekdayLimitIds)
        {
            string sMessage = "";
            moLecturesPerStandardDC.LecturesPerStandardWeekdaysStructDetails = moLecturesPerStandardWeekdaysStruct;
            sMessage = CheckDependencies(aoHashWeekLyLimitIds, aoHashWeekdayLimitIds);
            if (sMessage.Equals(""))
            {
                moLecturesPerStandardDC.ManageStandardLectures();
            }
            else
            {
                throw new Exceptions.ReferenceExceptions(sMessage);
            }
        }

        public static DataSet GetAllStandardLectures(int aiSchoolId, int aiAcademicYearId)
        {
            return LecturesPerStandardDC.GetAllStandardLectures(aiSchoolId, aiAcademicYearId);
        }
      
    }

  
}
