//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- MessageDetailsBL
// Purpose          :- This class is used to manage MessageDetails details.
// Date Of creation :- 1/9/2008
// Author Name      :- Mahesh Chavan


using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using DataCommunicator;
using Utility;
using System.Globalization;
using SchoolEntities;

namespace BusinessLogic
{


    public class MessageDetailsBL
    {

        private MessageDetailsDC.MessageDetailsStruct moMessageDetailsStruct;

        private MessageDetailsDC moMessageDetailsDC;

        #region Constructor

        public MessageDetailsBL()
        {
            moMessageDetailsDC = new MessageDetailsDC();
        }

        public MessageDetailsBL(int miMessageDetailsId)
        {
            moMessageDetailsDC = new MessageDetailsDC(miMessageDetailsId);
            moMessageDetailsStruct = moMessageDetailsDC.MessageDetailsStructDetails;
        }

        #endregion Constructor

        #region Properties

        public  int Message_Details_Id
        {
            get
            {
                return moMessageDetailsStruct.miMessageDetailsId;
            }
            set
            {
                moMessageDetailsStruct.miMessageDetailsId = value;
            }
        }

        public  string Subject
        {
            get
            {
                return moMessageDetailsStruct.msSubject;
            }
            set
            {
                moMessageDetailsStruct.msSubject = value;
            }
        }

        public  string Message_Body
        {
            get
            {
                return moMessageDetailsStruct.msMessaageBody;
            }
            set
            {
                moMessageDetailsStruct.msMessaageBody = value;
            }
        }

        public  string Display_Text
        {
            get
            {
                return moMessageDetailsStruct.msDisplayText;
            }
            set
            {
                moMessageDetailsStruct.msDisplayText = value;
            }
        }

        public  string Is_DeletedFromUser
        {
            get
            {
                return moMessageDetailsStruct.msIsDeletedFromUser;
            }
            set
            {
                moMessageDetailsStruct.msIsDeletedFromUser = value;
            }
        }

        public  int Sender_User_Role_Id
        {
            get
            {
                return moMessageDetailsStruct.miSenderUserRoleId;
            }
            set
            {
                moMessageDetailsStruct.miSenderUserRoleId = value;
            }
        }

        public  int Sender_User_Id
        {
            get
            {
                return moMessageDetailsStruct.miSenderUserId;
            }
            set
            {
                moMessageDetailsStruct.miSenderUserId = value;
            }
        }

        public  string Is_Deleted
        {
            get
            {
                return moMessageDetailsStruct.msIsDeleted;
            }
            set
            {
                moMessageDetailsStruct.msIsDeleted = value;
            }
        }

        public  System.DateTime Insert_Date
        {
            get
            {
                return moMessageDetailsStruct.mdtInsertDate;
            }
            set
            {
                moMessageDetailsStruct.mdtInsertDate = value;
            }
        }

        public  int Inserted_By_Id
        {
            get
            {
                return moMessageDetailsStruct.miInsertedById;
            }
            set
            {
                moMessageDetailsStruct.miInsertedById = value;
            }
        }

        public int AcademicYrId
        {
            get
            {
                return moMessageDetailsStruct.miAcademicYrId;
            }
            set
            {
                moMessageDetailsStruct.miAcademicYrId = value;
            }
        }
        public  System.DateTime Updated_Date
        {
            get
            {
                return moMessageDetailsStruct.mdtUpdatedDate;
            }
            set
            {
                moMessageDetailsStruct.mdtUpdatedDate = value;
            }
        }

        public  int Updated_By_Id
        {
            get
            {
                return moMessageDetailsStruct.miUpdatedById;
            }
            set
            {
                moMessageDetailsStruct.miUpdatedById = value;
            }
        }

        public string UserName
        {
            get
            {
                return moMessageDetailsStruct.msUserName;
            }
            set
            {
                moMessageDetailsStruct.msUserName = value;
            }
        }

        public ArrayList ToUsersList
        {
            get
            {
                return moMessageDetailsStruct.moArrayListToUsers; 
            }
            set
            {
                moMessageDetailsStruct.moArrayListToUsers = value;
            }
        }
        public List<FileAttachment> Attachments
        {
            get
            {
                return moMessageDetailsStruct.msAttachments;
            }
            set
            {
                moMessageDetailsStruct.msAttachments = value;
            }
        
        }

        public string Attatchment
        {
            get
            {
                return moMessageDetailsStruct.msAttatchment;
            }
            set
            {
                moMessageDetailsStruct.msAttatchment = value;
            }
        }

        public string Attatchment1
        {
            get
            {
                return moMessageDetailsStruct.msAttatchment1;
            }
            set
            {
                moMessageDetailsStruct.msAttatchment1 = value;
            }
        }

        public string Attatchment2
        {
            get
            {
                return moMessageDetailsStruct.msAttatchment2;
            }
            set
            {
                moMessageDetailsStruct.msAttatchment2 = value;
            }
        }
        public bool RequestReadReceipt
        {
            get
            {
                return moMessageDetailsStruct.mbRequestReadReceipt;
            }
            set
            {
                moMessageDetailsStruct.mbRequestReadReceipt = value;
            }
        }

        public bool IsReadReceiptRequested
        {
            get
            {
                return moMessageDetailsStruct.mbIsReadReceiptRequested;
            }
            set
            {
                moMessageDetailsStruct.mbIsReadReceiptRequested = value;
            }
        }

        public string Cc_Display_Text
        {
            get
            {
                return moMessageDetailsStruct.msCcDisplayText;
            }
            set
            {
                moMessageDetailsStruct.msCcDisplayText = value;
            }
        }
        #endregion Properties

        public int InsertMessageDetails(List<MessageReceiverDetailsBL> aoMessageReceiverDetailsBLList, List<string> alstFiles)
        {
            ArrayList oArrayListInsertStatements = new ArrayList(); 
            moMessageDetailsDC.MessageDetailsStructDetails = moMessageDetailsStruct;
            oArrayListInsertStatements.Add(moMessageDetailsDC.GetInsertMessageDetails());
            oArrayListInsertStatements.Add("SELECT SCOPE_IDENTITY() as "+ Constants.S_LAST_INSERTED_P_KEY);
  
            foreach (MessageReceiverDetailsBL oMessageReceiverDetailsBL in aoMessageReceiverDetailsBLList)
                oArrayListInsertStatements.Add(oMessageReceiverDetailsBL.GetInsertMessageReceiverDetails());

            foreach (string path in alstFiles)
            {
                MessageReceiverDetailsBL oMessageReceiverDetailsBL =new MessageReceiverDetailsBL();
                oArrayListInsertStatements.Add(moMessageDetailsDC.GetInsertAttachmentDetails(path));
            }

            return moMessageDetailsDC.InsertMessageDetails(oArrayListInsertStatements);
        }
        
        public void UpdateMessageDetails()
        {
            moMessageDetailsDC.MessageDetailsStructDetails = moMessageDetailsStruct;
            moMessageDetailsDC.UpdateMessageDetails();
        }

        #region Public Method

        /// <summary>
        /// This method is used to get the receiver name list.
        /// </summary>
        /// <returns></returns>

        public DataTable GetListOfReceiverName(int aiMessageDetailsId)
        {
            return moMessageDetailsDC.GetListOfReceiverName(aiMessageDetailsId);
        }

        public DataTable GetListOfCcReceiverName(int aiMessageDetailsId)
        {
            return moMessageDetailsDC.GetListOfCcReceiverName(aiMessageDetailsId);
        }

        public static string GetUserName(int aiUserId, int aiUserRoleId, int aiAcadYrId)
        {
            return MessageDetailsDC.GetUserName(aiUserId, aiUserRoleId, aiAcadYrId);
        }
        public static int CheckSuperAdmin(int aiUserId, int aiUserRoleId, int aiAcadYrId)
        {
            return MessageDetailsDC.CheckSuperAdmin(aiUserId, aiUserRoleId, aiAcadYrId);
        }
        #endregion 
    
        public DataTable GetAcademicYearDetails(int iAcadYrId)
        {
            return moMessageDetailsDC.GetAcademicYearDetails(iAcadYrId);
        }

        /// <summary>
        /// This method is used to get draft message Details.
        /// </summary>
        public List<MessageDraftDetails> GetDraftDetails(int aiSchoolId, int aiAcademicYearid, int aiUserId)
        {
            return moMessageDetailsDC.GetDraftDetails(aiSchoolId, aiAcademicYearid, aiUserId);
        }

        /// <summary>
        /// This method is used to save draft message Details.
        /// </summary>
        public int SaveMessageAsDraft(int aiDraftId, string asReceipantList, string asDisplayText, string asSubject, string asMessageBody, int aiUserId, int aiSchoolId, int aiAcademicYearId, string asCcReceipantList, string asCcDisplayText)
        {
            return moMessageDetailsDC.SaveMessageAsDraft(aiDraftId, asReceipantList, asDisplayText, asSubject, asMessageBody, aiUserId, aiSchoolId, aiAcademicYearId, asCcReceipantList, asCcDisplayText);
        }

        /// <summary>
        /// This method is used to get draft message Details for view.
        /// </summary>
        public MessageDraftDetails GetMessageDetailsForDraft(int aiDraftId, int aiUserId, int aiSchoolId,int aiAcademicYearId)
        {
            return this.moMessageDetailsDC.GetMessageDetailsForDraft(aiDraftId, aiUserId, aiSchoolId, aiAcademicYearId);
        }

        /// <summary>
        /// This method is used to get draft message Details for edit.
        /// </summary>
        public MessageDraftDetails GetMessageDetailsForDraftEdit(int aiDraftId, int aiUserId, int aiSchoolId, int aiAcademicYearId, out List<StandardDivisionDetails> alstStandardDivisionDetails, out List<MessageDraftUserDetails> alstMessageDraftDetails, out List<MessageDraftUserDetails> alstMessageDraftCCDetails)
        {
            return this.moMessageDetailsDC.GetMessageDetailsForDraftEdit(aiDraftId, aiUserId, aiSchoolId, aiAcademicYearId, out alstStandardDivisionDetails, out alstMessageDraftDetails, out alstMessageDraftCCDetails);
        }

        /// <summary>
        /// This method is used to delete draft message Details.
        /// </summary>
        public void DeleteMessageFromDraft(int aiDraftId, int aiUserId, int aiSchoolId, int aiAcademicYearId)
        {
            moMessageDetailsDC.DeleteMessageFromDraft(aiDraftId, aiUserId, aiSchoolId, aiAcademicYearId);
        }

        public UserData GetUserData(string asUserName, string asSchoolId, string asAcademicYearId)
        {
           return moMessageDetailsDC.GetUserData(asUserName,asSchoolId,asAcademicYearId);
        }

        public void DeleteMessagePermanently(int miSchoolId, int miAcademicYearId, int aiUpdatedById, string sIds, bool abIsSuperAdmin)
        {
            moMessageDetailsDC.DeleteMessagePermanently(miSchoolId, miAcademicYearId, aiUpdatedById, sIds, abIsSuperAdmin);
        }

        public bool IsPTAMember(int aiSchoolId, int aiAcademicYearId, int aiUserId)
        {
          return moMessageDetailsDC.IsPTAMember(aiSchoolId, aiAcademicYearId, aiUserId);
        }

        public string GetDesignation(int aiUserId, int aiSchoolId)
        {
             return moMessageDetailsDC.GetDesignation(aiUserId, aiSchoolId);
        }
    }

    public class MessageDetailsCollectionBL
    {
        private MessageDetailsCollectionDC moMessageDetailsCollectionDC = null;

        private int miMessagesCount;

        public DataTable GetMessages(int aiAcadYrId, int aiUserId, int aiUserRoleId, string asMode, string asFilter,string asOperator, string dtDate, String sortExpression, int maximumRows, int startRowIndex)
        {
            const string S_FLAG_SHOW_INBOX = "ShowInbox";
            const string S_FLAG_SHOW_SENT_ITEMS = "ShowSentItems";
            const string S_FLAG_SHOW_TRASH = "ShowTrash";
            DateTime dt = new DateTime();      

            if (asFilter == null)
                asFilter = string.Empty;
            if (dtDate == null)
                dt = DateTime.MinValue;
            else               
                dt = DateTime.Parse(dtDate.ToString());

            DataTable oDt = new DataTable();
            miMessagesCount = 0;
            switch (asMode)
            {
                case S_FLAG_SHOW_INBOX:
                    oDt = moMessageDetailsCollectionDC.GetMessageInboxForUser(aiAcadYrId, aiUserId, aiUserRoleId, sortExpression, maximumRows, startRowIndex, asFilter, asOperator, dt);
                    break;
                case S_FLAG_SHOW_TRASH:
                     oDt = moMessageDetailsCollectionDC.GetArchivedMessagesForUser(aiAcadYrId, aiUserId, aiUserRoleId, sortExpression, maximumRows, startRowIndex, asFilter, asOperator, dt);
                     break;
                case S_FLAG_SHOW_SENT_ITEMS:
                    oDt = moMessageDetailsCollectionDC.GetSentItemsForUser(aiAcadYrId, aiUserId, aiUserRoleId, sortExpression, maximumRows, startRowIndex, asFilter, asOperator, dt);
                    break;
                default:
                    oDt = moMessageDetailsCollectionDC.GetMessageInboxForUser(aiAcadYrId, aiUserId, aiUserRoleId, sortExpression, maximumRows, startRowIndex, asFilter,asOperator,dt);
                    break;
            }

            if (oDt != null && oDt.Rows.Count > 0)
                miMessagesCount = Convert.ToInt32(oDt.Rows[0]["TotalRows"]);

            return oDt;
        }
        public int GetMsgCount(int aiAcadYrId, int aiUserId, int aiUserRoleId, string asMode, string asFilter, string asOperator,string dtDate)
        {
            return miMessagesCount;
        }

        public MessageDetailsCollectionBL()
        {
            moMessageDetailsCollectionDC = new MessageDetailsCollectionDC();  
        }

        /////// <summary>
        /////// This method is used to get Inbox messages of the logged in user.
        /////// </summary>
        /////// <param name="aiSchoolId"></param>
        /////// <param name="aiUserId"></param>
        /////// <param name="aiUserRoleId"></param>
        /////// <returns></returns>
        ////public DataTable GetMessageInboxForUser(int aiAcadYrId, int aiUserId, int aiUserRoleId)
        ////{
        ////    return moMessageDetailsCollectionDC.GetMessageInboxForUser(aiAcadYrId, aiUserId, aiUserRoleId);
        ////}

        ////public DataTable GetArchivedMessagesForUser(int aiAcadYrId, int aiUserId, int aiUserRoleId)
        ////{
        ////    return moMessageDetailsCollectionDC.GetArchivedMessagesForUser(aiAcadYrId, aiUserId, aiUserRoleId);
        ////}

        ///// <summary>
        ///// This method is used to get the Sent Items list for logged in user.
        ///// </summary>
        ///// <param name="aiSchoolId"></param>
        ///// <param name="aiUserId"></param>
        ///// <param name="aiUserRoleId"></param>
        ///// <returns></returns>
        //public DataTable GetSentItemsForUser(int aiAcdYrId, int aiUserId, int aiUserRoleId)
        //{
        //    return moMessageDetailsCollectionDC.GetSentItemsForUser(aiAcdYrId, aiUserId, aiUserRoleId);
        //}

        
        /// <summary>
        /// This method is usedto delete messages from sent items list.
        /// </summary>
        /// <param name="aoArrMessageDetailsId"></param>

        public void DeleteSentItems(ArrayList aoArrMessageDetailsId)
        {
            moMessageDetailsCollectionDC.DeleteSentItems(aoArrMessageDetailsId);
        }

        public static DataSet GetUserIDDetailsByMessageID(int aiMsgID)
        {
            //This function is used to get message receiver user ID details by message Id.

            return MessageDetailsCollectionDC.GetUserIDDetailsByMessageID(aiMsgID);
        }
        
    }
}
