//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- ParentTeacherAssociationDetailsBL
// Purpose          :- This class is used to manage ParentTeacherAssociationDetails details.
// Date Of creation :- 12/30/2010
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;
using SchoolEntities;
using AssociationEntities;

namespace BusinessLogic
{
    public class ParentTeacherAssociationDetailsBL
    {
        #region "Data Members"

        private ParentTeacherAssociationDetailsDC oParentTeacherAssociationDetailsDC = null;
        private ParentTeacherAssociationDetails moParentTeacherAssociationDetails = null;

        #endregion "Data Members"

        #region "Constructors"

        public ParentTeacherAssociationDetailsBL()
        {
            moParentTeacherAssociationDetails = new ParentTeacherAssociationDetails();
            oParentTeacherAssociationDetailsDC = new ParentTeacherAssociationDetailsDC();
        }

        #endregion "Constructors"

        #region "Properties"

        public ParentTeacherAssociationDetails ParentTeacherAssociationDetails
        {
            get { return oParentTeacherAssociationDetailsDC.ParentTeacherAssociationDetails; }
            set { oParentTeacherAssociationDetailsDC.ParentTeacherAssociationDetails = value; }
        }

        public List<ParentTeacherAssociationDetails> ParentOrTeacherAssociationDetailsList
        {
            get { return oParentTeacherAssociationDetailsDC.moParentTeacherAssoDetails; }
            set { oParentTeacherAssociationDetailsDC.moParentTeacherAssoDetails = value; }
        }
        public List<ParentTeacherAssociationDetails> ParentAndTeacherAssociationDetailsList
        {
            get { return oParentTeacherAssociationDetailsDC.moParentAndTeacherAssoDetails; }
            set { oParentTeacherAssociationDetailsDC.moParentAndTeacherAssoDetails = value; }
        }
        public List<ParentTeacherAssociationDetails> TeacherAssociationDetailsList
        {
            get { return oParentTeacherAssociationDetailsDC.moTeacherAssoDetails; }
            set { oParentTeacherAssociationDetailsDC.moTeacherAssoDetails = value; }
        }
        public List<ParentTeacherAssociationDetails> ParentAssociationDetailsList
        {
            get { return oParentTeacherAssociationDetailsDC.moParentAssoDetails; }
            set { oParentTeacherAssociationDetailsDC.moParentAssoDetails = value; }
        }

        public List<ParentTeacherAssociationDetails> DesignationDetails
        {
            get { return oParentTeacherAssociationDetailsDC.moDesignationDetails; }
            set { oParentTeacherAssociationDetailsDC.moDesignationDetails = value; }
        }
		
        public List<ParentTeacherAssociationDetails> StudentStandardDetails
        {
            get { return oParentTeacherAssociationDetailsDC.moStudentStandardDetails; }
            set { oParentTeacherAssociationDetailsDC.moStudentStandardDetails = value; }
        }
        public List<ParentTeacherAssociationDetails> StandardDetails
        {
            get { return oParentTeacherAssociationDetailsDC.moStandardDetails; }
            set { oParentTeacherAssociationDetailsDC.moStandardDetails = value; }
        }

        #endregion "Properties"

        #region "Public Methods"

        /// <summary>
        /// This method is used to Get Parent or Teacher details as per selectetion of radiobutton.
        /// </summary>
        /// <param name="asFilter"></param>
        /// <param name="aiOptCheck"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        public void GetParentOrTeacherDetails(string asFilter, int aiOptCheck, int aiSchoolId, int aiAcademicYearId)
        {
            oParentTeacherAssociationDetailsDC.GetParentOrTeacherDetails(asFilter, aiOptCheck, aiSchoolId, aiAcademicYearId);
        }

        /// <summary>
        /// This method is used to Fill Teacher and Parent Combobox.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiTeacherUserRoleId"></param>
        /// <param name="aiParentUserRoleId"></param>
        /// <returns></returns>
        public void FillDesignationCombobox()
        {
            oParentTeacherAssociationDetailsDC.FillDesignationCombobox();
        }

        /// <summary>
        /// This method is used to Save Teacher Details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        public void SaveTeacherDetails(string asMode)
        {
            oParentTeacherAssociationDetailsDC.SaveTeacherDetails(asMode);
        }

        /// <summary>
        /// This method is used to Save Parent Details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        public void SaveParentDetails(string asTermXML, string asMode)
        {
            oParentTeacherAssociationDetailsDC.SaveParentDetails(asTermXML,asMode);
        }

        /// <summary>
        /// This method is used to Get all Teacher and Parent details.
        /// </summary>
        /// <returns></returns>
        public void GetAll()
        {
            oParentTeacherAssociationDetailsDC.GetAll();
        }

        /// <summary>
        /// This method is used to Get Teacher details.
        /// </summary>
        /// <returns></returns>
        public void GetTeacherDetails()
        {
            oParentTeacherAssociationDetailsDC.GetTeacherDetails();
        }

        /// <summary>
        ///  This method is used to Get Parent details.
        /// </summary>
        /// <returns></returns>
        public void GetParentDetails()
        {
            oParentTeacherAssociationDetailsDC.GetParentDetails();
        }

        /// <summary>
        /// This method is used to Delete Teacher or Parent Details. 
        /// </summary>
        /// <param name="aiTeacherAssociationId"></param>
        public void DeleteTeacherDetails()
        {
            oParentTeacherAssociationDetailsDC.DeleteTeacherDetails();
        }

        /// <summary>
        /// This method is used to Delete Teacher or Parent Details. 
        /// </summary>
        /// <param name="aiTeacherAssociationId"></param>
        public void DeleteParentDetails()
        {
            oParentTeacherAssociationDetailsDC.DeleteParentDetails();
        }

        /// <summary>
        /// This method is used to get selected Parent Teacher mobile numbers.
        /// </summary>
        /// <param name="aiSchoolID"></param>
        /// <param name="aiAcadYrId"></param>
        /// <returns></returns>
        public DataTable FetchParentTeacherAssociationDetails(int aiSchoolID, int aiAcadYrId, int aiSchoolCommitteeId, int aiLoginUserId =0)
        {
            return oParentTeacherAssociationDetailsDC.FetchParentTeacherAssociationDetails(aiSchoolID, aiAcadYrId, aiSchoolCommitteeId, aiLoginUserId);
        }

        /// <summary>
        /// This method is used to get selected Parent Teacher mobile numbers.
        /// </summary>
        /// <param name="asUserIDs"></param>
        /// <returns></returns>
        public DataTable GetAllMobileNosForParentTeachers(String asUserIDs)
        {
            return oParentTeacherAssociationDetailsDC.GetAllMobileNosForParentTeachers(asUserIDs);
        }

        /// <summary>
        /// This method is used to get all Parent Teacher mobile numbers.
        /// </summary>
        /// <returns></returns>
        public DataTable GetAllMobileNosForParentTeachers()
        {
            return oParentTeacherAssociationDetailsDC.GetAllMobileNosForParentTeachers();
        }


        #endregion "Public Methods"

        public List<SectionDetails> GetSections(int aiSchoolId)
        {
            return oParentTeacherAssociationDetailsDC.GetSections(aiSchoolId);
        }
    }
}
