//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- SchoolWiseAnnualResultPublishDC
// Purpose          :- This class is used to manage SchoolWiseAnnualResultPublish details.
// Date Of creation :- 3/17/2008
// Author Name      :- 


using System;
using System.Data;
using DataCommunicator;




namespace BusinessLogic
{


    public class SchoolWiseAnnualResultPublishBL
    {

        private SchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStruct moSchoolWiseAnnualResultPublishStruct;

        private SchoolWiseAnnualResultPublishDC moSchoolWiseAnnualResultPublishDC;

        public SchoolWiseAnnualResultPublishBL()
        {
            moSchoolWiseAnnualResultPublishDC = new SchoolWiseAnnualResultPublishDC();
        }

        public SchoolWiseAnnualResultPublishBL(int miAnnualResultpublishId)
        {
            moSchoolWiseAnnualResultPublishDC = new SchoolWiseAnnualResultPublishDC(miAnnualResultpublishId);
            moSchoolWiseAnnualResultPublishStruct = moSchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStructDetails;
        }

        public SchoolWiseAnnualResultPublishBL(int aiSchoolID, int aiAcadmicYearID, int aiStdDivId)
        {
            moSchoolWiseAnnualResultPublishDC = new SchoolWiseAnnualResultPublishDC(aiSchoolID, aiAcadmicYearID, aiStdDivId);
            moSchoolWiseAnnualResultPublishStruct = moSchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStructDetails;
            
        }

        /// <summary>
        /// This method is use to check wheteer final result of given standard is publistd or not.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAccYearId"></param>
        /// <param name="aiStandardId"></param>
        /// <param name="aiStandardDivisionId"></param>
        /// <returns></returns>
        public static bool IsResultPublished(int aiSchoolId, int aiAccYearId, int aistandardid, int aiStandardDivisionId)
        {
           return SchoolWiseAnnualResultPublishDC.IsResultPublished( aiSchoolId,  aiAccYearId,  aistandardid, aiStandardDivisionId);
        }

        public virtual int AnnualResult_publish_Id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miAnnualResultpublishId;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miAnnualResultpublishId = value;
            }
        }

        public virtual int School_Id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miSchoolId;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miSchoolId = value;
            }
        }

        public virtual int Academic_Year_Id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miAcademicYearId;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miAcademicYearId = value;
            }
        }

        public virtual int Standard_Division_Id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miStandardDivisionId;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miStandardDivisionId = value;
            }
        }

        public virtual string Is_Published
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.msIsPublished;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.msIsPublished = value;
            }
        }

        public virtual string Is_Deleted
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.msIsDeleted;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.msIsDeleted = value;
            }
        }

        public virtual System.DateTime Insert_Date
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.mdtInsertDate;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.mdtInsertDate = value;
            }
        }

        public virtual int Inserted_By_id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miInsertedByid;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miInsertedByid = value;
            }
        }

        public virtual System.DateTime Update_Date
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.mdtUpdateDate;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.mdtUpdateDate = value;
            }
        }

        public virtual int Updated_By_Id
        {
            get
            {
                return moSchoolWiseAnnualResultPublishStruct.miUpdatedById;
            }
            set
            {
                moSchoolWiseAnnualResultPublishStruct.miUpdatedById = value;
            }
        }
        /// <summary>
        // This function is used to insert the SchoolWiseAnnualResultPublish Details
        /// </summary>
        /// <returns></returns>
        public virtual int InsertSchoolWiseAnnualResultPublish()
        {
            moSchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStructDetails = moSchoolWiseAnnualResultPublishStruct;
            return moSchoolWiseAnnualResultPublishDC.InsertSchoolWiseAnnualResultPublish();
        }

        /// <summary>
        /// This function is used to delete the SchoolWiseAnnualResultPublish Details
        /// </summary>
        /// <returns></returns>
        public virtual int DeleteSchoolWiseAnnualResultPublish()
        {
            moSchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStructDetails = moSchoolWiseAnnualResultPublishStruct;
            return moSchoolWiseAnnualResultPublishDC.DeleteSchoolWiseAnnualResultPublish();
        }

        public void UnPublishFinalResult(string sUnPublishReason)
        {
            moSchoolWiseAnnualResultPublishDC.SchoolWiseAnnualResultPublishStructDetails = moSchoolWiseAnnualResultPublishStruct;
            moSchoolWiseAnnualResultPublishDC.UnPublishFinalResult(sUnPublishReason);
        }

        public bool IsGraceAppliedForAnyStudentOfStdDivId(int aiStdDivId)
        {
            DataTable oDataTable  = moSchoolWiseAnnualResultPublishDC.IsGraceAppliedForAnyStudentOfStdDivId(aiStdDivId);
            if (oDataTable != null && Convert.ToInt32(oDataTable.Rows[0][0])>0)
            {
                return true;
            }
            else return false;
        }


        /// <summary>
        /// This method is used to check the result of selected standard or class is published or not.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAccYearId"></param>
        /// <param name="aiStandardId"></param>
        /// <param name="aiDivisionId"></param>
        /// <returns></returns>
        public static bool IsExamPublished(int aiSchoolId, int aiAccYearId, int aiStandardId, int aiDivisionId)
        {
            return SchoolWiseAnnualResultPublishDC.IsExamPublished(aiSchoolId, aiAccYearId, aiStandardId, aiDivisionId);
        }

        public bool IsGraceAppliedForTheStudent(int iStudentId)
        {
            DataTable oDataTable = moSchoolWiseAnnualResultPublishDC.IsGraceAppliedForTheStudent(iStudentId);
            if (oDataTable != null && Convert.ToInt32(oDataTable.Rows[0][0]) > 0)
            {
                return true;
            }
            else return false;
        }
    }

    public class SchoolWiseAnnualResultPublishCollectionBL
    {
        /// <summary>
        /// This method is used to publis result of all school
        /// </summary>
        /// <param name="iSchoolID"></param>
        /// <param name="iAcademicYrID"></param>
        public static void PublishAllSchoolResults(int iSchoolID, int iAcademicYrID)
        {
            SchoolWiseAnnualResultPublishCollectionDC.PublishAllSchoolResults(iSchoolID, iAcademicYrID);
        }
    }
}
