//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- SchoolwiseBankMasterBL
// Purpose          :- This class is used to manage SchoolwiseBankMaster details.
// Date Of creation :- 10/6/2008
// Author Name      :- 


using System;
using System.Data;
using System.Collections.Generic;
using DataCommunicator;
using Utility;
using FeeEntities;


namespace BusinessLogic
{
    public class SchoolwiseBankMasterBL
    {

        private SchoolwiseBankMasterDC.SchoolwiseBankMasterStruct moSchoolwiseBankMasterStruct;

        private SchoolwiseBankMasterDC moSchoolwiseBankMasterDC;

        public SchoolwiseBankMasterBL()
        {
            moSchoolwiseBankMasterDC = new SchoolwiseBankMasterDC();
        }

        public SchoolwiseBankMasterBL(int miSchoolwiseBankId)
        {
            moSchoolwiseBankMasterDC = new SchoolwiseBankMasterDC(miSchoolwiseBankId);
            moSchoolwiseBankMasterStruct = moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails;
        }

        public List<DisbaleBankDetails> lstDisbaleBankDetailList
        {
            get
            {
                return moSchoolwiseBankMasterDC.mlstDisbaleBankDetails;
            }
            set
            {
                moSchoolwiseBankMasterDC.mlstDisbaleBankDetails = value;
            }
        }
        public int Schoolwise_Bank_Id
        {
            get
            {
                return moSchoolwiseBankMasterStruct.miSchoolwiseBankId;
            }
            set
            {
                moSchoolwiseBankMasterStruct.miSchoolwiseBankId = value;
            }
        }

        public int School_Id
        {
            get
            {
                return moSchoolwiseBankMasterStruct.miSchoolId;
            }
            set
            {
                moSchoolwiseBankMasterStruct.miSchoolId = value;
            }
        }

        public string Bank_Name
        {
            get
            {
                return moSchoolwiseBankMasterStruct.msBankName;
            }
            set
            {
                moSchoolwiseBankMasterStruct.msBankName = value;
            }
        }

        public int Inserted_By_Id
        {
            get
            {
                return moSchoolwiseBankMasterStruct.miInsertedById;
            }
            set
            {
                moSchoolwiseBankMasterStruct.miInsertedById = value;
            }
        }

        public int Updated_By_Id
        {
            get
            {
                return moSchoolwiseBankMasterStruct.miUpdatedById;
            }
            set
            {
                moSchoolwiseBankMasterStruct.miUpdatedById = value;
            }
        }

        private void IsHolidayNameDuplicate()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            Int32 iBankNameCount = moSchoolwiseBankMasterDC.CheckForDuplicateBankName();
            if (iBankNameCount != Constants.I_ZERO)
            {
                throw new BusinessLogic.DuplicateBankName("Bank name already exists.");
            }
        }

        public int InsertSchoolwiseBankMaster()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            IsHolidayNameDuplicate();
            return moSchoolwiseBankMasterDC.InsertSchoolwiseBankMaster();
        }

        public void UpdateSchoolwiseBankMaster()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            IsHolidayNameDuplicate();
            moSchoolwiseBankMasterDC.UpdateSchoolwiseBankMaster();
        }

        public void DeleteSchoolwiseBankMaster()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            moSchoolwiseBankMasterDC.DeleteSchoolwiseBankMaster();
        }

        public bool IsBankInCardPayment()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            return moSchoolwiseBankMasterDC.IsBankInCardPayment();
        }

        public bool IsBankInCashPayment()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            return moSchoolwiseBankMasterDC.IsBankInCashPayment();
        }

        public bool IsBankInPTchallan()
        {
            moSchoolwiseBankMasterDC.SchoolwiseBankMasterStructDetails = moSchoolwiseBankMasterStruct;
            return moSchoolwiseBankMasterDC.IsBankInPTchallan();
        }
        /// <summary>
        /// This method is used to get bank list for student caution money screen.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYrId"></param>
        /// <returns></returns>
        public DataTable GetSchoolwiseBankList(int aiSchoolId)
        {
            return moSchoolwiseBankMasterDC.GetSchoolwiseBankList(aiSchoolId);
        }

        /// <summary>
        /// This method is used to get the list of banks.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <returns></returns>
        public static List<BankDetails> GetBankDetails(int aiSchoolId)
        {
            return SchoolwiseBankMasterDC.GetBankDetails(aiSchoolId);
        }

        public static List<CardTypeDetails> GetCardTypeDetails(int aiSchoolId)
        {
            return SchoolwiseBankMasterDC.GetCardTypeDetails(aiSchoolId);
        }

        public DataTable GetSchoolwiseCardTypeList(int aiSchoolId)
        {
            return moSchoolwiseBankMasterDC.GetSchoolwiseCardTypeList(aiSchoolId);
        }

        /// <summary>
        /// This method is used to check whether given bank is referenced or not.
        /// </summary>
        /// <param name="aiBankId"></param>
        /// <returns></returns>
        public bool IsBankAlreadyUsed(int aiBankId)
        {
            return moSchoolwiseBankMasterDC.IsBankAlreadyUsed(aiBankId);
        }

        /// <summary>
        /// This method is used to save disabled bank period details.
        /// </summary>
        /// <param name="asBankXML"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <returns></returns>
        public List<DisbaleBankDetails> SaveBankDisablePeriodDetails(string asBankXML, int aiSchoolId, int aiUserId)
        {
            return moSchoolwiseBankMasterDC.SaveBankDisablePeriodDetails(asBankXML, aiSchoolId, aiUserId);
        }

        /// <summary>
        /// This method is used to get disabled bank details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <returns></returns>
        public List<DisbaleBankDetails> GetDisabledBankDetails(int aiSchoolId)
        {
            return moSchoolwiseBankMasterDC.GetDisabledBankDetails(aiSchoolId);
        }

        /// <summary>
        /// This method is used to delete disabled bank details.
        /// </summary>
        /// <param name="aiDisabledBankId"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <returns></returns>
        public List<DisbaleBankDetails> DeleteDisableBankDetails(int aiDisabledBankId, int aiSchoolId, int aiUserId)
        {
            return moSchoolwiseBankMasterDC.DeleteDisableBankDetails(aiDisabledBankId, aiSchoolId, aiUserId);
        }

        /// <summary>
        /// This method is used to get all the bank which are available for the net banking.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <returns></returns>
        public List<RegBankDetails> GetNetBankingDetails(int aiSchoolId)
        {
            return SchoolwiseBankMasterDC.GetNetBankingDetails(aiSchoolId);
        }

        /// <summary>
        /// This method is used to get currently active disabled bank details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiFeeType"></param>
        /// <returns></returns>
        public List<DisbaleBankDetails> GetCurrentlyActiveDisabledBankDetails(int aiSchoolId, int aiFeeType)
        {
            return moSchoolwiseBankMasterDC.GetCurrentlyActiveDisabledBankDetails(aiSchoolId, aiFeeType);
        }
    }

    public class DuplicateBankName : Exception
    {
        private string msMessage = " ";
        public override string Message
        {
            get
            {
                return msMessage;
            }
        }
        public DuplicateBankName(string asMessage)
        {
            msMessage = asMessage;
        }
    }

    public class SchoolwiseBankMasterCollectionBL
    {

        private SchoolwiseBankMasterCollectionDC moSchoolwiseBankMasterCollectionDC = new SchoolwiseBankMasterCollectionDC();


        public List<clsSchoolwiseBankMasterDC> lstSchoolwiseBankMaster
        {
            get
            {
                return moSchoolwiseBankMasterCollectionDC.olstSchoolwiseBankMasterDC;
            }
            set
            {
                moSchoolwiseBankMasterCollectionDC.olstSchoolwiseBankMasterDC = value;
            }
        }


        public void GetSchoolwiseBankMasterDetails(int aiSchoolId)
        {
            moSchoolwiseBankMasterCollectionDC.GetSchoolwiseBankMasterDetails(aiSchoolId);
        }

        // This function is used to Fetch the SchoolwiseBankMaster Details
        public static DataTable FetchSchoolwiseBankMasterDetails(int aiSchoolId)
        {
            return SchoolwiseBankMasterCollectionDC.FetchSchoolwiseBankMasterDetails(aiSchoolId);
        }

        // This function is used to Fetch the SchoolwiseBankMaster Details
        public static DataTable GetNetBankingBanksList(int aiSchoolId, int aiFeeType, int aiPaymentTypeId, int aiGatewayId)
        {
            return SchoolwiseBankMasterCollectionDC.GetNetBankingBanksList(aiSchoolId, aiFeeType,aiPaymentTypeId,aiGatewayId);
        }          
    }

    public class clsSchoolwiseBankMaster
    {
        private int miSchoolwise_Bank_Id;
        private int miCount;
        private string msBank_Name;
        private int miSchoolId;
        private string msIs_Deleted;

        public int Schoolwise_Bank_Id
        {
            get
            {
                return miSchoolwise_Bank_Id;
            }
            set
            {
                miSchoolwise_Bank_Id = value;
            }
        }
        public int Count
        {
            get
            {
                return miCount;
            }
            set
            {
                miCount = value;
            }
        }
        public string Bank_Name
        {
            get
            {
                return msBank_Name;
            }
            set
            {
                msBank_Name = value;
            }
        }
        public int SchoolId
        {
            get
            {
                return miSchoolId;
            }
            set
            {
                miSchoolId = value;
            }
        }
        public string Is_Deleted
        {
            get
            {
                return msIs_Deleted;
            }
            set
            {
                msIs_Deleted = value;
            }
        }

    }

}
