//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- SmsTemplateBL
// Purpose          :- This class is used to manage SmsTemplate details.
// Date Of creation :- 12/7/2009
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;




namespace BusinessLogic
{


    public class SmsTemplateBL
    {

        private SmsTemplateDC.SmsTemplateStruct moSmsTemplateStruct;

        private SmsTemplateDC moSmsTemplateDC;

        public SmsTemplateBL()
        {
            moSmsTemplateDC = new SmsTemplateDC();
        }

        public SmsTemplateBL(int aiSchoolId, int aiAcademicYearId)
        {
            moSmsTemplateDC = new SmsTemplateDC(aiSchoolId, aiAcademicYearId);
        }

        public SmsTemplateBL(int miTemplateId)
        {
            moSmsTemplateDC = new SmsTemplateDC(miTemplateId);
            moSmsTemplateStruct = moSmsTemplateDC.SmsTemplateStructDetails;
        }

        public   int TemplateId
        {
            get
            {
                return moSmsTemplateStruct.miTemplateId;
            }
            set
            {
                moSmsTemplateStruct.miTemplateId = value;
            }
        }

        public   string SmsName
        {
            get
            {
                return moSmsTemplateStruct.msSmsName;
            }
            set
            {
                moSmsTemplateStruct.msSmsName = value;
            }
        }

        public   string TemplateText
        {
            get
            {
                return moSmsTemplateStruct.msTemplateText;
            }
            set
            {
                moSmsTemplateStruct.msTemplateText = value;
            }
        }
        public string TemplateRegistrationId
        {
            get
            {
                return moSmsTemplateStruct.msTemplateRegistrationId;
            }
            set
            {
                moSmsTemplateStruct.msTemplateRegistrationId = value;
            }
        }

        public   int SchoolId
        {
            get
            {
                return moSmsTemplateStruct.miSchool_Id;
            }
            set
            {
                moSmsTemplateStruct.miSchool_Id = value;
            }
        }

        public   int AcademicYearId
        {
            get
            {
                return moSmsTemplateStruct.miAcademicYearId;
            }
            set
            {
                moSmsTemplateStruct.miAcademicYearId = value;
            }
        }

        public   bool IsDeleted
        {
            get
            {
                return moSmsTemplateStruct.mblnIsDeleted;
            }
            set
            {
                moSmsTemplateStruct.mblnIsDeleted = value;
            }
        }     

        public   int InsertSmsTemplate()
        {
            moSmsTemplateDC.SmsTemplateStructDetails = moSmsTemplateStruct;
            return moSmsTemplateDC.InsertSmsTemplate();
        }

        public void UpdateSmsTemplate()
        {
            moSmsTemplateDC.SmsTemplateStructDetails = moSmsTemplateStruct;
            moSmsTemplateDC.UpdateSmsTemplate();
        }

        public void Delete(int aiTemplateId)
        {
            moSmsTemplateDC.Delete( aiTemplateId);
        }

        public static DataSet FillSmsNameComboAndDyanamicVariableList(int aiSchoolId,int aiAcademicYearId)
        {
           return SmsTemplateDC.FillSmsNameComboAndDyanamicVariableList(aiSchoolId, aiAcademicYearId);
        }

        public static DataTable GetTemplate(int aiSmsId,int aiSchoolId)
        {
            return SmsTemplateDC.GetTemplate(aiSmsId, aiSchoolId);
        }

        public static DataTable GetTemplate(string asSMSType, int aiSchoolId)
        {
            return SmsTemplateDC.GetTemplate(asSMSType, aiSchoolId);
        }

        /// <summary>
        /// This method is used to get all the templates into the listview with their associating status.It is called from Object data source
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiGroupId"></param>
        /// <param name="maximumRows"></param>
        /// <param name="startRowIndex"></param>
        /// <param name="sortDirection"></param>
        /// <returns></returns>
        public DataTable GetAll(int aiSchoolId, int maximumRows, int startRowIndex, string sortDirection, string ShowSystemDefined)
        {
            return moSmsTemplateDC.GetAll(aiSchoolId, sortDirection, ShowSystemDefined);
        }
        
        /// <summary>
        /// This method is used to return a templates count to Object data source. 
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiGroupId"></param>
        /// <param name="sortDirection"></param>
        /// <returns></returns>
        public int Count(int aiSchoolId,string sortDirection,string ShowSystemDefined)
        {
            return moSmsTemplateDC.Count(aiSchoolId, ShowSystemDefined);
        }

        /// <summary>
        /// This procedure is used to insert & update the template details.
        /// </summary>
        public void Insert()
        {
            moSmsTemplateDC.SmsTemplateStructDetails = moSmsTemplateStruct;
            moSmsTemplateDC.Insert();
        }
    }
}
