//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- StudentCautionMoneyDetailsBL
// Purpose          :- This class is used to manage StudentCautionMoneyDetails details.
// Date Of creation :- 12/31/2008
// Author Name      :- 

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using DataCommunicator;
using Utility;

namespace BusinessLogic
{
	public class StudentCautionMoneyDetailsBL
	{
		public StudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStruct moStudentCautionMoneyDetailsStruct;
		private StudentCautionMoneyChequeDetailsBL moStudentCautionMoneyChequeDetailsBL;
		private StudentCautionMoneyDetailsDC moStudentCautionMoneyDetailsDC;

		public StudentCautionMoneyDetailsBL()
		{
			moStudentCautionMoneyDetailsDC = new StudentCautionMoneyDetailsDC();
		}

		public StudentCautionMoneyDetailsBL(int miStudentCautionMoneyId)
		{
			moStudentCautionMoneyDetailsDC = new StudentCautionMoneyDetailsDC(miStudentCautionMoneyId);
			moStudentCautionMoneyDetailsStruct = moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails;
		}

		#region Properties

		public int Student_Caution_Money_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miStudentCautionMoneyId; }
			set { moStudentCautionMoneyDetailsStruct.miStudentCautionMoneyId = value; }
		}

		public StudentCautionMoneyChequeDetailsBL StudentCautionMoneyChequeDetails
		{
			get { return moStudentCautionMoneyChequeDetailsBL; }
			set { moStudentCautionMoneyChequeDetailsBL = value; }
		}

		public int School_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miSchoolId; }
			set { moStudentCautionMoneyDetailsStruct.miSchoolId = value; }
		}

		public int Schoolwise_Student_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miSchoolwiseStudentId; }
			set { moStudentCautionMoneyDetailsStruct.miSchoolwiseStudentId = value; }
		}

		public int Amount
		{
			get { return moStudentCautionMoneyDetailsStruct.miAmount; }
			set { moStudentCautionMoneyDetailsStruct.miAmount = value; }
		}

		public bool Paid_By_Student
		{
			get { return moStudentCautionMoneyDetailsStruct.mblnPaidByStudent; }
			set { moStudentCautionMoneyDetailsStruct.mblnPaidByStudent = value; }
		}

		public DateTime Payment_Date
		{
			get { return moStudentCautionMoneyDetailsStruct.mdtPaymentDate; }
			set { moStudentCautionMoneyDetailsStruct.mdtPaymentDate = value; }
		}

		public bool Returned_By_School
		{
			get { return moStudentCautionMoneyDetailsStruct.mblnReturnedBySchool; }
			set { moStudentCautionMoneyDetailsStruct.mblnReturnedBySchool = value; }
		}

		public DateTime Return_Date
		{
			get { return moStudentCautionMoneyDetailsStruct.mdtReturnDate; }
			set { moStudentCautionMoneyDetailsStruct.mdtReturnDate = value; }
		}

		public string Payment_Mode
		{
			get { return moStudentCautionMoneyDetailsStruct.msPaymentMode; }
			set { moStudentCautionMoneyDetailsStruct.msPaymentMode = value; }
		}

		public string Return_Mode
		{
			get { return moStudentCautionMoneyDetailsStruct.msReturnMode; }
			set { moStudentCautionMoneyDetailsStruct.msReturnMode = value; }
		}

		public string Remarks
		{
			get { return moStudentCautionMoneyDetailsStruct.msRemark; }
			set { moStudentCautionMoneyDetailsStruct.msRemark = value; }
		}

		public int Payment_Cheque_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miPaymentChequeId; }
			set { moStudentCautionMoneyDetailsStruct.miPaymentChequeId = value; }
		}

		public int Return_Cheque_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miReturnChequeId; }
			set { moStudentCautionMoneyDetailsStruct.miReturnChequeId = value; }
		}

		public DateTime Insert_Date
		{
			get { return moStudentCautionMoneyDetailsStruct.mdtInsertDate; }
			set { moStudentCautionMoneyDetailsStruct.mdtInsertDate = value; }
		}

		public int Inserted_By_id
		{
			get { return moStudentCautionMoneyDetailsStruct.miInsertedByid; }
			set { moStudentCautionMoneyDetailsStruct.miInsertedByid = value; }
		}

		public DateTime Update_Date
		{
			get { return moStudentCautionMoneyDetailsStruct.mdtUpdateDate; }
			set { moStudentCautionMoneyDetailsStruct.mdtUpdateDate = value; }
		}

		public int Updated_By_Id
		{
			get { return moStudentCautionMoneyDetailsStruct.miUpdatedById; }
			set { moStudentCautionMoneyDetailsStruct.miUpdatedById = value; }
		}

        public string PaidByName
        {
            get { return moStudentCautionMoneyDetailsStruct.msPaidByName; }
            set { moStudentCautionMoneyDetailsStruct.msPaidByName = value; }
        }

        public int ConcessionAmount
        {
            get { return moStudentCautionMoneyDetailsStruct.miConcessionAmount; }
            set { moStudentCautionMoneyDetailsStruct.miConcessionAmount = value; }
        }

        public int ReturnAmount
        {
            get { return moStudentCautionMoneyDetailsStruct.miReturnAmount; }
            set { moStudentCautionMoneyDetailsStruct.miReturnAmount = value; }
        }

		#endregion Properties

		public int InsertStudentCautionMoneyPaidDetails()
		{
			moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails = moStudentCautionMoneyDetailsStruct;
			return moStudentCautionMoneyDetailsDC.InsertStudentCautionMoneyPaidDetails();
		}

		public string GetUpdateStatementForStudentCautionMoneyPaidDetails()
		{
			moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails = moStudentCautionMoneyDetailsStruct;
			return moStudentCautionMoneyDetailsDC.GetUpdateStatementForStudentCautionMoneyPaidDetails();
		}

		public int InsertStudentCautionMoneyReturnDetails()
		{
			moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails = moStudentCautionMoneyDetailsStruct;
			return moStudentCautionMoneyDetailsDC.InsertStudentCautionMoneyReturnDetails();
		}

		public void UpdateStudentCautionMoneyPaidDetails()
		{
			moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails = moStudentCautionMoneyDetailsStruct;
			moStudentCautionMoneyDetailsDC.UpdateStudentCautionMoneyPaidDetails();
		}

		public void UpdateStudentCautionMoneyReturnDetails()
		{
			moStudentCautionMoneyDetailsDC.StudentCautionMoneyDetailsStructDetails = moStudentCautionMoneyDetailsStruct;
			moStudentCautionMoneyDetailsDC.UpdateStudentCautionMoneyReturnDetails();
		}

		public DataTable GetDataForReciept(int aiStudentId, int aiSchoolId, string asIsReturnMode)
		{
            return moStudentCautionMoneyDetailsDC.GetDataForReciept(aiStudentId, aiSchoolId, asIsReturnMode);
		}

		public DataTable GetStudentCautionMoneyDetails(int iStudentID, int iAcademicYrID, int iSchoolID)
		{
			return moStudentCautionMoneyDetailsDC.GetStudentCautionMoneyDetails(iStudentID, iAcademicYrID, iSchoolID);
		}
		
		public DataTable GetStudentCautionMoneyDetail(int iStudentID, int iAcademicYrID, int iSchoolID)
		{
			return moStudentCautionMoneyDetailsDC.GetStudentCautionMoneyDetail(iStudentID, iAcademicYrID, iSchoolID);
		}
	}

	public class StudentCautionMoneyDetailsCollectionBL : BusinessLogicBaseBL
	{
        private int miStudentCountForCautionMoney;

		StudentCautionMoneyDetailsCollectionDC moStudentCautionMoneyDetailsCollectionDC = new StudentCautionMoneyDetailsCollectionDC();

		public StudentCautionMoneyDetailsCollectionBL()
		{

		}

        public DataTable GetStudentCautionMoneyDetails(int aiSchoolId, string asRegNo, bool abIncludePaid, bool abIncludeReturned, string aiChequeNumber, string adtFromDate, string adtToDate, string adtReturnStartDate, string adtReturnEndDate, String sortExpression, int maximumRows, int startRowIndex, int aiAcademicYearId)
		{
            DataTable oDT = moStudentCautionMoneyDetailsCollectionDC.GetStudentCautionMoneyDetails(aiSchoolId, asRegNo, abIncludePaid, abIncludeReturned, aiChequeNumber, adtFromDate, adtToDate, adtReturnStartDate, adtReturnEndDate, sortExpression, maximumRows, startRowIndex, aiAcademicYearId);
            if (oDT != null && oDT.Rows.Count > 0)
                miStudentCountForCautionMoney = Convert.ToInt32(oDT.Rows[0]["TotalRows"]);
            return oDT;
		}

        public int CountStudentsForCautionMoney(int aiSchoolId, string asRegNo, bool abIncludePaid, bool abIncludeReturned, string aiChequeNumber, string adtFromDate, string adtToDate, string adtReturnStartDate, string adtReturnEndDate, int aiAcademicYearId)
		{
            return miStudentCountForCautionMoney;
		}
		
		public DataTable GetReturnedCautionMoneyDetails(int aiStudentId)
		{
			return moStudentCautionMoneyDetailsCollectionDC.GetReturnedCautionMoneyDetails(aiStudentId);
		}

		public void InsertMultipleCautionMoney(List<StudentCautionMoneyDetailsBL> aoArrStudentCautionMoneyDetailsBL)
		{
			ArrayList oArrayList = new ArrayList();
			foreach (StudentCautionMoneyDetailsBL oStudentCautionMoneyDetailsBL in aoArrStudentCautionMoneyDetailsBL)
			{
				oArrayList.Add(oStudentCautionMoneyDetailsBL.StudentCautionMoneyChequeDetails.GetInsertStatementForStudentCautionMoneyChequeDetails());
				if (oStudentCautionMoneyDetailsBL.Payment_Mode == 'Q'.ToString())
					oArrayList.Add(GetSelectStatementForLastInsertedPKey(Constants.S_LAST_INSERTED_P_KEY));
				oArrayList.Add(oStudentCautionMoneyDetailsBL.GetUpdateStatementForStudentCautionMoneyPaidDetails());
			}

			moStudentCautionMoneyDetailsCollectionDC.InsertMultipleCautionMoney(oArrayList);
		}

		public int GetStudentAcademicYearId(int aiStudentId, int aiSchoolId, int aiAcademicYearId)
		{
			return moStudentCautionMoneyDetailsCollectionDC.GetStudentAcademicYearId(aiStudentId, aiSchoolId, aiAcademicYearId);
		}
		
		public int GetTotalAmountofCautionMoney(int aiSchoolId, string asRegNo, bool abIncludePaid, bool abIncludeReturned, string aiChequeNumber, string adtFromDate, string adtToDate)
		{
			return moStudentCautionMoneyDetailsCollectionDC.GetTotalAmountofCautionMoney(aiSchoolId, asRegNo, abIncludePaid, abIncludeReturned, aiChequeNumber, adtFromDate, adtToDate);
		}

        /// <summary>
        /// This method is used to delete the student Caution Money Details.
        /// </summary>
        /// <param name="aiStudentId"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUpdatedById"></param>
        /// <param name="abIsReturn"></param>
        public void DeleteCautionMoneyDetails(int aiStudentId, int aiSchoolId, int aiUpdatedById, bool abIsReturn)
        {
            moStudentCautionMoneyDetailsCollectionDC.DeleteCautionMoneyDetails(aiStudentId, aiSchoolId, aiUpdatedById, abIsReturn);
        }
	}
}
