//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- StudentwiseRemarkMasterBL
// Purpose          :- This class is used to manage StudentwiseRemarkMaster details.
// Date Of creation :- 10/15/2010
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using DataCommunicator;
using ProgressReportEntities;
using StudentEntities;
namespace BusinessLogic
{


    public class StudentwiseRemarkMasterBL
    {

        private StudentwiseRemarkMasterDC.StudentwiseRemarkMasterStruct moStudentwiseRemarkMasterStruct;

        private StudentwiseRemarkMasterDC moStudentwiseRemarkMasterDC;

        public StudentwiseRemarkMasterBL()
        {
            moStudentwiseRemarkMasterDC = new StudentwiseRemarkMasterDC();
        }

        public StudentwiseRemarkMasterBL(int miStudentwiseRemarkId)
        {
            moStudentwiseRemarkMasterDC = new StudentwiseRemarkMasterDC(miStudentwiseRemarkId);
            moStudentwiseRemarkMasterStruct = moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails;
        }

        public List<StudentwiseRemarkConfigDetails> olstStudentwiseRemarkConfigDetails
        {
            get
            {
                return moStudentwiseRemarkMasterDC.lstStudentwiseRemarkConfigDetails;
            }
            set
            {
                moStudentwiseRemarkMasterDC.lstStudentwiseRemarkConfigDetails = value;
            }
        }

        public List<StudentwiseRemarkConfigDetails> StudenRemarks
        {
            get
            {
                return moStudentwiseRemarkMasterDC.StudenRemarks;
            }
            set
            {
                moStudentwiseRemarkMasterDC.StudenRemarks = value;
            }
        }

        public List<StudentwiseRemarkConfigDetails> RemarkCategories
        {
            get
            {
                return moStudentwiseRemarkMasterDC.RemarkCategories;
            }
            set
            {
                moStudentwiseRemarkMasterDC.RemarkCategories = value;
            }
        }      

        public List<RemarkMaster> olstRemarkMaster
        {
            get
            {
                return moStudentwiseRemarkMasterDC.olstRemarkMaster;
            }
            set
            {
                moStudentwiseRemarkMasterDC.olstRemarkMaster = value;
            }
        }
         
        public virtual int Studentwise_Remark_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miStudentwiseRemarkId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miStudentwiseRemarkId = value;
            }
        }

        public virtual int Yearwise_Student_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miYearwiseStudentId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miYearwiseStudentId = value;
            }
        }

        public virtual int Teacher_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miTeacherId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miTeacherId = value;
            }
        }

        public virtual string Remark
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.msRemark;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.msRemark = value;
            }
        }

        public virtual int School_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miSchoolId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miSchoolId = value;
            }
        }

        public virtual int Academic_Year_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miAcademicYearId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miAcademicYearId = value;
            }
        }

        public virtual bool Is_Deleted
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.mblnIsDeleted;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.mblnIsDeleted = value;
            }
        }

        public virtual int Term_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miTermId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miTermId = value;
            }
        }

        public virtual int Standard_Division_Id
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miStandardDivisionId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miStandardDivisionId = value;
            }
        }

        public virtual System.DateTime InsertDate
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.mdtInsertDate;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.mdtInsertDate = value;
            }
        }

        public virtual int InsertedbyId
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miInsertedbyId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miInsertedbyId = value;
            }
        }

        public virtual System.DateTime UpdateDate
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.mdtUpdateDate;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.mdtUpdateDate = value;
            }
        }

        public virtual int UpdatedbyId
        {
            get
            {
                return moStudentwiseRemarkMasterStruct.miUpdatedbyId;
            }
            set
            {
                moStudentwiseRemarkMasterStruct.miUpdatedbyId = value;
            }
        }

        public virtual int InsertStudentwiseRemarkMaster(int aiStudentId)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            return moStudentwiseRemarkMasterDC.InsertStudentwiseRemarkMaster(aiStudentId);
        }

        public virtual void UpdateStudentwiseRemarkMaster()
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            moStudentwiseRemarkMasterDC.UpdateStudentwiseRemarkMaster();
        }

        public virtual void DeleteStudentwiseRemarkMaster(int aiStudentId, int iSchoolId, int iAcademicYearId, int iTermId)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            moStudentwiseRemarkMasterDC.DeleteStudentwiseRemarkMaster(aiStudentId, iSchoolId, iAcademicYearId, iTermId);
        }

        public DataTable GetAllStudents(int aiSchoolId, int aiAcademicYearId, int aiTeacherId, int aiStudentId, int aiTermId, string sortExpression, int maximumRows, int startRowIndex)
        {
            int iStartIndex = startRowIndex;
            int iEndIndex = iStartIndex + maximumRows;
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            return moStudentwiseRemarkMasterDC.GetAllStudents(aiSchoolId, aiAcademicYearId, sortExpression, iEndIndex, startRowIndex, aiTeacherId, aiStudentId, aiTermId);
        }

        public int CountTotalStudents(Int32 aiSchoolId, Int32 aiAcademicYearId, int aiTeacherId, int aiStudentId, int aiTermId, string sortExpression, int maximumRows, int startRowIndex)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            return moStudentwiseRemarkMasterDC.CountTotalStudents(aiSchoolId, aiAcademicYearId, sortExpression, maximumRows, startRowIndex, aiTeacherId, aiStudentId, aiTermId);
        }

        public void UpdateStudentRemark(string sXML)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            moStudentwiseRemarkMasterDC.UpdateStudentRemark(sXML);
        }

        /// <summary>
        /// This method is used to Get flag for Final Exam published status for current year.
        /// </summary>
        /// <param name="aiStandard_Div_Id"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiTermId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <returns></returns>
        public bool GetFinalPublishedExamStatus(int aiStandard_Div_Id, int aiSchoolId, int aiTermId, int aiAcademicYearId, out bool abIsPublishedStatus)
        {
           return moStudentwiseRemarkMasterDC.GetFinalPublishedExamStatus(aiStandard_Div_Id, aiSchoolId, aiTermId, aiAcademicYearId, out abIsPublishedStatus);
        }

        /// <summary>
        /// This method is used to update student remark details.
        /// </summary>
        /// <param name="sXML"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiLoginUserId"></param>
        /// <param name="aiStandardDivId"></param>
        /// <param name="aiTerm"></param>
        public void UpdateStudentwiseRemarkDetails(string sXML, int aiSchoolId, int aiAcademicYearId, int aiLoginUserId, int aiStandardDivId, int aiTerm)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            moStudentwiseRemarkMasterDC.UpdateStudentwiseRemarkDetails(sXML, aiSchoolId, aiAcademicYearId, aiLoginUserId, aiStandardDivId, aiTerm);
        }
        

        /// <summary>
        /// This method is used to check whether exams are conducted for selected term. 
        /// </summary>
        /// <param name="aiStudentId"></param>
        /// <param name="aiStdDivId"></param>
        /// <param name="aiTermId"></param>
        /// <param name="aiStandardId"></param>
        /// <param name="iSchoolID"></param>
        /// <param name="iAcadYearID"></param>
        /// <returns></returns>
        public DataTable IsReportEmpty(int aiStudentId, int aiStdDivId, int aiTermId, int aiStandardId, int iSchoolID, int iAcadYearID)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            return moStudentwiseRemarkMasterDC.IsReportEmpty(aiStudentId, aiStdDivId, aiTermId, aiStandardId, iSchoolID, iAcadYearID);
        }

        /// <summary>
        /// This method is used to get the student list of selected class teacher to fill student combo box.
        /// </summary>
        /// <param name="iTeacherId"></param>
        /// <param name="aiAcadYearID"></param>
        /// <param name="aiSchoolID"></param>
        /// <returns></returns>
        public DataTable GetStudentListOfGivenClassTeacher(int iTeacherId, int aiAcadYearID, int aiSchoolID, int aiTermId)
        {
            moStudentwiseRemarkMasterDC.StudentwiseRemarkMasterStructDetails = moStudentwiseRemarkMasterStruct;
            return moStudentwiseRemarkMasterDC.GetStudentListOfGivenClassTeacher(iTeacherId, aiAcadYearID, aiSchoolID, aiTermId);
        }


        public static DataTable GetTestwiseTerm(int iSchoolId)
        {
            return StudentwiseRemarkMasterDC.GetTestwiseTerm(iSchoolId);
        }

        public void GetStudentwiseRemarkConfigDetails(Int32 aiSchoolId, Int32 aiAcademicYearId, int aiTeacherId, int aiStudentId, int aiTermId)
        {
            moStudentwiseRemarkMasterDC.GetStudentwiseRemarkConfigDetails(aiSchoolId, aiAcademicYearId, aiTeacherId, aiStudentId, aiTermId);
        }

        /// <summary>
        /// This Method is used to get records of Student data to Export.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiTeacherId"></param>
        /// <param name="aiStudentId"></param>
        /// <param name="aiTermId"></param>
        /// <returns></returns>
        public List<StudentInfo> GetStudentDataToExport(int aiSchoolId, int aiAcademicYearId, int aiTeacherId, int aiStudentId, int aiTermId)
        {
          return  moStudentwiseRemarkMasterDC.GetStudentDataToExport(aiSchoolId, aiAcademicYearId, aiTeacherId, aiStudentId, aiTermId);
        }

       
    }
}
