//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- InternalFeeDetailsDC
// Purpose          :- This class is used to manage InternalFeeDetails details.
// Date Of creation :- 5/5/2010
// Author Name      :- 


using System;
using System.Data;
using System.Data.SqlClient;
using Utility;
using FeeEntities;
using System.Collections.Generic;

namespace DataCommunicator
{


    public class InternalFeeDetailsDC
    {

        private InternalFeeDetailsStruct moInternalFeeDetailsStruct;

        public InternalFeeDetailsDC()
        {
        }

        public InternalFeeDetailsDC(int miInternalFeeDetailsId)
        {
            LoadInternalFeeDetailsDetails(miInternalFeeDetailsId);
        }

        public virtual InternalFeeDetailsStruct InternalFeeDetailsStructDetails
        {
            get
            {
                return moInternalFeeDetailsStruct;
            }
            set
            {
                moInternalFeeDetailsStruct = value;
            }
        }

        // This function is used to insert the InternalFeeDetails Details
        public DataTable InsertInternalFeeDetails(string asInternalFeeDebitDetails, int aiUserId, int aiSchoolId, int aiAcademicYearId, DateTime aDtSelectedDate, int aiStudentId, string asChequeDetailsXml, int aiPaymentTypeId, bool abIsNextYearPayment,string asElectronicDetailsXml)
        {  
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                //oSQLServerDbUtility.AddParameter("InternalFeeDetailsId", moInternalFeeDetailsStruct.miInternalFeeDetailsId, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("Amount", moInternalFeeDetailsStruct.miAmount, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InternalFeeDebitDetailsXML", asInternalFeeDebitDetails, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("PaidDate", aDtSelectedDate, SqlDbType.Date);
                //oSQLServerDbUtility.AddParameter("Remark", StringUtility.ReplaceSingleQuoteInString(moInternalFeeDetailsStruct.msRemark, false), SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiUserId, SqlDbType.Int);

                if (asChequeDetailsXml != string.Empty)
                    oSQLServerDbUtility.AddParameter("ChequeDetailsXml", asChequeDetailsXml, SqlDbType.Xml);

                oSQLServerDbUtility.AddParameter("PaymentTypeId", aiPaymentTypeId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearPayment", abIsNextYearPayment, SqlDbType.Bit);
                if (asElectronicDetailsXml != string.Empty)
                    oSQLServerDbUtility.AddParameter("ElectronicDetailsXml", asElectronicDetailsXml, SqlDbType.Xml);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_InsertInternalFeeDetals",true);
            }
        }

        public DataTable InsertDuplicateInternalFeeReceiptDetails()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("InternalFeeDetailsIds", moInternalFeeDetailsStruct.msInternalFeeDetailsIds, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("PaidDate", moInternalFeeDetailsStruct.mdtPaidDate, SqlDbType.SmallDateTime);
                oSQLServerDbUtility.AddParameter("Remark", moInternalFeeDetailsStruct.msRemark, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("SchoolId", moInternalFeeDetailsStruct.miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", moInternalFeeDetailsStruct.miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Schoolwise_Student_Id", moInternalFeeDetailsStruct.miSchoolwiseStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", moInternalFeeDetailsStruct.miInsertedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ShowConsolidatedPartialPayments", moInternalFeeDetailsStruct.mbShowConsolidatedPartialPayments, SqlDbType.Bit);

                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_InternalDuplicateFeeReceiptDetails",true);
            }
        }

        // This function is used to update the InternalFeeDetails Details
        public virtual void UpdateInternalFeeDetails()
        {
            string sUpdateStatement = "UPDATE InternalFeeDetails SET " +
            "ReceiptNo= " + moInternalFeeDetailsStruct.miReceiptNo +
            ",Schoolwise_Student_Id= " + moInternalFeeDetailsStruct.miSchoolwiseStudentId +
            ",Amount= " + moInternalFeeDetailsStruct.miAmount +
            ",PaidDate= N'" + moInternalFeeDetailsStruct.mdtPaidDate + "' " +
            ",Remark= N'" + StringUtility.ReplaceSingleQuoteInString(moInternalFeeDetailsStruct.msRemark, false) + "' " +
            ",SchoolId= " + moInternalFeeDetailsStruct.miSchoolId +
            ",AcademicYearId= " + moInternalFeeDetailsStruct.miAcademicYearId +
            ",InsertedById= " + moInternalFeeDetailsStruct.miInsertedById +
            ",InsertDate= N'" + moInternalFeeDetailsStruct.mdtInsertDate + "' " +
            ",UpdatedById= " + moInternalFeeDetailsStruct.miUpdatedById +
            ",UpdateDate= N'" + moInternalFeeDetailsStruct.mdtUpdateDate + "' " +
            "" +
            " WHERE InternalFeeDetailsId=" + moInternalFeeDetailsStruct.miInternalFeeDetailsId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        // This function is used to delete the InternalFeeDetails Details
        public virtual void DeleteInternalFeeDetails(int aiInternalFeeDetailsId)
        {
            string sQueryStatement = " INSERT INTO InternalFeeDetails( " +
                                    " ReceiptNo,Schoolwise_Student_Id, Fee_Type, Payable_For, Amount, Standard_Div_Id, [Debit/Credit], PaidDate, " +
                                    " InternalFeeMasterID, Remark, SchoolId, AcademicYearId, InsertedById, InsertDate,UpdatedById) " +
                                " SELECT 0,Schoolwise_Student_Id, Fee_Type, Payable_For,Amount,Standard_Div_Id " +
                     " ,'Debit', PaidDate,InternalFeeMasterID,Remark,SchoolId, AcademicYearId,InsertedById,dbo.GetLocalDate(DEFAULT),UpdatedById" +
                    " FROM InternalFeeDetails  where InternalFeeDetailsId = " + aiInternalFeeDetailsId.ToString();

            sQueryStatement += " UPDATE InternalFeeDetails SET Is_Deleted = 1 " +
                                " WHERE InternalFeeDetailsId =" + aiInternalFeeDetailsId.ToString();

            sQueryStatement += " UPDATE InternalFeeDetails SET Is_Deleted = 1 " +
                                " WHERE FeeDetailsID =" + aiInternalFeeDetailsId.ToString();

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sQueryStatement);
        }


        public void DeleteInternalFeeDetails(int aiInternalFeeDetailsId, int aiSchoolId, int aiAcademicYearId, int aiStudentId, int aiUpdatedById, bool abIsNextYearPayment, int aiInternalFeeMasterId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("InternalFeeDetailsId",aiInternalFeeDetailsId, SqlDbType.Int);                
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UpdatedById", aiUpdatedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearPayment", abIsNextYearPayment, SqlDbType.Bit);
                oSQLServerDbUtility.AddParameter("InternalFeeMasterId", aiInternalFeeMasterId, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_DeleteInternalFeeDetails");
            }
        }
        // This function is used to load the InternalFeeDetails Details
        private void LoadInternalFeeDetailsDetails(int miInternalFeeDetailsId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchInternalFeeDetailsDetailsFromDatabase(miInternalFeeDetailsId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    if (oDR != null)
                    {
                        while (oDR.Read())
                        {
                            if (oDR["InternalFeeDetailsId"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miInternalFeeDetailsId = Convert.ToInt32(oDR["InternalFeeDetailsId"]);
                            if (oDR["ReceiptNo"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miReceiptNo = Convert.ToInt32(oDR["ReceiptNo"]);
                            if (oDR["Schoolwise_Student_Id"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miSchoolwiseStudentId = Convert.ToInt32(oDR["Schoolwise_Student_Id"]);
                            if (oDR["Amount"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miAmount = Convert.ToInt32(oDR["Amount"]);
                            if (oDR["PaidDate"] != DBNull.Value)
                                moInternalFeeDetailsStruct.mdtPaidDate = Convert.ToDateTime(oDR["PaidDate"]);
                            if (oDR["Remark"] != DBNull.Value)
                                moInternalFeeDetailsStruct.msRemark = Convert.ToString(oDR["Remark"]);
                            if (oDR["SchoolId"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miSchoolId = Convert.ToInt32(oDR["SchoolId"]);
                            if (oDR["AcademicYearId"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miAcademicYearId = Convert.ToInt32(oDR["AcademicYearId"]);
                            if (oDR["InsertedById"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miInsertedById = Convert.ToInt32(oDR["InsertedById"]);
                            if (oDR["InsertDate"] != DBNull.Value)
                                moInternalFeeDetailsStruct.mdtInsertDate = Convert.ToDateTime(oDR["InsertDate"]);
                            if (oDR["UpdatedById"] != DBNull.Value)
                                moInternalFeeDetailsStruct.miUpdatedById = Convert.ToInt32(oDR["UpdatedById"]);
                            if (oDR["UpdateDate"] != DBNull.Value)
                                moInternalFeeDetailsStruct.mdtUpdateDate = Convert.ToDateTime(oDR["UpdateDate"]);
                        }
                    }
                }
            }
        }

        // This function is used to fetch the InternalFeeDetails Details
        private String FetchInternalFeeDetailsDetailsFromDatabase(int miInternalFeeDetailsId)
        {
            string sSelectStatement = " SELECT  " +
            "InternalFeeDetailsId" +
            ",ReceiptNo" +
            ",Schoolwise_Student_Id" +
            ",Amount" +
            ",PaidDate" +
            ",Remark" +
            ",SchoolId" +
            ",AcademicYearId" +
            ",InsertedById" +
            ",InsertDate" +
            ",UpdatedById" +
            ",UpdateDate" +
            " FROM InternalFeeDetails" +
            " WHERE InternalFeeDetailsId=" + miInternalFeeDetailsId;
            return sSelectStatement;
        }


        public DataTable GetStudentInternalFeeDetails(int aiSchoolId, int aiAcademicYearId, string asRegNo, String sortExpression, int iEndIndex, int iStartIndex)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("RegNumber", StringUtility.ReplaceSingleQuoteInString(asRegNo, true), SqlDbType.NVarChar);
                //oSQLServerDbUtility.AddParameter("IncludePaid", abIncludePaid, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("IsPayForNextYear", abIsPayForNextYear, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("FeeTypeID", StringUtility.ReplaceSingleQuoteInString(asFeeTypeID,true), SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("StartIndex", iStartIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EndIndex", iEndIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SortExp", sortExpression == "" ? "" : " ORDER BY " + sortExpression, SqlDbType.NVarChar);
                //if (adtFromDate != null)
                //{
                //    oSQLServerDbUtility.AddParameter("FromDate", Convert.ToDateTime(adtFromDate), SqlDbType.DateTime);
                //    oSQLServerDbUtility.AddParameter("ToDate", Convert.ToDateTime(adtToDate), SqlDbType.DateTime);
                //}
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAllInternalFeeDetails");
            }
        }

        public static DataTable GetInternalFeesStudentForSMS(int aiSchoolId, int aiAcademicYearId, string asRegNo, bool abIncludePaid, bool abIsPayForNextYear, string adtFromDate, string adtToDate, string asFeeTypeID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("RegNumber", StringUtility.ReplaceSingleQuoteInString(asRegNo, true), SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("IncludePaid", abIncludePaid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsPayForNextYear", abIsPayForNextYear, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("FeeTypeID", asFeeTypeID, SqlDbType.NVarChar);
                if (!string.IsNullOrEmpty(adtFromDate))
                {
                    oSQLServerDbUtility.AddParameter("FromDate", Convert.ToDateTime(adtFromDate), SqlDbType.DateTime);
                    oSQLServerDbUtility.AddParameter("ToDate", Convert.ToDateTime(adtToDate), SqlDbType.DateTime);
                }
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetInternalFeesStudentForSMS");
            }
        }

        public struct InternalFeeDetailsStruct
        {

            public int miInternalFeeDetailsId;

            public int miReceiptNo;

            public int miSchoolwiseStudentId;

            public int miAmount;

            public System.DateTime mdtPaidDate;

            public string msRemark;

            public int miSchoolId;

            public int miAcademicYearId;

            public int miInsertedById;

            public System.DateTime mdtInsertDate;

            public int miUpdatedById;

            public System.DateTime mdtUpdateDate;

            public string msInternalFeeDetailsIds;

            public bool mbShowConsolidatedPartialPayments;
        }

        public static bool IsMidGenreated(int aiAcademicYearId, int aiSchoolID)
        {
            string sSelectStatement = "SELECT [dbo].[udf_IsMidConfiured](" + aiAcademicYearId + ", " + aiSchoolID + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return Convert.ToBoolean(oSQLServerDbUtility.PerformStringQueryOnSqlServer(sSelectStatement));
        }

        public static DataTable GetRemark(int aiSchoolId, int aiAcademicYearId, int aiInternalFeeDetailsId)
        {
            string sSelectStatement = "SELECT Fee_Type, Payable_For, Amount,Remark  FROM InternalFeeDetails WHERE SchoolId=" + aiSchoolId +
                " AND" +
                " AcademicYearId=" + aiAcademicYearId +
                " AND InternalFeeDetailsId = " + aiInternalFeeDetailsId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }

        /// <summary>
        /// This is used to get the Internal Fee debit/credit details of selected student.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStudentId"></param>
        /// <returns></returns>
        public List<InternalFeeDebitDetails> GetInternalFeeDebitDetails(int aiSchoolId, int aiAcademicYearId, int aiStudentId, bool abIsNextYearFeePayment)
        {
            List<InternalFeeDebitDetails> lstInternalFeeDebitDetails = new List<InternalFeeDebitDetails>();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearFeePayment", abIsNextYearFeePayment, SqlDbType.Int);
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetInternalFeeDetails"))
                {
                    GenericClass<InternalFeeDebitDetails> oGenericClass = new GenericClass<InternalFeeDebitDetails>();
                    lstInternalFeeDebitDetails = oGenericClass.GetFilledObjectList(oSqlDataReader);
                }
            }
            return lstInternalFeeDebitDetails;
        }

        /// <summary>
        /// This is used to get the Internal Fee debit/credit details of selected student.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStudentId"></param>
        /// <returns></returns>
        public List<InternalFeeDebitDetails> GetInternalFeeDebitDetailsForOnlinePayment(int aiSchoolId, int aiAcademicYearId, int aiStudentId, bool abIsNextYearFeePayment)
        {
            List<InternalFeeDebitDetails> lstInternalFeeDebitDetails = new List<InternalFeeDebitDetails>();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearFeePayment", abIsNextYearFeePayment, SqlDbType.Int);
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetInternalFeeDetailsForOnlinePayment"))
                {
                    GenericClass<InternalFeeDebitDetails> oGenericClass = new GenericClass<InternalFeeDebitDetails>();
                    lstInternalFeeDebitDetails = oGenericClass.GetFilledObjectList(oSqlDataReader);
                }
            }
            return lstInternalFeeDebitDetails;
        }

        public static List<InternalFeeDetails> GetInternalFeeDetailsForPayment(int aiSchoolId, int aiAcademicYearId, int aiStudentId)
        {
            List<InternalFeeDetails> olstInternalFeeDetails = new List<InternalFeeDetails>();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetInternalFeeDetailsForPayment"))
                {
                    GenericClass<InternalFeeDetails> oGenericClass = new GenericClass<InternalFeeDetails>();
                    olstInternalFeeDetails = oGenericClass.GetFilledObjectList(oSqlDataReader);
                }
            }

            return olstInternalFeeDetails;
        }

        //public static DataTable GetReceiptNo(int aiSchoolId, int aiAcademicYearId)
        //{
        //    string sSelectStatement = "SELECT MAX(ReceiptNo) FROM InternalFeeDetails WHERE SchoolId=" + aiSchoolId +
        //        " AND" +
        //        " AcademicYearId=" + aiAcademicYearId;

        //    using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
        //        return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        //}

        public static DataSet GetRecieptDetails(int aiSchoolId, int aiReceiptNo, int aiInternalFeeDetailsId, int aiCurrAcadYerId, int aiAcademicYear, int aiStudentId, int aiDuplicateInternalFeeDetailsId, bool abIsNextYearPayment, int aiSerialNumber)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYear, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("CurrAcadYerId", aiCurrAcadYerId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ReceiptNo", aiReceiptNo, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InternalFeeDetailsId", aiInternalFeeDetailsId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Schoolwise_Student_Id", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("DuplicateInternalFeeDetailsId", aiDuplicateInternalFeeDetailsId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearPayment", abIsNextYearPayment, SqlDbType.Bit);
                oSQLServerDbUtility.AddParameter("SerialNumber", aiSerialNumber, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetInternalFeeReceipt");
            }
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("academic_Year_Id", aiAcademicYear, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetInternalFee");
            }
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear, int aiStandardID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("academic_Year_Id", aiAcademicYear, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardID", aiStandardID, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetInternalFee");
            }
        }

        public static DataTable GetInternalFee(int aiSchoolId, int aiAcademicYear, int aiStandardID, int aiDivisionID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("academic_Year_Id", aiAcademicYear, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardID", aiStandardID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("DivisionID", aiDivisionID, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetInternalFee");
            }
        }

        public bool IsDuplicateChequeNumber(int aiSchoolId, int aiAcademicYearId, string asChequeNumber, int aiStudentId, int aiBankId, bool abIsNextYearPayment)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ChequeNumber", asChequeNumber, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("BankId", aiBankId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearPayment", abIsNextYearPayment, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsDuplicate", false, SqlDbType.Bit, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsDuplicateChequeNumber");
                return oSqlParameter.Value.ToBool();
            }
        }

        public bool IsDuplicateTransactionNumber(int aiSchoolId, int aiAcademicYearId, string asTransactionNo, int aiStudentId, int aiBankId, bool abIsNextYearPayment, int aiElectronicTypeId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TxnNo", asTransactionNo, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("BankId", aiBankId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsNextYearPayment", (abIsNextYearPayment ? 1 : 0), SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ElectronicTypeId", aiElectronicTypeId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsDuplicate", false, SqlDbType.Bit, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsDuplicateTransactionNUmber");
                return oSqlParameter.Value.ToBool();
            }
        }
    }
}
