//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- PrePrimaryProgressSheetConfigDC
// Purpose          :- This class is used to manage PrePrimaryProgressSheetConfig details.
// Date Of creation :- 10/22/2008
// Author Name      :- 


using System;
using System.Data;
using System.Text;
using System.Data.SqlClient;
using Utility;
using ProgressReportEntities;
using StudentEntities;
using System.Collections.Generic;


namespace DataCommunicator
{
    public class PrePrimaryProgressSheetConfigDC
    {
        public struct PrePrimaryProgressSheetConfigStruct
        {

            public int miHeadingId;

            public string msHeadingText;

            public int miHeadingParentId;

            public string msIsDescription;

            public int miDescription_For_Test_Id;

            public int mistandardId;

            public int miAcademicYearId;

            public int mischoolId;

            public string msIsDeleted;

            public System.DateTime mdtInsertDate;

            public string msInsertedByid;

            public System.DateTime mdtUpdateDate;

            public string msUpdatedById;
        }

        public List<PrePrimaryStandards> lstPrePrimaryStandards = new List<PrePrimaryStandards>();
        public List<PrePrimaryModule> lstPrePrimaryModule = new List<PrePrimaryModule>();
        public List<PrePrimaryProgressReportSubjects> lstPrePrimarySubjects = new List<PrePrimaryProgressReportSubjects>();
        public PrePrimaryProgressReportSubSubjects moPrePrimaryProgressReportSubSubjectsEntity = null;

        public List<PrePrimaryConfiguredMonthDetails> lstPrePrimaryConfiguredMonthDetails = new List<PrePrimaryConfiguredMonthDetails>();
        public List<PrePrimaryRemark> lstPrePrimaryRemarkConfig = new List<PrePrimaryRemark>();
        public List<PrePrimaryProgressReportSubSubjects> lstSubSubjectsWithoutSubjects = new List<PrePrimaryProgressReportSubSubjects>();
        public List<PrePrimaryProgressReportSubSubjects> lstSubSubjectsWithSubjects = new List<PrePrimaryProgressReportSubSubjects>();
        public List<PrePrimaryStudentsExamResult> lstPrePrimaryStudentsExamResultWithoutSubjects = new List<PrePrimaryStudentsExamResult>();
        public List<PrePrimaryStudentsExamResult> lstPrePrimaryStudentsExamResultWithSubjects = new List<PrePrimaryStudentsExamResult>();
        public List<PrePrimaryStudentsExamComment> lstPrePrimaryStudentsExamComment = new List<PrePrimaryStudentsExamComment>();

        public StudentInfo studentDetails = new StudentInfo();

        private PrePrimaryProgressSheetConfigStruct moPrePrimaryProgressSheetConfigStruct;

        #region Properties

        public virtual PrePrimaryProgressReportSubSubjects PrePrimaryProgressReportSubSubjectsEntity
        {
            get
            {
                return moPrePrimaryProgressReportSubSubjectsEntity;
            }
            set
            {
                moPrePrimaryProgressReportSubSubjectsEntity = value;
            }
        }

        #endregion

        #region private

        // This function is used to fetch the PrePrimaryProgressSheetConfig Details
        private string FetchPrePrimaryProgressSheetConfigDetailsFromDatabase(int miHeadingId)
        {
            string sSelectStatement = " SELECT  " +
            "Heading_Id" +
            ",Heading_Text" +
            ",Heading_Parent_Id" +
            ",Is_Description" +
            ",Description_For_Test_Id" +
            ",standard_Id" +
            ",Academic_Year_Id" +
            ",school_Id" +
            ",Is_Deleted" +
            ",Insert_Date" +
            ",Inserted_By_id" +
            ",Update_Date" +
            ",Updated_By_Id" +
            " FROM PrePrimary_ProgressSheet_Config" +
            " WHERE Heading_Id=" + miHeadingId;
            return sSelectStatement;
        }

        // This function is used to load the PrePrimaryProgressSheetConfig Details
        private void LoadPrePrimaryProgressSheetConfigDetails(int miHeadingId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchPrePrimaryProgressSheetConfigDetailsFromDatabase(miHeadingId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    if (oDR != null)
                    {
                        while (oDR.Read())
                        {
                            if (oDR["Heading_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.miHeadingId = Convert.ToInt32(oDR["Heading_Id"]);
                            if (oDR["Heading_Text"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.msHeadingText = Convert.ToString(oDR["Heading_Text"]);
                            if (oDR["Heading_Parent_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.miHeadingParentId = Convert.ToInt32(oDR["Heading_Parent_Id"]);
                            if (oDR["Is_Description"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.msIsDescription = Convert.ToString(oDR["Is_Description"]);
                            if (oDR["Description_For_Test_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.miDescription_For_Test_Id = Convert.ToInt32(oDR["Description_For_Test_Id"]);
                            if (oDR["standard_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.mistandardId = Convert.ToInt32(oDR["standard_Id"]);
                            if (oDR["Academic_Year_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.miAcademicYearId = Convert.ToInt32(oDR["Academic_Year_Id"]);
                            if (oDR["school_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.mischoolId = Convert.ToInt32(oDR["school_Id"]);
                            if (oDR["Is_Deleted"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.msIsDeleted = Convert.ToString(oDR["Is_Deleted"]);
                            if (oDR["Insert_Date"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.mdtInsertDate = Convert.ToDateTime(oDR["Insert_Date"]);
                            if (oDR["Inserted_By_id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.msInsertedByid = Convert.ToString(oDR["Inserted_By_id"]);
                            if (oDR["Update_Date"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.mdtUpdateDate = Convert.ToDateTime(oDR["Update_Date"]);
                            if (oDR["Updated_By_Id"] != DBNull.Value)
                                moPrePrimaryProgressSheetConfigStruct.msUpdatedById = Convert.ToString(oDR["Updated_By_Id"]);
                        }
                    }
                }
            }
        }

        #endregion private

        #region public

        public PrePrimaryProgressSheetConfigDC()
        {
        }

        public PrePrimaryProgressSheetConfigDC(int miHeadingId)
        {
            LoadPrePrimaryProgressSheetConfigDetails(miHeadingId);
        }

        public virtual PrePrimaryProgressSheetConfigStruct PrePrimaryProgressSheetConfigStructDetails
        {
            get
            {
                return moPrePrimaryProgressSheetConfigStruct;
            }
            set
            {
                moPrePrimaryProgressSheetConfigStruct = value;
            }
        }

        // This function is used to insert the PrePrimaryProgressSheetConfig Details
        public virtual int InsertPrePrimaryProgressSheetConfig()
        {
            string sInsertStatement = "INSERT INTO PrePrimary_ProgressSheet_Config(" +
            "Heading_Text" +
            ",Heading_Parent_Id" +
            ",Is_Description" +
            ",Description_For_Test_Id" +
            ",standard_Id" +
            ",Academic_Year_Id" +
            ",school_Id" +
            ",Inserted_By_id" +
            ")VALUES(" +
            "N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msHeadingText, true) + "' " +
             " , " + moPrePrimaryProgressSheetConfigStruct.miHeadingParentId +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msIsDescription, true) + "' " +
             " , " + moPrePrimaryProgressSheetConfigStruct.miDescription_For_Test_Id +
             " , " + moPrePrimaryProgressSheetConfigStruct.mistandardId +
             " , " + moPrePrimaryProgressSheetConfigStruct.miAcademicYearId +
             " , " + moPrePrimaryProgressSheetConfigStruct.mischoolId +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msInsertedByid, true) + "' " +
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }

        // This function is used to insert the PrePrimaryProgressSheetConfig Details
        public void InsertPrePrimaryProgressSheetConfig(string asXmlNotApplicableExam)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
				oSQLServerDbUtility.AddParameter("Heading_Text", moPrePrimaryProgressSheetConfigStruct.msHeadingText, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("Heading_Parent_Id", moPrePrimaryProgressSheetConfigStruct.miHeadingParentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Is_Description", StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msIsDescription, true), SqlDbType.Char);
                oSQLServerDbUtility.AddParameter("Description_For_Test_Id", moPrePrimaryProgressSheetConfigStruct.miDescription_For_Test_Id, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("standard_Id", moPrePrimaryProgressSheetConfigStruct.mistandardId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moPrePrimaryProgressSheetConfigStruct.miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("school_Id", moPrePrimaryProgressSheetConfigStruct.mischoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Inserted_By_id", moPrePrimaryProgressSheetConfigStruct.msInsertedByid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("NotApplicableExamXML", asXmlNotApplicableExam, SqlDbType.Xml);

                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_InsertPrePrimaryProgressSheetConfig");
            }            
        }


        public bool isAlreadyExists()
        {
            string sSelectStatement = " SELECT " +
                   " count(*) " +
               " FROM " +
                   " PrePrimary_ProgressSheet_Config " +
               " WHERE " +
                   " Heading_Text =N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msHeadingText, true) + "' " +
                   " AND NOT Heading_Id =" + moPrePrimaryProgressSheetConfigStruct.miHeadingId +
                   " AND Heading_Parent_Id=" + moPrePrimaryProgressSheetConfigStruct.miHeadingParentId +
                   " AND standard_Id = " + moPrePrimaryProgressSheetConfigStruct.mistandardId +
                   " AND Academic_Year_Id=" + moPrePrimaryProgressSheetConfigStruct.miAcademicYearId +
                   " AND school_Id=" + moPrePrimaryProgressSheetConfigStruct.mischoolId +
                   " AND Is_Deleted = N'" + Constants.C_NO + "'";
            // Perform the stetement on server.
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }

        // This function is used to update the PrePrimaryProgressSheetConfig Details
        public virtual void UpdatePrePrimaryProgressSheetConfig()
        {
            string sUpdateStatement = "UPDATE PrePrimary_ProgressSheet_Config SET " +
            "Heading_Text= N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msHeadingText, true) + "' " +
            ",Heading_Parent_Id= " + moPrePrimaryProgressSheetConfigStruct.miHeadingParentId +
            ",Is_Description= N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msIsDescription, true) + "' " +
            ",Description_For_Test_Id= N'" + moPrePrimaryProgressSheetConfigStruct.miDescription_For_Test_Id + "' " +
            ",Update_Date= N'" + moPrePrimaryProgressSheetConfigStruct.mdtUpdateDate + "' " +
            ",Updated_By_Id= N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msUpdatedById, true) + "' " +
            "" +
            " WHERE Heading_Id=" + moPrePrimaryProgressSheetConfigStruct.miHeadingId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        // This function is used to insert the PrePrimaryProgressSheetConfig Details
        public void UpdatePrePrimaryProgressSheetConfig(string asXmlNotApplicableExam)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
				oSQLServerDbUtility.AddParameter("Heading_Text", moPrePrimaryProgressSheetConfigStruct.msHeadingText, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("Heading_Parent_Id", moPrePrimaryProgressSheetConfigStruct.miHeadingParentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Is_Description", StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressSheetConfigStruct.msIsDescription, true), SqlDbType.Char);
                oSQLServerDbUtility.AddParameter("Description_For_Test_Id", moPrePrimaryProgressSheetConfigStruct.miDescription_For_Test_Id, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Updated_By_Id", moPrePrimaryProgressSheetConfigStruct.msUpdatedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Heading_Id", moPrePrimaryProgressSheetConfigStruct.miHeadingId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("NotApplicableExamXML", asXmlNotApplicableExam, SqlDbType.Xml);

                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_UpdatePrePrimaryProgressSheetConfig");
            }
        }

        // This function is used to delete the PrePrimaryProgressSheetConfig Details
        public virtual void DeletePrePrimaryProgressSheetConfig()
        {
            StringBuilder sDeleteStatement = new StringBuilder();
            sDeleteStatement.Append("DELETE PrePrimary_ProgressSheet_Config WHERE Heading_Id=N'" + moPrePrimaryProgressSheetConfigStruct.miHeadingId + "' OR Heading_Parent_Id =N'" + moPrePrimaryProgressSheetConfigStruct.miHeadingId + "'");
            sDeleteStatement.Append("; DELETE ExamwiseNotApplicable_PrePrimary_ProgressSheet_Config WHERE Heading_Id = N'" + moPrePrimaryProgressSheetConfigStruct.miHeadingId + "'");
            sDeleteStatement.Append("; DELETE ExamwiseNotApplicable_PrePrimary_ProgressSheet_Config " +
                                                                   " FROM         ExamwiseNotApplicable_PrePrimary_ProgressSheet_Config INNER JOIN " +
                                                                   " PrePrimary_ProgressSheet_Config ON " +
                                                                   " ExamwiseNotApplicable_PrePrimary_ProgressSheet_Config.Heading_Id = PrePrimary_ProgressSheet_Config.Heading_Parent_Id " +
                                                                   " WHERE ExamwiseNotApplicable_PrePrimary_ProgressSheet_Config.Heading_Id = N'" + moPrePrimaryProgressSheetConfigStruct.miHeadingId + "'");
                  
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement.ToString());
        }

        // This function is used to fetch the PrePrimaryProgressSheetConfig Details
        public DataTable FetchPrePrimaryProgressSheetConfigDetails(int aiParentHeaderId, int aiStandardID, int aiAcademicYearId, int aiSchoolId)
        {
            string sSelectStatement = " SELECT  " +
                                    "Heading_Id" +
                                    ",Heading_Text" +
                                    ",Heading_Parent_Id" +
                                    ",Is_Description" +
                                    ",standard_Id" +
                                    ",Academic_Year_Id" +
                                    ",school_Id" +
                                    ",Is_Deleted" +
                                    ",Insert_Date" +
                                    ",Inserted_By_id" +
                                    ",Update_Date" +
                                    ",Updated_By_Id" +
                                    " FROM PrePrimary_ProgressSheet_Config" +
                                    " WHERE " +
                                        " school_Id=" + aiSchoolId +
                                        " AND Academic_Year_Id=" + aiAcademicYearId +
                                        " AND standard_Id=" + aiStandardID +
                                        " AND Heading_Parent_Id=" + aiParentHeaderId +
                                        " AND Is_Deleted=N'" + Constants.C_NO.ToString() + "'";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }


        public DataTable IsPrePrimaryConfigured(int miStdDivId, int iSchoolID, int iAcademicYrID)
        {
            string sSelectStatement = "SELECT TOP 1 PrePrimary_ProgressSheet_Config.Heading_Id " +
                                    " FROM PrePrimary_ProgressSheet_Config INNER JOIN " +
                                    " SchoolWise_Standard_Division_Master ON PrePrimary_ProgressSheet_Config.standard_Id = SchoolWise_Standard_Division_Master.Standard_Id AND " +
                                    " PrePrimary_ProgressSheet_Config.Academic_Year_Id = SchoolWise_Standard_Division_Master.academic_year_id AND " +
                                    " PrePrimary_ProgressSheet_Config.school_Id = SchoolWise_Standard_Division_Master.School_Id " +
                                    " WHERE (SchoolWise_Standard_Division_Master.SchoolWise_Standard_Division_Id = " + miStdDivId + " ) " +
                                    " AND (SchoolWise_Standard_Division_Master.academic_year_id =  " + iAcademicYrID + " )" +
                                    " AND (SchoolWise_Standard_Division_Master.School_Id =  " + iSchoolID + " )";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }


        public DataSet GetPrePrimaryProgressSheetDetails(int iSchoolID, int iAcademicYrID, int iTestId, int iStudentId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", iSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", iAcademicYrID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", iTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", iStudentId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetPrePrimaryProgressSheetDetails");
            }
        }

		public DataSet GetAllPrePrimaryProgressSheetDetails(int iSchoolID, int iAcademicYrID, int aiStdDivId, int aiTestId, int iStudentId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", iSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", iAcademicYrID, SqlDbType.Int);
				oSQLServerDbUtility.AddParameter("StdDivId", aiStdDivId, SqlDbType.Int);
                if (aiTestId != 0)
                    oSQLServerDbUtility.AddParameter("TestId", aiTestId, SqlDbType.Int);
                if (iStudentId != 0)
                    oSQLServerDbUtility.AddParameter("StudentId", iStudentId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetAllPrePrimaryProgressSheetDetails");
            }
        }

        // This function is used to insert the SchoolWiseStanderedDivisionTestMaster Details
        public virtual int SubmitPrePrimaryTest(int miStdDivId, int iSchoolID, int miTestiD, int iAcademicYrID, int iUpdateById)
        {
            string sInsertStatement = "INSERT INTO PrePrimaryTestSubmit_Master(" +
            " School_id" +
            ", Standerd_division_Id" +
            ", Academic_Year_ID" +
            ", SchoolWise_Test_Id" +
            ", Is_Submitted" +
            ", Inserted_By_id" +
            ", Updated_By_Id" +
            ")VALUES(" +
            " " + iSchoolID +
             " , " + miStdDivId +
             " , " + iAcademicYrID +
             " , " + miTestiD +
             " , 'Y'" +
             " , " + iUpdateById +
             " , " + iUpdateById +
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }



        public DataTable GetIncompleteProgressRollNos(int aiSchoolId, int aiAcademicYearId, int aiTeacherId, int aiTestId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("prm_iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("prm_iAcademicYrId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TeacherId", aiTeacherId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", aiTestId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_getPrePrimaryProgressSheetStatusRollNo");
            }
        }


        public void CopyConfiguration(int iSrcStandard, int iDestStandard)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("prm_iSrcStandard", iSrcStandard, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("prm_iDestStandard", iDestStandard, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_CopyPrePrimaryProgressConfiguration");
            }
        }
        //" [Photo_file_PathImage] = ''" +
        public void GetPrePrimaryProgressReportSubjects(int aiSchoolId, int aiAcademicYrId, int aiModuleID)
        {
            string sSelectStatement = "SELECT     PrePrimarySubjectId, PrePrimarySubjectName " +
                                      " FROM       PrePrimaryProgressReportSubjectConfigList " +
                                      " WHERE	   ModuleId = " + aiModuleID +
                                      " AND School_Id = " + aiSchoolId +
                                      " AND Academic_Year_Id = " + aiAcademicYrId +
                                      " AND Is_Deleted =N'" + Constants.C_NO + "'" +
                                      " ORDER BY SortOrder";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    PrePrimaryProgressReportSubjects oPrePrimaryProgressReportSubjects;
                    while (oSqlDataReader.Read())
                    {
                        oPrePrimaryProgressReportSubjects = new PrePrimaryProgressReportSubjects
                        {
                            PrePrimaryProgressReportSubjectID = Convert.ToInt32(oSqlDataReader["PrePrimarySubjectId"]),
                            PrePrimaryProgressReportSubjectName = Convert.ToString(oSqlDataReader["PrePrimarySubjectName"]),

                        };
                        lstPrePrimarySubjects.Add(oPrePrimaryProgressReportSubjects);
                    }
                }
            }    
        }

        public static List<PrePrimaryProgressReportSubSubjects> GetAllConfiguredPrePrimarySubSubjects(int aiSchoolId, int aiAcademicYrID, int aiStandardId, string sortExpression, int iEndIndex, int iStartIndex)
        {
            List<PrePrimaryProgressReportSubSubjects> olstclsSubSubjects = new List<PrePrimaryProgressReportSubSubjects>();
            string sSortExpression = "";
            if (sortExpression != "")
                sSortExpression = " ORDER BY " + sortExpression;
            else
                sSortExpression = " ORDER BY ModuleName";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYrId", aiAcademicYrID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StartIndex", iStartIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EndIndex", iEndIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SortExp", sSortExpression, SqlDbType.NVarChar);

                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetSubSubjectsForStandards"))
                {
                    PrePrimaryProgressReportSubSubjects oPrePrimaryProgressReportSubSubjects;
                    while (oSqlDataReader.Read())
                    {
                        oPrePrimaryProgressReportSubSubjects = new PrePrimaryProgressReportSubSubjects
                        {
                            SubSubjectName = Convert.ToString(oSqlDataReader["SubSubjectName"]),
                            SubjectName = Convert.ToString(oSqlDataReader["SubjectName"]),
                            ModuleName = Convert.ToString(oSqlDataReader["ModuleName"]),
                            SubSubjectID = Convert.ToInt32(oSqlDataReader["SubSubjectID"]),
                            SubjectID = oSqlDataReader["SubjectID"] != System.DBNull.Value ? Convert.ToInt32(oSqlDataReader["SubjectID"]) : 0,
                            ModuleID = Convert.ToInt32(oSqlDataReader["ModuleID"]),
                        };
                        olstclsSubSubjects.Add(oPrePrimaryProgressReportSubSubjects);
                    }
                }
            }
            return olstclsSubSubjects;         
            
        }

        public static int CountAllConfiguredPrePrimarySubSubjects(int aiSchoolId, int aiAcademicYrID, int aiStandardId)
        {
            SqlParameter oSqlParameter = new SqlParameter();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYrId", aiAcademicYrID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetCntSubSubjectsForStandards");
            }
            return Convert.ToInt32(oSqlParameter.Value);
        }

        public void GetPrePrimaryStandardsAndModuleName(int aiSchoolId, int aiAcademicYr)
        {
            string sSelectStatement = " SELECT  " +
                                 " school_id " +
                                 " , original_standard_id " +
                                 " , standard_id " +
                                 " , standard_name " +
                             " FROM " +
                                  " standard_master " +
                             " WHERE " +
                                  " is_deleted = N'" + Constants.C_NO + "'" +
                                  " AND is_preprimary = N'" + Constants.C_YES + "'" +
                                  " AND school_id = " + aiSchoolId +
                                  " AND academic_year_id = " + aiAcademicYr +
                                  " AND standard_id IN (SELECT Standard_Id " +
                                                        "FROM PrePrimaryStandardForNewProgressReport " +
                                                        " WHERE School_id = " + aiSchoolId +
                                                        " AND Academic_Year_Id = " + aiAcademicYr +
                                                        " AND Is_Deleted=0)" +
                              " ORDER BY " +
                                   " original_standard_id";

            sSelectStatement += " Select ExamModuleId,ExamModuleName FROM PrePrimaryProgressReportModuleConfigList " +
                                " where is_deleted = 0  AND School_Id = " + aiSchoolId +
                                  " AND Academic_Year_Id = " + aiAcademicYr;

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    FillPrePrimaryStandardsEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillPrePrimaryModuleEntityList(oSqlDataReader);
                }
            }
        }
        public void GetPrePrimaryModuleName(int aiSchoolId, int aiAcademicYr)
        {

            string sSelectStatement = " Select ExamModuleId,ExamModuleName FROM PrePrimaryProgressReportModuleConfigList " +
                                " where is_deleted = 0  AND School_Id = " + aiSchoolId +
                                  " AND Academic_Year_Id = " + aiAcademicYr;

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                using(SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                FillPrePrimaryModuleEntityList(oSqlDataReader);
            }
        }

        private void FillPrePrimaryStandardsEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryStandards oPrePrimaryStandards;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryStandards = new PrePrimaryStandards
                {
                    StandardID = Convert.ToInt32(oSqlDataReader["standard_id"]),
                    StandardName = Convert.ToString(oSqlDataReader["standard_name"]),

                };
                lstPrePrimaryStandards.Add(oPrePrimaryStandards);
            }         
        }

        private void FillPrePrimaryModuleEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryModule oPrePrimaryModule;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryModule = new PrePrimaryModule
                {
                    ModuleID = Convert.ToInt32(oSqlDataReader["ExamModuleId"]),
                    ModuleName = Convert.ToString(oSqlDataReader["ExamModuleName"]),

                };
                lstPrePrimaryModule.Add(oPrePrimaryModule);
            }
        }

        public void UpdateSubSubject(int aiSubSubjectId)
        {
            string sUpdateStatement = " UPDATE PrePrimaryProgressReportSubSubjects SET " +
                                      " PrePrimaryProgressReportSubSubjectName = N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressReportSubSubjectsEntity.SubSubjectName, false) + "' " +
                                      " , ExamModuleId = " + moPrePrimaryProgressReportSubSubjectsEntity.ModuleID +
                                      " , PrePrimaryProgressReportSubjectId = " + moPrePrimaryProgressReportSubSubjectsEntity.SubjectID +
                                      " , Standard_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                      " , School_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
                                      " , Academic_Year_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId +
                                      " , UpdatedById = " + moPrePrimaryProgressReportSubSubjectsEntity.UpdatedById +
                                      " , UpdatedDate = dbo.GetLocalDate(DEFAULT) " +
                                      " WHERE PrePrimaryProgressReportSubSubjectId = " + aiSubSubjectId.ToString();
            
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        public void SaveSubSubject()
        {
            string sInsertStatement = " INSERT INTO PrePrimaryProgressReportSubSubjects " +
                                      " (PrePrimaryProgressReportSubSubjectName, ExamModuleId, PrePrimaryProgressReportSubjectId, Standard_Id, School_Id, " +
                                      " Academic_Year_Id, InsertedDate,SortOrder, InsertedById) VALUES " +
                                      "( N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressReportSubSubjectsEntity.SubSubjectName, false) + " ' " +
                                          ", " + moPrePrimaryProgressReportSubSubjectsEntity.ModuleID +
                                          ", " + moPrePrimaryProgressReportSubSubjectsEntity.SubjectID +
                                           ", " + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                           ", " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
                                           ", " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId +
                                           ", dbo.GetLocalDate(DEFAULT) " +
                                           ", ISNULL((SELECT MAX(SortOrder)+1 FROM PrePrimaryProgressReportSubSubjects WHERE ExamModuleId = " + moPrePrimaryProgressReportSubSubjectsEntity.ModuleID +
                                                                                                                       " AND PrePrimaryProgressReportSubjectId = " + moPrePrimaryProgressReportSubSubjectsEntity.SubjectID +
                                                                                                                       " AND Standard_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                                                                                                       " AND School_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
                                                                                                                       " AND Academic_Year_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId + "),0) " +
                                            ", " + moPrePrimaryProgressReportSubSubjectsEntity.InsertedById +                                                                            
                                           " ) ";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }

        public static void CopyPrePrimaryConfiguration(int aiSchoolId, int aiAcademicYearId, int aiSourceStdId, int aiTargetStdId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SrcStandard", aiSourceStdId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TargetSubId", aiTargetStdId, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_CopyPrePrimaryConfiguration");
            }
        }

        public static void DeleteSubSubject(int aiSubSubjectId)
        {
            string sDeleteStatement = " UPDATE  PrePrimaryProgressReportSubSubjects SET " +
                                      " Is_Deleted = N'" + Constants.C_YES + "'" +
                                      " WHERE PrePrimaryProgressReportSubSubjectId = " + aiSubSubjectId.ToString();

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);                                      
        }

        public bool IsDuplicateSubSubjectName(int aiSubID)
        {
            string sSelectStatement = " SELECT COUNT(*) FROM PrePrimaryProgressReportSubSubjects " +
                                      " WHERE PrePrimaryProgressReportSubSubjectName = N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressReportSubSubjectsEntity.SubSubjectName, false) + " ' "  +
                                      " AND ExamModuleId = " + moPrePrimaryProgressReportSubSubjectsEntity.ModuleID +
                                      " AND PrePrimaryProgressReportSubjectId = " + moPrePrimaryProgressReportSubSubjectsEntity.SubjectID +
                                      " AND Standard_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                      " AND School_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
                                      " AND Academic_Year_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId +
                                      " AND Is_Deleted=N'" + Constants.C_NO + "'" +
                                      " AND PrePrimaryProgressReportSubSubjectId <> " + aiSubID.ToString();
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;            
        }

        public bool IsDuplicateSubSubjectName()
        {
            string sSelectStatement = " SELECT COUNT(*) FROM PrePrimaryProgressReportSubSubjects " +
                                      " WHERE PrePrimaryProgressReportSubSubjectName = N'" + StringUtility.ReplaceSingleQuoteInString(moPrePrimaryProgressReportSubSubjectsEntity.SubSubjectName, false) + " ' " +
                                      " AND ExamModuleId = " + moPrePrimaryProgressReportSubSubjectsEntity.ModuleID +
                                      " AND PrePrimaryProgressReportSubjectId = " + moPrePrimaryProgressReportSubSubjectsEntity.SubjectID +
                                      " AND Standard_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                      " AND School_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
                                      " AND Academic_Year_Id = " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId +
                                      " AND Is_Deleted=N'" + Constants.C_NO + "'";
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }

        public bool GetCinfigStudCntForStd()
        {
            string sSelectStatement="SELECT COUNT (YearWise_Student_Id) FROM YearWise_Student_Details"+
                                            " WHERE Standard_Id=" + moPrePrimaryProgressReportSubSubjectsEntity.StandardID +
                                            " AND YearWise_Student_Id IN (SELECT StudentId "+
											                               " FROM PrePrimaryExamResult "+
												                           " WHERE PrePrimaryExamResult.academic_year_id= " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId+
														                            " AND PrePrimaryExamResult.SchoolId= " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId +
												                                    " AND PrePrimaryExamResult.Is_Deleted='" + Constants.C_NO + "') AND "+
                                    "Academic_Year_ID= " + moPrePrimaryProgressReportSubSubjectsEntity.AcademicYearId+
                                    " AND School_Id= " + moPrePrimaryProgressReportSubSubjectsEntity.SchoolId;

            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }

        public static List<PrePrimaryProgressReportSubSubjects> GetConfiguredSubSubject(int aiSchoolId, int aiAcademicYearId, int aiStandardId)
        {
            List<PrePrimaryProgressReportSubSubjects> olstclsSubSubjects = new List<PrePrimaryProgressReportSubSubjects>();

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);

                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetSavedSubSubjectsForStandards"))
                {
                    PrePrimaryProgressReportSubSubjects oPrePrimaryProgressReportSubSubjects;
                    while (oSqlDataReader.Read())
                    {
                        oPrePrimaryProgressReportSubSubjects = new PrePrimaryProgressReportSubSubjects
                        {
                            SubSubjectName = Convert.ToString(oSqlDataReader["SubSubject"]),
                            SubSubjectID = Convert.ToInt32(oSqlDataReader["SubSubjectID"])
                        };
                        olstclsSubSubjects.Add(oPrePrimaryProgressReportSubSubjects);
                    }
                }
            }
            return olstclsSubSubjects;

        }

        public static void UpdateExamSortOrder(string asSubSubjectOrderXML)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {

                oSQLServerDbUtility.AddParameter("SubSubjectOrderXML", asSubSubjectOrderXML, SqlDbType.Xml);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_UpdateSubSubjectsSorOrder");
            }
        }



        public bool IsDependent(int aiSubSubjectId, int aiAcademicYearId, int aiSchoolId)
        {
            string sSelectStatement = " SELECT COUNT(*) FROM PrePrimaryExamResult " +
                                      " WHERE  PrePrimaryProgressReportSubSubjectId = " + aiSubSubjectId +
                                      " AND SchoolId = " + aiSchoolId +
                                      " AND academic_year_id = " + aiAcademicYearId +
                                      " AND Is_Deleted=N'" + Constants.C_NO + "'";
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }
        public static List<PrePrimaryProgressReportSubjects> GetConfiguredSubject(int aiSchoolId, int aiAcademicYearId)
        {
            List<PrePrimaryProgressReportSubjects> olstclsSubjects = new List<PrePrimaryProgressReportSubjects>();

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);

                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetSavedSubjectsForStandards"))
                {
                    PrePrimaryProgressReportSubjects oPrePrimaryProgressReportSubjects;
                    while (oSqlDataReader.Read())
                    {
                        oPrePrimaryProgressReportSubjects = new PrePrimaryProgressReportSubjects
                        {
                            PrePrimaryProgressReportSubjectName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportSubjectName"]),
                            PrePrimaryProgressReportSubjectID = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportSubjectID"])
                        };
                        olstclsSubjects.Add(oPrePrimaryProgressReportSubjects);
                    }
                }
            }
            return olstclsSubjects;

        }

        public static void UpdateSubjectSortOrder(string sSubjectOrderXML)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SubjectOrderXML", sSubjectOrderXML, SqlDbType.Xml);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_UpdateSubjectsSorOrder");

            }
        }

        public void GetPrePrimaryProgressSheetDetailsOfStudent(int aiSchoolId, int aiAcademicYearId, int aiStudentId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYrId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);

                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetAllPrePrimaryProgressReportDetailsOfStudent"))
                {
                    FillMonthConfigurationEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillRemarksEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillSubSubjectsWithoutSubjectsEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillSubSubjectsWithSubjectsEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillStudentsExamResultWithSubjectsEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillStudentsExamResultWithOutSubjectsEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillPrePrimaryModuleEntityList(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillStudentEntity(oSqlDataReader);
                    if (oSqlDataReader.NextResult())
                        FillCommentsEntity(oSqlDataReader);

                }
            }
        }

        public static void SaveProgressDetailsOfStudent(int aiStudentId, int aiAcademicYearId, int aiSchoolId, int aiInsertedById, string asRemarksForStudent, string asMonths, string asCommentsForStudent, bool abIsStudentWiseProgressReport)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYrId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("RemarksForStudent", asRemarksForStudent, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("CommentsForStudent", asCommentsForStudent, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("IsStudentWiseProgressReport", abIsStudentWiseProgressReport, SqlDbType.Bit);
                oSQLServerDbUtility.AddParameter("Months", asMonths, SqlDbType.NVarChar);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_InsertPrePrimaryProgressReportDetailsForStudent");
            }
        }

        private void FillSubSubjectsWithoutSubjectsEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryProgressReportSubSubjects oPrePrimaryProgressReportSubSubjects;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryProgressReportSubSubjects = new PrePrimaryProgressReportSubSubjects
                {
                    SubSubjectName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportSubSubjectName"]),
                    ModuleName = Convert.ToString(oSqlDataReader["ExamModuleName"]),
                    SubSubjectID = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportSubSubjectId"]),
                    ModuleID = Convert.ToInt32(oSqlDataReader["ExamModuleId"]),
                };
                lstSubSubjectsWithoutSubjects.Add(oPrePrimaryProgressReportSubSubjects);
            }
        }

        private void FillStudentsExamResultWithSubjectsEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryStudentsExamResult oPrePrimaryStudentsExamResult;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryStudentsExamResult = new PrePrimaryStudentsExamResult
                {
                    PrePrimaryProgressReportSubSubjectName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportSubSubjectName"]),
                    ExamModuleName = Convert.ToString(oSqlDataReader["ExamModuleName"]),
                    //PrePrimarySubjectName = Convert.ToString(oSqlDataReader["PrePrimarySubjectName"]),
                    PrePrimaryProgressReportSubSubjectId = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportSubSubjectId"]),
                    ExamModuleId = Convert.ToInt32(oSqlDataReader["ExamModuleId"]),
                    PrePrimarySubjectId = Convert.ToInt32(oSqlDataReader["PrePrimarySubjectId"]),
                    PreprimaryExamConfigurationId = Convert.ToInt32(oSqlDataReader["PreprimaryExamConfigurationId"]),
                    Is_SubjectApplicable = Convert.ToBoolean(oSqlDataReader["Is_SubjectApplicable"]),
                    PrePrimaryRemarkId = Convert.ToInt32(oSqlDataReader["PrePrimaryRemarkId"]),
                };
                lstPrePrimaryStudentsExamResultWithSubjects.Add(oPrePrimaryStudentsExamResult);
            }
        }

        private void FillStudentsExamResultWithOutSubjectsEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryStudentsExamResult oPrePrimaryStudentsExamResult;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryStudentsExamResult = new PrePrimaryStudentsExamResult
                {
                    PrePrimaryProgressReportSubSubjectName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportSubSubjectName"]),
                    ExamModuleName = Convert.ToString(oSqlDataReader["ExamModuleName"]),                    
                    PrePrimaryProgressReportSubSubjectId = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportSubSubjectId"]),
                    ExamModuleId = Convert.ToInt32(oSqlDataReader["ExamModuleId"]),                    
                    PreprimaryExamConfigurationId = Convert.ToInt32(oSqlDataReader["PreprimaryExamConfigurationId"]),
                    Is_SubjectApplicable = Convert.ToBoolean(oSqlDataReader["Is_SubjectApplicable"]),
                    PrePrimaryRemarkId = Convert.ToInt32(oSqlDataReader["PrePrimaryRemarkId"]),
                };
                lstPrePrimaryStudentsExamResultWithoutSubjects.Add(oPrePrimaryStudentsExamResult);
            }
        }

        private void FillSubSubjectsWithSubjectsEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryProgressReportSubSubjects oPrePrimaryProgressReportSubSubjects;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryProgressReportSubSubjects = new PrePrimaryProgressReportSubSubjects
                {
                    SubSubjectName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportSubSubjectName"]),
                    ModuleName = Convert.ToString(oSqlDataReader["ExamModuleName"]),
                    SubSubjectID = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportSubSubjectId"]),
                    ModuleID = Convert.ToInt32(oSqlDataReader["ExamModuleId"]),
                    SubjectID = oSqlDataReader["PrePrimarySubjectId"] != System.DBNull.Value ? Convert.ToInt32(oSqlDataReader["PrePrimarySubjectId"]) : 0,
                    SubjectName = Convert.ToString(oSqlDataReader["PrePrimarySubjectName"]),
                };
                lstSubSubjectsWithSubjects.Add(oPrePrimaryProgressReportSubSubjects);
            }
        }      

        private void FillRemarksEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryRemark oPrePrimaryRemarkConfig;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryRemarkConfig = new PrePrimaryRemark
                {
                    PrePrimaryProgressReportRemarkId = Convert.ToInt32(oSqlDataReader["PrePrimaryProgressReportRemarkId"]),
                    PrePrimaryProgressReportRemarkName = Convert.ToString(oSqlDataReader["PrePrimaryProgressReportRemarkName"]),
                };
                lstPrePrimaryRemarkConfig.Add(oPrePrimaryRemarkConfig);
            }
        }

        private void FillMonthConfigurationEntityList(SqlDataReader oSqlDataReader)
        {
            PrePrimaryConfiguredMonthDetails oPrePrimaryConfiguredMonthDetails;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryConfiguredMonthDetails = new PrePrimaryConfiguredMonthDetails
                {
                    MonthAbbreviation = Convert.ToString(oSqlDataReader["MonthAbbreviation"]),
                    PreprimaryExamConfigurationId = Convert.ToInt32(oSqlDataReader["PreprimaryExamConfigurationId"]),
                    PreprimaryProgressReportMonthID = Convert.ToInt32(oSqlDataReader["PreprimaryProgressReportMonthID"]),
                    IsPublished = Convert.ToBoolean(oSqlDataReader["IsPublished"]),
                    IsSubmitted = Convert.ToBoolean(oSqlDataReader["IsSubmitted"]),
                    PreprimaryStudentWiseTestPublishStatus = Convert.ToString(oSqlDataReader["PreprimaryStudentWiseTestPublishStatus"]),
                };
                lstPrePrimaryConfiguredMonthDetails.Add(oPrePrimaryConfiguredMonthDetails);
            }
        }

        private void FillStudentEntity(SqlDataReader oSqlDataReader)
        {
            while (oSqlDataReader.Read())
            {
                studentDetails = new StudentInfo
                {
                    StudentName = Convert.ToString(oSqlDataReader["StudentName"]),
                    ClassName = Convert.ToString(oSqlDataReader["Class"]),
                    RollNo = Convert.ToInt32(oSqlDataReader["Roll_No"]),
                    IsNewStudent = Convert.ToInt32(oSqlDataReader["Is_New_Student"]),
                    RegNo = Convert.ToString(oSqlDataReader["Enrolment_Number"]),
                    Academic_Year = Convert.ToString(oSqlDataReader["Academic_Year"]),
                    School_Name = Convert.ToString(oSqlDataReader["School_Name"]),
                    School_Orgn_Name = Convert.ToString(oSqlDataReader["School_Orgn_Name"]),
                    First_Term_PresentDay = Convert.ToInt32(oSqlDataReader["Term1PresentDay"]),
                    First_Term_Total = Convert.ToInt32(oSqlDataReader["Term1Total"]),
                    Final_Term_PresentDay = Convert.ToInt32(oSqlDataReader["Term2PresentDay"]),
                    Final_Term_Total = Convert.ToInt32(oSqlDataReader["Term2Total"]),
                };
            }
        }

        private void FillCommentsEntity(SqlDataReader oSqlDataReader)
        {
            PrePrimaryStudentsExamComment oPrePrimaryStudentsExamComment;
            while (oSqlDataReader.Read())
            {
                oPrePrimaryStudentsExamComment = new PrePrimaryStudentsExamComment
                {
                    Header = Convert.ToString(oSqlDataReader["Header"]),
                    Comment = Convert.ToString(oSqlDataReader["Comment"]),
                    Progress_Entry_Id = Convert.ToInt32(oSqlDataReader["Progress_Entry_Id"]),
                    MonthId = Convert.ToInt32(oSqlDataReader["MonthId"]),
                    IsPublished = Convert.ToBoolean(oSqlDataReader["IsPublished"]),
                    IsSubmitted = Convert.ToBoolean(oSqlDataReader["IsSubmitted"]),
                };
                lstPrePrimaryStudentsExamComment.Add(oPrePrimaryStudentsExamComment);
            }
        }

        public static int  IsSubjectApplicable(int aiModuleId)
        {
           string  sSelectStatement="SELECT Is_SubjectApplicable"+
                                    " FROM "+
                                    " PrePrimaryProgressReportModuleConfigList "+
                                    " WHERE ExamModuleId="+aiModuleId+
                                    " AND Is_Deleted=0";

           using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
               return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
        }

        
        
        #endregion public



        public static List<PrePrimaryProgressReportSubSubjects> GetConfiguredSubSubject(int aiSchoolId, int aiAcademicYearId, int aiStandardId, int aiModuleId, int aiSubjectId)
        {
            List<PrePrimaryProgressReportSubSubjects> olstclsSubSubjects = new List<PrePrimaryProgressReportSubSubjects>();

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ModuleId", aiModuleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SubjectId", aiSubjectId, SqlDbType.Int);

                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetSavedSubSubjectsForStandards"))
                {
                    PrePrimaryProgressReportSubSubjects oPrePrimaryProgressReportSubSubjects;
                    while (oSqlDataReader.Read())
                    {
                        oPrePrimaryProgressReportSubSubjects = new PrePrimaryProgressReportSubSubjects
                        {
                            SubSubjectName = Convert.ToString(oSqlDataReader["SubSubject"]),
                            SubSubjectID = Convert.ToInt32(oSqlDataReader["SubSubjectID"])
                        };
                        olstclsSubSubjects.Add(oPrePrimaryProgressReportSubSubjects);
                    }
                }
            }
            return olstclsSubSubjects;
            
        }

        public bool IsPriPrimaryStudent(int aiAcademicYrID, int miStudentId, int aiSchoolID)
        {
            string sSelect = " SELECT COUNT(YearWise_Student_Details.Standard_Id)"+
                             " FROM  YearWise_Student_Details INNER JOIN "+
                             " PrePrimaryStandardForNewProgressReport ON "+
                             " YearWise_Student_Details.Standard_Id = PrePrimaryStandardForNewProgressReport.Standard_Id "+
                             " WHERE YearWise_Student_Details.YearWise_Student_Id = "+ miStudentId+
                             " AND YearWise_Student_Details.Academic_Year_ID="+aiAcademicYrID+
                             " AND YearWise_Student_Details.School_Id="+ aiSchoolID+
                             " AND YearWise_Student_Details.Is_Deleted=N'" + Constants.C_NO + "'";
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelect);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true; 
        }
    }
}
