//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------

// Class Name       :- SchoolEnquiryDC
// Purpose          :- This class is used to manage Student Enquiry details.

using System.Data;
using System.Data.SqlClient;
using Utility;
using System;
using SchoolEntities;
using System.Collections.Generic;


namespace DataCommunicator
{
    public class SchoolEnquiryDC
    {

        private SchoolEnquiryStruct moSchoolEnquiryStruct;
        private int miSchoolId;
        private int miAcademicYearId;
        private int miUpdatedById;
        public int miStudentEnquiryCount;

        public SchoolEnquiryDC()
        {
        }

        public SchoolEnquiryDC(int aiSchoolId, int aiAcademicYearId, int aiUpdatedById)
        {
            // TODO: Complete member initialization
            this.miSchoolId = aiSchoolId;
            this.miAcademicYearId = aiAcademicYearId;
            this.miUpdatedById = aiUpdatedById;
        }

        public SchoolEnquiryStruct SchoolEnquiryStructDetails
        {
            get
            {
                return moSchoolEnquiryStruct;
            }
            set
            {
                moSchoolEnquiryStruct = value;
            }
        }

     
        // This function is used to insert the StudentEnquiry Details.
        public DataTable InsertSchoolEnquiryDetails(int aiSchoolId, int aiEnquiryId, string asSchoolReferences, out int aiDBEnquiryId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("Enquiry_Details", moSchoolEnquiryStruct.msEnquiryDetails, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolReferences", asSchoolReferences, SqlDbType.NVarChar);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("DBEnquiryId", 0, SqlDbType.Int, ParameterDirection.Output);
                DataTable dtEnquiryDetails = oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_InsertSchoolEnquiryDetails");
                aiDBEnquiryId = oSqlParameter.Value.ToInt();
                return dtEnquiryDetails;
            }
        }
        public DataTable GetAcademicYear(int aiid, int aiSchoolID)
        {
            DataTable oDT = new DataTable();

            if (aiSchoolID == Constants.SchoolId.DPISRAVET.ToInt())
            {
                string sCOnnectionString = Constants.S_CONNECTION_STRING.Replace("DPIS", "DPISRavet");
                using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility(sCOnnectionString))
                {
                    oSQLServerDbUtility.AddParameter("Id", aiid, SqlDbType.Int);
                    oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                    oDT = oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAcademicYearNo");
                }
            }
            else
            {
                using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                {
                    oSQLServerDbUtility.AddParameter("Id", aiid, SqlDbType.Int);
                    oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                    oDT = oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAcademicYearNo");
                }
            }

            return oDT;
        }
        /// <summary>
        /// This method is used to return minimum and maximum date of birth for selected standard.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStandardId"></param>
        public void GetMinMaxDOBforStandard(int aiSchoolId, int aiAcademicYearId, int aiStandardId, out DateTime adtMinDOB, out DateTime adtMaxDOB)
        {
            adtMinDOB = DateTime.MinValue;
			adtMaxDOB = DateTime.MinValue;
			
			string sSelectStatement = "SELECT DOBMin,DOBMax " +
                                      "FROM AdmissionProcessDetails" +
                                      " WHERE School_ID = " + aiSchoolId +
                                      " AND Academic_Year_ID = " + aiAcademicYearId +
                                      " AND Standard_Id = " + aiStandardId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            using (SqlDataReader oDRMinMaxDate = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
            {
                if (oDRMinMaxDate.Read())
                {
                    if (oDRMinMaxDate["DOBMin"] != DBNull.Value)
                        adtMinDOB = Convert.ToDateTime(oDRMinMaxDate["DOBMin"]);
                    if (oDRMinMaxDate["DOBMax"] != DBNull.Value)
                        adtMaxDOB = Convert.ToDateTime(oDRMinMaxDate["DOBMax"]);
                }
            }
        }

        public struct SchoolEnquiryStruct
        {

            public string msEnquiryDetails;

            public string msHeardFromDetails;

            public int miInsertedByid;

        }

        /// <summary>
        /// This method is used to get Next Academic Year.
        /// </summary>
        /// <param name="aiSchoolID"></param>
        /// <param name="acAdmissionForCurrentYear"></param>
        /// <returns></returns>
        public DataSet GetNextAcadamicYearDetails(int aiSchoolID, string acAdmissionForCurrentYear)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AdmissionForCurrentYear", acAdmissionForCurrentYear, SqlDbType.VarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetNextNotConfiguredAcademicYearDetails");
            }
        }

        /// <summary>
        /// This method is used to Check whether Enquiry number is duplicate.
        /// </summary>
        /// <param name="asEnquiryNo"></param>
        /// <returns></returns>
        public bool IsDuplicateEnquiryNumber(string asEnquiryNo)
        {
            bool bFlag = false;
            string sSelectStatement = "SELECT COUNT(*)  " +
                                            " FROM " +
                                            " SchoolEnquiryDetails " +
                                         " WHERE " +
                                            " Enquiry_No like'%" + StringUtility.ReplaceSingleQuoteInString(asEnquiryNo, false) + "%'" +
                                            " AND Is_Deleted = N'" + Constants.C_NO + "'";
                                            

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                int i = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
                if (i > 0)
                    bFlag = true;
            }
            return bFlag;
        }

        /// <summary>
        /// This method is used to get Next Enquiry Number.
        /// </summary>
        /// <param name="aiSchoolID"></param>
        /// <returns></returns>
        public string GetNextEnquiryNo(int aiSchoolID,int aiAcademicYearID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearID", aiAcademicYearID, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("EnquiryNo", null, SqlDbType.NVarChar, ParameterDirection.Output, 100);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_GetEnquiryNo");
                return oSqlParameter.Value.ToString();
            }
        }

        /// <summary>
        /// This method is used to get master data for enquiry.
        /// </summary>
        /// <param name="aiSchoolID"></param>
        /// <param name="acAdmissionForCurrentYear"></param>
        /// <returns></returns>
        public static DataSet GetAllMasterDataForStudentEnquiry(int aiSchoolID,string acAdmissionForCurrentYear)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AdmissionForCurrentYear", acAdmissionForCurrentYear, SqlDbType.VarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetSchoolDetailsforEnquiry");
            }
        }

        /// <summary>
        /// This method is used to get All Student Enquiry details.
        /// </summary>
        /// <param name="aiEndIndex"></param>
        /// <returns></returns>
        public static DataTable GetAllStuEnquiryDetails(int aiSchoolID, int aiAcademicYearID, int aiStandardID,int aiLocationId ,int aiAdmissionType,string asStudentName, string sortExpression, int aiStartIndex, int aiEndIndex, int aiAdmissionStatusId, int aiAdmissionFor, string asStartDate, string asEndDate) ////
           {

            string sFilter = string.Empty;
            if (asStartDate == "")
                asStartDate = null;
            if (asEndDate == "")
                asEndDate = null; 
            if (asStartDate != null && asEndDate != null)
                sFilter = String.Format(" AND SED.InsertedDate BETWEEN '{0}' AND '{1}'", asStartDate, asEndDate);
            else if (asStartDate != null && asEndDate == null)
                sFilter = String.Format(" AND SED.InsertedDate >= '{0}'", asStartDate);
            else if (asStartDate == null && asEndDate != null)
                sFilter = String.Format(" AND SED.InsertedDate <= '{0}'", asEndDate);
            else if (asStartDate == null && asEndDate == null)
                sFilter = string.Empty;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SortExp", " ORDER BY " + sortExpression.ToString(), SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("StartIndex", aiStartIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EndIndex", aiEndIndex, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("LocationId", aiLocationId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("FormOrName", asStudentName, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("Standard_Id", aiStandardID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AdmissionStatusId", aiAdmissionStatusId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AdmissionForId", aiAdmissionFor, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("DateFilter", sFilter, SqlDbType.NVarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAllStudEnquiryDetails");
            }
        }

        public DataTable GetStudEnquiryStatusDetailsForExport(int aiSchoolId, int aiAcademicYearId, int aiEnquiryId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);

                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetStudEnquiryStatusDetailsForExport");
            }
        }

        /// <summary>
        /// This method is used to get Enquiry details for specific EnquiryId.
        /// </summary>
        /// <returns></returns>
        public static DataSet GetStudentEnquiryDetails(int? aiEnquiryId, int aiSchoolId, int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetStudEnquiryDetails");
            }
        }        

        /// <summary>
        /// This method is used to get Fee Areas.
        /// </summary>
        /// <param name="aiSchoolID"></param>
        /// <returns></returns>
        public static DataTable GetAllAreas(int aiSchoolID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAreas");
            }
        }

        //public  DataTable GetAcademicYear(int aiid, int aiSchoolID)
        //{
        //    using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
        //    {

        //        oSQLServerDbUtility.AddParameter("Id", aiid, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolID, SqlDbType.Int);
        //      return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAcademicYearNo");
        //    }
        //}

        public static DataTable GetAllOccupations()
        {
            using(SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSQLStatement = string.Empty;
                sSQLStatement = "SELECT Ocupation_Id, Ocupation_Name from Ocupation_Master WHERE Is_Deleted = 'N' ";
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSQLStatement);
            }
        }

        public static DataTable GetAllCategoriesForEnquiry()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSQLStatement = string.Empty;
                sSQLStatement = "SELECT Category_Id, Category_Name from Category_Master WHERE Is_Deleted = 'N' ORDER BY SortOrder";
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSQLStatement);
            }
        }

        /// <summary>
        /// This method is used to check whether admission is Available for that standard.
        /// </summary>
        /// <returns></returns>
        public static bool ChkIfAdmissionOpenforStd(int aiStandardId, int aiSchoolId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsAdmissionOpen", 0, SqlDbType.Bit, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsAdmissionOpenforStnadard");
                return Convert.ToBoolean(oSqlParameter.Value);
            }
        }

        public static int GetFeeArea(int? miEnquiryId)
        {
            string sSqlStatement = "SELECT Area" +
                                            " FROM " +
                                            " SchoolEnquiryDetails" +
                                         " WHERE " +
                                            " SchoolEnquiryDetails.Id = " + (miEnquiryId) + 
                                            " AND SchoolEnquiryDetails.Is_Deleted = N'" + Constants.C_NO + "'";

            using (SQLServerDbUtility oSqlDbUtility = new SQLServerDbUtility())
                return oSqlDbUtility.PerformIntQueryOnSqlServer(sSqlStatement);
        }

        public List<EnquiryReference> GetAllSchoolReference()
        {
            List<EnquiryReference> lstEnquiryReference = new List<EnquiryReference>();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                using (SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_GetSchoolEnquiryParameters"))
                {
                    while (oSqlDataReader.Read())
                    {
                        lstEnquiryReference.Add
                            (
                                new EnquiryReference
                                {
                                    Id = oSqlDataReader["Id"].ToInt(),
                                    Name = oSqlDataReader["Name"].ToString()
                                }
                            );
                    }
                }
            }
            return lstEnquiryReference;
        }

        /// <summary>
        /// This method is used to get enquiry details for registration.
        /// </summary>
        /// <param name="aiEnquiryId"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiAdmissionId"></param>
        /// <returns></returns>
        public static DataTable GetStudentEnquiryDetailsForRegistration(int aiEnquiryId, int aiSchoolId, int aiAcademicYearId, int aiAdmissionId, int aiIsEnquiry)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                if (aiIsEnquiry == 0)
                {
                    oSQLServerDbUtility.AddParameter("AdmissionId", aiAdmissionId, SqlDbType.Int);
                }
                string sProcName = aiIsEnquiry == 0 ? "usp_GetEnquiryDetailsForRegistration" : "usp_GetEnquiryDetails";
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable(sProcName);
            }
        }

        /// <summary>
        /// This method is used to save student registration details in table.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="asStudentDetails"></param>
        /// <param name="aiAdmissionId"></param>
        /// <param name="aiInsertedById"></param>
        /// <param name="aiEnquiryId"></param>
        //public int SaveStudentRegistrationDetails(int aiSchoolId, int aiAcademicYearId, string asStudentDetails, int aiAdmissionId, int aiInsertedById, int aiEnquiryId, string asStudentStreamWiseSubjectDetails) //
        //{
        //    using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
        //    {
        //        oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("AdmissionId", aiAdmissionId, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("StudentDetails", asStudentDetails, SqlDbType.NVarChar);
        //        oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
        //        oSQLServerDbUtility.AddParameter("StreamWiseSubjectDetails", asStudentStreamWiseSubjectDetails, SqlDbType.NVarChar); //
        //        oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_SaveStudentRegistrationDetails");
        //    }
        //}
        public static DataTable SaveStudentRegistrationDetails(int aiSchoolId, int aiAcademicYearId, string asStudentDetails,
                                         int aiAdmissionId, int aiInsertedById, int aiEnquiryId,
                                         string asStudentStreamWiseSubjectDetails, int aiIsEnquiry)
        {
            using (var oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                if (aiIsEnquiry == 0)
                {
                    SqlParameter oSqlParam = oSQLServerDbUtility.AddParameter("AdmissionId", aiAdmissionId, SqlDbType.Int, ParameterDirection.InputOutput);
                }
                oSQLServerDbUtility.AddParameter("StudentDetails", asStudentDetails, SqlDbType.Xml);
                oSQLServerDbUtility.AddParameter("EnquiryId", aiEnquiryId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("InsertedById", aiInsertedById, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StreamWiseSubjectDetails", asStudentStreamWiseSubjectDetails, SqlDbType.Xml);
                string sProcName = aiIsEnquiry == 0 ? "usp_SaveStudentRegistrationDetails" : "usp_SaveStudentEnquiryDetails";
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable(sProcName);

             
            }
        }
        public DataTable GetSchoolLocations()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetSchoolLocations");
            }
        }
    }

}
