//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------

// Class Name       :- SchoolwiseFeeSubTypeConfigurationDC
// Purpose          :- This class is used to manage SchoolwiseFeeSubTypeConfiguration details.
// Date Of creation :- 2/7/2008
// Author Name      :- 


using System;
using System.Data;
using System.Collections;
using System.Data.SqlClient;
using Utility;

namespace DataCommunicator
{
	public class SchoolwiseFeeSubTypeConfigurationDC : DataCommunicatorBaseDC
	{
		#region -- MEMBER(s) --

		private SchoolwiseFeeSubTypeConfigurationStruct moSchoolwiseFeeSubTypeConfigurationStruct;

		#endregion -- MEMBER(s) --

		#region -- CONSTRUCTOR(s) --

		public SchoolwiseFeeSubTypeConfigurationDC()
		{
		}

		public SchoolwiseFeeSubTypeConfigurationDC(int aiFeeSubTypeId)
		{
			LoadSchoolwiseFeeSubTypeConfigurationDetails(aiFeeSubTypeId);
		}

		#endregion -- CONSTRUCTOR(s) --

		#region -- PROPERTIES & STRUCT(s) --

		public struct SchoolwiseFeeSubTypeConfigurationStruct
		{
			public int miFeeSubTypeId;
			public string msFeeSubType;
			public int miSchoolId;
			public int miAcademicYearId;
			public int miOriginalFeeSubTypeId;
			public int miInsertedByid;
			public int miUpdatedById;
			public bool IsNewStudent;
			public bool IsOldStudent;
		}

		public virtual SchoolwiseFeeSubTypeConfigurationStruct SchoolwiseFeeSubTypeConfigurationStructDetails
		{
			get { return moSchoolwiseFeeSubTypeConfigurationStruct; }
			set { moSchoolwiseFeeSubTypeConfigurationStruct = value; }
		}

		#endregion -- PROPERTIES & STRUCT(s) --

		#region -- PUBLIC METHOD(s) --

		/// <summary>
		///		This function is used to insert the SchoolwiseFeeSubTypeConfiguration Details
		/// </summary>
		/// <returns></returns>
		public string InsertSchoolwiseFeeSubTypeConfiguration()
		{
			return "INSERT dbo.Schoolwise_Fee_SubType_Configuration(" +
						"Fee_SubType" +
						",School_Id" +
						",Academic_Year_Id" +
						",Original_Fee_SubType_Id" +
						",Inserted_By_id" +
						",Updated_By_Id" +						
					")VALUES(" +
						" N'" + StringUtility.ReplaceSingleQuoteInString(moSchoolwiseFeeSubTypeConfigurationStruct.msFeeSubType, false) + "' " +
							" , " + moSchoolwiseFeeSubTypeConfigurationStruct.miSchoolId +
							" , " + moSchoolwiseFeeSubTypeConfigurationStruct.miAcademicYearId +
							" , " + moSchoolwiseFeeSubTypeConfigurationStruct.miOriginalFeeSubTypeId +
							" , " + moSchoolwiseFeeSubTypeConfigurationStruct.miInsertedByid +
							" , " + moSchoolwiseFeeSubTypeConfigurationStruct.miUpdatedById +							
					")";
		}

		/// <summary>
		///		This function is used to update the SchoolwiseFeeSubTypeConfiguration Details
		/// </summary>
		/// <returns></returns>
		public string UpdateSchoolwiseFeeSubTypeConfiguration()
		{
			return string.Format("UPDATE dbo.Schoolwise_Fee_SubType_Configuration " +
                                 "   SET Fee_SubType= N'{0}', School_Id = {1}, Academic_Year_Id = {2}, Original_Fee_SubType_Id = {3}, Updated_By_Id = {4}, Update_Date = dbo.GetLocalDate(DEFAULT) " +
								  "WHERE Fee_SubType_Id = {5} AND is_deleted = '{6}'",
								  StringUtility.ReplaceSingleQuoteInString(moSchoolwiseFeeSubTypeConfigurationStruct.msFeeSubType, false),
								  moSchoolwiseFeeSubTypeConfigurationStruct.miSchoolId,
								  moSchoolwiseFeeSubTypeConfigurationStruct.miAcademicYearId,
								  moSchoolwiseFeeSubTypeConfigurationStruct.miOriginalFeeSubTypeId,								  
								  moSchoolwiseFeeSubTypeConfigurationStruct.miUpdatedById,
								  moSchoolwiseFeeSubTypeConfigurationStruct.miFeeSubTypeId,
								  Constants.C_NO);
		}

		/// <summary>
		///		This function is used to delete the SchoolwiseFeeSubTypeConfiguration Details
		/// </summary>
		/// <returns></returns>
		public string DeleteSchoolwiseFeeSubTypeConfiguration()
		{
			return "DELETE dbo.Schoolwise_Fee_SubType_Configuration" +
				   " WHERE Fee_SubType_Id = " + moSchoolwiseFeeSubTypeConfigurationStruct.miFeeSubTypeId +
				   "   AND is_deleted = N'" + Constants.C_NO + "'";
		}

		/// <summary>
		///		This function is used to load the SchoolwiseFeeSubTypeConfiguration Details
		/// </summary>
		/// <param name="aiFeeSubTypeId"></param>
		private void LoadSchoolwiseFeeSubTypeConfigurationDetails(int aiFeeSubTypeId)
		{
			string sSelectStatement = FetchSchoolwiseFeeSubTypeConfigurationDetailsFromDatabase(aiFeeSubTypeId);

			using (var oSQLServerDbUtility = new SQLServerDbUtility())
			using (SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
			{
				if (oDR != null)
				{
					while (oDR.Read())
					{
						if (oDR["Fee_SubType_Id"] != DBNull.Value)
							moSchoolwiseFeeSubTypeConfigurationStruct.miFeeSubTypeId = oDR["Fee_SubType_Id"].ToInt();
						if (oDR["Fee_SubType"] != DBNull.Value)
							moSchoolwiseFeeSubTypeConfigurationStruct.msFeeSubType = oDR["Fee_SubType"].ToString();
						if (oDR["School_Id"] != DBNull.Value)
							moSchoolwiseFeeSubTypeConfigurationStruct.miSchoolId = oDR["School_Id"].ToInt();
						if (oDR["Academic_Year_Id"] != DBNull.Value)
							moSchoolwiseFeeSubTypeConfigurationStruct.miAcademicYearId = oDR["Academic_Year_Id"].ToInt();
						if (oDR["Original_Fee_SubType_Id"] != DBNull.Value)
							moSchoolwiseFeeSubTypeConfigurationStruct.miOriginalFeeSubTypeId = oDR["Original_Fee_SubType_Id"].ToInt();
					}
				}
			}
		}

		/// <summary>
		///		This function is used to fetch the SchoolwiseFeeSubTypeConfiguration Details
		/// </summary>
		/// <param name="aiFeeSubTypeId"></param>
		/// <returns></returns>
		private string FetchSchoolwiseFeeSubTypeConfigurationDetailsFromDatabase(int aiFeeSubTypeId)
		{
			return "SELECT Fee_SubType_Id" +
						 ",Fee_SubType" +
						 ",School_Id" +
						 ",Academic_Year_Id" +
						 ",Original_Fee_SubType_Id" +
				   "  FROM dbo.Schoolwise_Fee_SubType_Configuration" +
				   " WHERE Fee_SubType_Id = " + aiFeeSubTypeId;
		}

		/// <summary>
		///		This method is used to return datatable containing collection of all Weekdays details.
		/// </summary>
		/// <param name="aiSchoolId"></param>
		/// <param name="aiAcademicYearId"></param>
		/// <returns></returns>
		public DataTable GetAllFeeSubTypeConfiguration(int aiSchoolId, int aiAcademicYearId)
		{
			string sSelectQuery = " SELECT  -9999 as school_id " +
											", Fee_SubType_Id " +
											",Fee_SubType " +
											",Original_Fee_SubType_Id " +											
								  " FROM " +
											" dbo.Schoolwise_Fee_SubType_Configuration" +
								  " WHERE " +
											" is_deleted = N'" + Constants.C_NO + "'" +
											" AND School_Id is null " +
											" AND Fee_SubType_Id NOT IN " +
											"(SELECT " +
											"Original_Fee_SubType_Id" +
											" FROM " +
											"Schoolwise_Fee_SubType_Configuration" +
											" WHERE " +
											" is_deleted = N'" + Constants.C_NO + "'" +
											" AND school_id =" + aiSchoolId + "" +
											" AND Academic_Year_Id = " + aiAcademicYearId + ")" +
								  " UNION  SELECT " +
											" school_id  " +
											",Fee_SubType_Id " +
											",Fee_SubType " +
											", Original_Fee_SubType_Id " +											
								 " FROM " +
											" dbo.Schoolwise_Fee_SubType_Configuration " +
								 " WHERE " +
											" is_deleted = N'" + Constants.C_NO + "'" +
											" AND school_id =" + aiSchoolId + "" +
											" AND Academic_Year_Id = " + aiAcademicYearId +
											" ORDER BY Original_Fee_SubType_Id ";



			using (var oSQLServerDbUtility = new SQLServerDbUtility())
				return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectQuery);
		}

		/// <summary>
		///		Determines if fee types are configured or not.
		/// </summary>
		/// <param name="aiSchoolId"></param>
		/// <param name="aiAcademicYearId"></param>
		/// <returns></returns>
		public bool CheckFeeTypeConfigureOrNot(int aiSchoolId, int aiAcademicYearId)
		{
			string sSelectStatement = string.Format("SELECT COUNT(Fee_SubType_Id) FROM dbo.Schoolwise_Fee_SubType_Configuration WHERE School_Id= {0} AND Is_Deleted = '{1}' AND Academic_Year_Id = {2}",
													aiSchoolId,
													Constants.C_NO,
													aiAcademicYearId);

			using (var oSQLServerDbUtility = new SQLServerDbUtility())
				return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement) != Constants.I_ZERO;
		}

		/// <summary>
		///		This method returns true when school has at least one student in current academic year.
		/// </summary>
		/// <param name="aiSchoolId"></param>
		/// <param name="aiAcademicYearId"></param>
		/// <returns></returns>
		public bool IsSchoolContainAtLeastOneStudent(int aiSchoolId, int aiAcademicYearId)
		{
			string sSelectStatement = string.Format("SELECT [dbo].[Udf_IsSchoolContainAtLeastOneStudent]({0}, {1})", aiSchoolId, aiAcademicYearId);

			using (var oSQLServerDbUtility = new SQLServerDbUtility())
				return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement) == Constants.I_ZERO;
		}

		#endregion -- PUBLIC METHOD(s) --
	}

	public class SchoolwiseFeeSubTypeConfigurationCollectionDC
	{
		#region Data Members

		private int miSchoolId = 0;
		private int miAcademicYearId = 0;

		#endregion

		#region Constructors

		public SchoolwiseFeeSubTypeConfigurationCollectionDC(int aiSchoolId, int aiAcademicYearId)
		{
			miSchoolId = aiSchoolId;
			miAcademicYearId = aiAcademicYearId;
		}

		public SchoolwiseFeeSubTypeConfigurationCollectionDC()
		{
		}

		#endregion

		#region PublicMethod

		/// <summary>
		/// 	This method update all FeeSubType Configuration into Fee SubType table.
		/// </summary>
		/// <param name="aoArrayFeeSubType"> </param>
		public void UpdateFeeSubTypeConfiguration(ArrayList aoArrayFeeSubType)
		{
			using (var oSQLServerDbUtility = new SQLServerDbUtility())
				oSQLServerDbUtility.ExecuteTransaction((String[])aoArrayFeeSubType.ToArray(typeof(string)));
		}

		/// <summary>
		/// 	This method is used to get Schoolwise feesubtype;
		/// </summary>
		/// <returns> Dataset </returns>
		public DataSet GetConfiguredFeeSubType(int aiSchoolId, int aiAcademicYearId, int aiStandardId, int aiFeeTypeId)
		{
			using (var oSQLServerDbUtility = new SQLServerDbUtility())
			{
				oSQLServerDbUtility.AddParameter("School_Id", aiSchoolId, SqlDbType.Int);
				oSQLServerDbUtility.AddParameter("academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
				oSQLServerDbUtility.AddParameter("Standard_Id", aiStandardId, SqlDbType.Int);
				oSQLServerDbUtility.AddParameter("Fee_Type_Id", aiFeeTypeId, SqlDbType.Int);
				return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_getFeeSubTypeDetails");
			}
		}

		#endregion
	}
}
