//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- SchoolWiseStanderedDivisionTestMasterDC
// Purpose          :- This class is used to manage SchoolWiseStanderedDivisionTestMaster details.
// Date Of creation :- 1/17/2008
// Author Name      :- 


using System;
using System.Data;
using System.Data.SqlClient;
using Utility;
using ProgressReportEntities;
using System.Collections.Generic;

namespace DataCommunicator
{
    public class SchoolWiseStanderedDivisionTestMasterDC : DataCommunicatorBaseDC
    {

        private SchoolWiseStanderedDivisionTestMasterStruct moSchoolWiseStanderedDivisionTestMasterStruct;
        public List<PublishExamDependencyMaster> lstPublishExamDependencyMaster = new List<PublishExamDependencyMaster>();
        public SchoolWiseStanderedDivisionTestMasterDC()
        {
        }

        public SchoolWiseStanderedDivisionTestMasterDC(int miStanderedDivisionTestId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(miStanderedDivisionTestId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                LoadSchoolWiseStanderedDivisionTestMasterDetails(oDR);
               
            }
        }

        public SchoolWiseStanderedDivisionTestMasterDC(int miSchoolID,
                                                      int miStandardDivisionId, int miAcademicYrID, int miTestId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(miSchoolID, miStandardDivisionId, miAcademicYrID, miTestId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                LoadSchoolWiseStanderedDivisionTestMasterDetails(oDR);
               
            }
        }

        public SchoolWiseStanderedDivisionTestMasterDC(int miSchoolID,
                                                     int miStandardDivisionId, int miAcademicYrID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(miSchoolID, miStandardDivisionId, miAcademicYrID);
               using( SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                LoadSchoolWiseStanderedDivisionTestMasterDetails(oDR);
            
            }
        }


        public virtual SchoolWiseStanderedDivisionTestMasterStruct SchoolWiseStanderedDivisionTestMasterStructDetails
        {
            get
            {
                return moSchoolWiseStanderedDivisionTestMasterStruct;
            }
            set
            {
                moSchoolWiseStanderedDivisionTestMasterStruct = value;
            }
        }

        // This function is used to insert the SchoolWiseStanderedDivisionTestMaster Details
        public virtual int InsertSchoolWiseStanderedDivisionTestMaster()
        {
            string sInsertStatement = "INSERT INTO SchoolWise_StanderedDivision_Test_Master(" +
            "School_id" +
            ",Standerd_division_Id" +
            ",Academic_Year_ID" +
            ",SchoolWise_Test_Id" +
            ",Is_Published" +
            ",Inserted_By_id" +
            ",Updated_By_Id" +
            ")VALUES(" +
            " " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid +
             " , " + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId +
             " , " + moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid +
             " , " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId +
             " , N'" + moSchoolWiseStanderedDivisionTestMasterStruct.msIsPublished + "'" +
             " , " + moSchoolWiseStanderedDivisionTestMasterStruct.miInsertedByid +
             " , " + moSchoolWiseStanderedDivisionTestMasterStruct.miUpdatedById +
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }

        // This function is used to insert the SchoolWiseStanderedDivisionTestMaster Details
        public void InsertSchoolWiseStandaredDivisionTestMaster()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StdDivId", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("IsPublished", moSchoolWiseStanderedDivisionTestMasterStruct.msIsPublished, SqlDbType.Char);
                oSQLServerDbUtility.AddParameter("InsertedById", moSchoolWiseStanderedDivisionTestMasterStruct.miInsertedByid, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_InsertExampublishDetails");
            }
        }

        /// <summary>
        /// This method is used to check the any exam is dependent on publish exam.
        /// </summary>
        public void CheckPublishExamDependency()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StdDivId  ", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("ExamDependentMessage",string.Empty,SqlDbType.VarChar);
                using(SqlDataReader oSqlDataReader = oSQLServerDbUtility.ExecuteStoredProcedureAndGetresult("usp_CheckPublishExamDependencies"))
                SetDependentExamNames(oSqlDataReader);
            };
        }
        private void SetDependentExamNames(SqlDataReader aoSqlDataReader)
        {
            PublishExamDependencyMaster oPublishExamDependencyMaster;
            if (aoSqlDataReader != null)
            {
                if (aoSqlDataReader.Read())
                {
                    oPublishExamDependencyMaster = new PublishExamDependencyMaster()
                    {
                        DependentExamName = aoSqlDataReader["DependentExamName"].ToString(),
                        ExamDependentMessage = aoSqlDataReader["ExamDependentMessage"].ToString() 
                    };
                    lstPublishExamDependencyMaster.Add(oPublishExamDependencyMaster);
                }
            }
        }

        /// <summary>
        /// This function is used to insert student test marks into SchoolWise_Student_Test_total_Marks
        /// </summary>
        public virtual void PublishTestMarks()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardDivision_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Published_By_id", moSchoolWiseStanderedDivisionTestMasterStruct.miInsertedByid, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_PublishTestMarks",true);
            }
        }

        public virtual void GenerateTestTotalMarks()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardDivision_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Inserted_By_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miInsertedByid, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GenerateTestTotalMarks",true);
            }
        }

        /// <summary>
        /// This function is used to insert student test marks into SchoolWise_Student_Test_total_Marks
        /// </summary>
        public virtual DataSet GetTestAndSubjectToppers(int aiRankCount)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardDivision_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ToppersCount", aiRankCount, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetTestAndSubjectToppers");
            }
        }


        /// <summary>
        /// This function is used to insert student test marks into SchoolWise_Student_Test_total_Marks
        /// </summary>
        public virtual DataSet GetTestAndSubjectStdToppers(int aiStandard, int aiRankCount)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Standard_Id", aiStandard, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("TestId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ToppersCount", aiRankCount, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetTestAndSubjectStdToppers");
            }
        }

        /// <summary>
        /// This method is used to get standard division id according to academic year id.
        /// </summary>
        /// <param name="miSchoolid"></param>
        /// <param name="miAcadmicyearid"></param>
        /// <param name="miStanderddivisionId"></param>
        /// <returns></returns>
        public static int GetStandardDivisionIdOfYear(int miSchoolid, int miAcadmicyearid, int miStudentId)
        {
            string sSelectStatement = "SELECT [dbo].[Udf_GetStandardDivisionIdOfYear](" + miSchoolid + "," + miAcadmicyearid + "," + miStudentId + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
        }

        /// <summary>
        /// This method is used to get standard division id.
        /// </summary>
        /// <param name="miSchoolid"></param>
        /// <param name="miAcadmicyearid"></param>
        /// <param name="miStanderddivisionId"></param>
        /// <returns></returns>
        public static int GetStandardDivisionId(int miSchoolid, int miAcadmicyearid, int miStandardId)
        {
            string sSelectStatement = "SELECT " +
                                      "TOP 1  SchoolWise_Standard_Division_Id " +
                                      "FROM " +
                                      "SchoolWise_Standard_Division_Master " +
                                      "WHERE " +
                                      "(School_Id = " + miSchoolid + ") " +
                                      "AND (Standard_Id = " + miStandardId + ") " +
                                      "AND (Is_Deleted = 'N') " +
                                      "AND (academic_year_id = " + miAcadmicyearid + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
        }


        public static int GetStandardId(int miSchoolid, int miAcadmicyearid, int miStandardDivisionId)
        {
            string sSelectStatement = "SELECT " +
                                      "TOP 1 Standard_Id " +
                                      "FROM " +
                                      "SchoolWise_Standard_Division_Master " +
                                      "WHERE " +
                                      "(School_Id = " + miSchoolid + ") " +
                                      "AND (SchoolWise_Standard_Division_Id = " + miStandardDivisionId + ") " +
                                      "AND (Is_Deleted = 'N') " +
                                      "AND (academic_year_id = " + miAcadmicyearid + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
        }

        public virtual bool isAnyTestPublished(int miSchoolid, int miAcadmicyearid, int miStanderddivisionId)
        {           
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StanderdDivisionId", miStanderddivisionId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsPublished", false, SqlDbType.Bit, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsAnyTestPublished");
                return oSqlParameter.Value.ToBool();
            }
        }

        public DataSet IsAnyTestPublishedForStudent(int aiSchoolID, int aiAcademicYrID, int aiStudentId, int aiStanderddivisionId)
        {
            string sFilter = string.Empty;
            if (aiStudentId != 0)
                sFilter = " AND StudentId= " + aiStudentId;
            if (aiStanderddivisionId != 0)
                sFilter = " AND Standard_division_Id= " + aiStanderddivisionId;
            String strSelect = " SELECT " +
                                  " TOP 1 StudentWiseTestPublishStatusId As TestCount " +
                               " FROM StudentWiseTestPublishStatus " +
                               " WHERE  " +
                                    " School_Id= " + aiSchoolID +
                                    " AND Is_Published= N'" + Constants.C_YES + "'" +
                                    " AND Is_Deleted= N'" + Constants.C_NO + "'" +
                                    sFilter +
                                    " AND Academic_Year_ID= " + aiAcademicYrID;

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataSet(strSelect);
        }

        /// <summary>
        /// This function is used to check is all standard division of all school have published their result or not.
        /// </summary>
        /// <returns></returns>
        public virtual DataSet isAllSchoolResultsPublished(int iSchoolID, int iAcademicYrID)
        {
            String strSelect = " SELECT dbo.Udf_isAllSchoolResultsPublished(" + iSchoolID.ToString() + ","
                                                    + iAcademicYrID.ToString() + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataSet(strSelect);

        }


        public virtual DataSet IsAllResultsGeneratedForStdDiv()
        {
            String strSelect = " SELECT dbo.Udf_isAllResultsGeneratedForStdDiv(" + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid + "," +
                                                    +moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid + "," +
                                                    +moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId + ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataSet(strSelect);

        }

        public DataTable IsAtleastOneResultGeneratedForStdDiv()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Standard_Division_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Standard_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderdId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_IsAtleastOneResultGeneratedForStdDiv");
            }
        }

        public virtual DataSet isAllResultsGenerated(int iSchoolID, int iAcademicYrID)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", iSchoolID, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", iAcademicYrID, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_getResultNotGeneratedStd");
            }
        }

        /// <summary>
        /// This method is used to get all non configured standered division of a given standered
        /// </summary>
        /// <param name="aiStandard_Id"></param>
        /// <returns></returns>
        public virtual DataTable isTestPublishedForAllDivs(int aiStandard_Id)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("Schoool_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Standard_Id", aiStandard_Id, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Test_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_isTestPublishedForAllDivs");
            }
        }

        /// <summary>
        /// This method is used to get all non configured standered division of a given standered
        /// </summary>
        /// <param name="aiStandard_Id"></param>
        /// <returns></returns>
        public virtual DataSet isAllResultsGeneratedForDivs(int aiStandard_Id)
        {
            String strSelect = " SELECT " +
                                    " Standard_Master.Standard_Name + ' - ' + Division_Master.Division_Name AS Standered_Name " +
                                " FROM SchoolWise_Standard_Division_Master INNER JOIN " +
                                " Standard_Master ON SchoolWise_Standard_Division_Master.Standard_Id = Standard_Master.Standard_Id AND " +
                                " SchoolWise_Standard_Division_Master.academic_year_id = Standard_Master.academic_Year_Id AND " +
                                " SchoolWise_Standard_Division_Master.School_Id = Standard_Master.School_Id INNER JOIN " +
                                " Division_Master ON SchoolWise_Standard_Division_Master.Division_Id = Division_Master.Division_Id AND " +
                                " SchoolWise_Standard_Division_Master.School_Id = Division_Master.School_Id AND " +
                                " SchoolWise_Standard_Division_Master.academic_year_id = Division_Master.academic_year_id " +
                                " WHERE     " +
                                    " (SchoolWise_Standard_Division_Master.School_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid + ")" +
                                    " AND (SchoolWise_Standard_Division_Master.academic_year_id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid + ")" +
                                    " AND (SchoolWise_Standard_Division_Master.Standard_Id = " + aiStandard_Id + ")" +
                                    " AND (dbo.Udf_isAllResultsGeneratedForStdDiv(SchoolWise_Standard_Division_Master.School_Id," +
                                            " SchoolWise_Standard_Division_Master.academic_year_id, SchoolWise_Standard_Division_Master.SchoolWise_Standard_Division_Id) = 0" +
                                            " OR dbo.Udf_isAllResultsGeneratedForStdDiv(SchoolWise_Standard_Division_Master.School_Id," +
                                            " SchoolWise_Standard_Division_Master.academic_year_id, SchoolWise_Standard_Division_Master.SchoolWise_Standard_Division_Id) IS NULL)";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataSet(strSelect);

        }


        /// <summary>

        /// </summary>
        public virtual DataSet isAllTestPublished()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("iAcadmicYearId", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("iStdDivId", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_IsAllConffguredTestPublished");
            }
        }

        public virtual DataTable AllTestUnPublished()
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("iAcadmicYearId", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("iStdDivId", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_AllConffguredTestUnPublished");
            }
        }


        // This function is used to update the SchoolWiseStanderedDivisionTestMaster Details
        public virtual void UpdateSchoolWiseStanderedDivisionTestMaster()
        {
            string sUpdateStatement = "UPDATE SchoolWise_StanderedDivision_Test_Master SET " +
            "School_id= " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid +
            ",Standerd_division_Id= " + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId +
            ",Academic_Year_ID= " + moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid +
            ",SchoolWise_Test_Id= " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId +
            ",Is_Published= N'" + moSchoolWiseStanderedDivisionTestMasterStruct.msIsPublished + "' " +
            ",Update_Date= N'" + moSchoolWiseStanderedDivisionTestMasterStruct.mdtUpdateDate + "' " +
            ",Updated_By_Id= " + moSchoolWiseStanderedDivisionTestMasterStruct.miUpdatedById +
            "" +
            " WHERE StanderedDivisionTest_Id=" + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderedDivisionTestId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        // This function is used to delete the SchoolWiseStanderedDivisionTestMaster Details
        public virtual void DeleteSchoolWiseStanderedDivisionTestMaster()
        {
            string sDeleteStatement = "DELETE SchoolWise_StanderedDivision_Test_Master WHERE StanderedDivisionTest_Id=N'" + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderedDivisionTestId + "'";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);
        }

        // This function is used to load the SchoolWiseStanderedDivisionTestMaster Details
        private void LoadSchoolWiseStanderedDivisionTestMasterDetails(SqlDataReader oDR)
        {
            if (oDR != null)
            {
                while (oDR.Read())
                {
                    if (oDR["StanderedDivisionTest_Id"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.miStanderedDivisionTestId = Convert.ToInt32(oDR["StanderedDivisionTest_Id"]);
                    if (oDR["School_id"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid = Convert.ToInt32(oDR["School_id"]);
                    if (oDR["Standerd_division_Id"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId = Convert.ToInt32(oDR["Standerd_division_Id"]);
                    if (oDR["Academic_Year_ID"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid = Convert.ToInt32(oDR["Academic_Year_ID"]);
                    if (oDR["SchoolWise_Test_Id"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId = Convert.ToInt32(oDR["SchoolWise_Test_Id"]);
                    if (oDR["Is_Published"] != DBNull.Value)
                        moSchoolWiseStanderedDivisionTestMasterStruct.msIsPublished = Convert.ToChar(oDR["Is_Published"]);
                }
            }
        }

        // This function is used to fetch the SchoolWiseStanderedDivisionTestMaster Details
        private string FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(int miStanderedDivisionTestId)
        {
            string sSelectStatement = " SELECT  " +
            "StanderedDivisionTest_Id" +
            ",School_id" +
            ",Standerd_division_Id" +
            ",Academic_Year_ID" +
            ",SchoolWise_Test_Id" +
            ",Is_Published" +
            ",Is_Deleted" +
            ",Insert_Date" +
            ",Inserted_By_id" +
            ",Update_Date" +
            ",Updated_By_Id" +
            " FROM SchoolWise_StanderedDivision_Test_Master" +
            " WHERE StanderedDivisionTest_Id=" + miStanderedDivisionTestId +
            " AND is_deleted = N'" + Constants.C_NO + "'";
            return sSelectStatement;
        }

        // This function is used to fetch the SchoolWiseStanderedDivisionTestMaster Details
        private string FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(int miSchoolID,
                                                      int miAcademicYrID, int miStandardDivisionId, int miTestId)
        {
            string sSelectStatement = " SELECT  " +
            "StanderedDivisionTest_Id" +
            ",School_id" +
            ",Standerd_division_Id" +
            ",Academic_Year_ID" +
            ",SchoolWise_Test_Id" +
            ",Is_Published" +
            ",Is_Deleted" +
            ",Insert_Date" +
            ",Inserted_By_id" +
            ",Update_Date" +
            ",Updated_By_Id" +
            " FROM SchoolWise_StanderedDivision_Test_Master" +
            " WHERE " +
            " Standerd_division_Id = " + miStandardDivisionId +
            " AND Academic_Year_ID = " + miAcademicYrID +
            " AND School_id = " + miSchoolID +
            " AND SchoolWise_Test_Id = " + miTestId +
            " AND is_deleted = N'" + Constants.C_NO + "'";
            return sSelectStatement;
        }

        // This function is used to fetch the SchoolWiseStanderedDivisionTestMaster Details
        private string FetchSchoolWiseStanderedDivisionTestMasterDetailsFromDatabase(int miSchoolID,
                                                      int miAcademicYrID, int miStandardDivisionId)
        {
            string sSelectStatement = " SELECT  TOP 1 " +
            "StanderedDivisionTest_Id" +
            ",School_id" +
            ",Standerd_division_Id" +
            ",Academic_Year_ID" +
            ",SchoolWise_Test_Id" +
            ",Is_Published" +
            ",Is_Deleted" +
            ",Insert_Date" +
            ",Inserted_By_id" +
            ",Update_Date" +
            ",Updated_By_Id" +
            " FROM SchoolWise_StanderedDivision_Test_Master" +
            " WHERE " +
            " Standerd_division_Id = " + miStandardDivisionId +
            " AND Academic_Year_ID = " + miAcademicYrID +
            " AND School_id = " + miSchoolID +
            " AND is_deleted = N'" + Constants.C_NO + "'";

            return sSelectStatement;
        }
        /// <summary>
        /// This method is used to unpublish this test
        /// </summary>
        public void UnPublishTest(string sUnPublishReason)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_ID", moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Standerd_division_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolWise_Test_Id", moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolWiseTestId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UnPublishReason", sUnPublishReason, SqlDbType.NVarChar);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_UnPublishTest");
            }
        }

        public Boolean CheckGradeConfigurations()
        {
            string sSelectstr = "SELECT    " +
                                 "COUNT(Marks_Grades_Configuration_Details.Marks_Grades_Configuration_Detail_ID)" +
                                 " FROM         Marks_Grades_Configuration INNER JOIN " +
                                 " Marks_Grades_Configuration_Details ON " +
                                 " Marks_Grades_Configuration.Marks_Grades_Configuration_Id = " +
                                 " Marks_Grades_Configuration_Details.Marks_Grades_Configuration_Id INNER JOIN " +
                                 " SchoolWise_Standard_Division_Master ON Marks_Grades_Configuration.School_Id = SchoolWise_Standard_Division_Master.School_Id AND " +
                                 " Marks_Grades_Configuration.Academic_Year_Id = SchoolWise_Standard_Division_Master.academic_year_id AND " +
                                 " Marks_Grades_Configuration.Standard_Id = SchoolWise_Standard_Division_Master.Standard_Id INNER JOIN " +
                                 " Standard_Master ON Marks_Grades_Configuration.Standard_Id = Standard_Master.Standard_Id INNER JOIN " +
                                 " Division_Master ON SchoolWise_Standard_Division_Master.Division_Id = Division_Master.Division_Id " +
                                 " WHERE     (Marks_Grades_Configuration.Is_Deleted = 'N') " +
                                 " AND (Marks_Grades_Configuration_Details.Is_Deleted = 'N') AND " +
                                 " (Marks_Grades_Configuration.School_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid + ") " +
                                 " AND (Marks_Grades_Configuration.Academic_Year_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid + ") AND " +
                                 " (SchoolWise_Standard_Division_Master.SchoolWise_Standard_Division_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId + ")";

            // Perform the stetement on server.
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectstr);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }


        public bool CheckPassFailConfigurations()
        {
            string sSelectstr = "SELECT " +
                        " Pass_Fail_Criteria.IsFailCriteriaNotApplicable " +
                        " FROM  Pass_Fail_Criteria INNER JOIN " +
                        " SchoolWise_Standard_Division_Master ON Pass_Fail_Criteria.Standard_Id " +
                        " = SchoolWise_Standard_Division_Master.Standard_Id AND " +
                        " Pass_Fail_Criteria.School_Id = SchoolWise_Standard_Division_Master.School_Id AND " +
                        " Pass_Fail_Criteria.Academic_Year_Id = SchoolWise_Standard_Division_Master.academic_year_id " +
                        " WHERE (SchoolWise_Standard_Division_Master.SchoolWise_Standard_Division_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miStanderddivisionId + ")" +
                        " AND (SchoolWise_Standard_Division_Master.School_Id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miSchoolid + ") AND " +
                        " (SchoolWise_Standard_Division_Master.academic_year_id = " + moSchoolWiseStanderedDivisionTestMasterStruct.miAcadmicyearid + ") ";

            // Perform the stetement on server.
            string sIsFailCriteriaNotApplicable = string.Empty;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                sIsFailCriteriaNotApplicable = oSQLServerDbUtility.PerformStringQueryOnSqlServer(sSelectstr);

            // If the count is zero there is no duplication of Buyer login. 
            //if (iCount == 0)
            if (string.IsNullOrEmpty(sIsFailCriteriaNotApplicable))
                return false;
            else
                return true;
        }

        public struct SchoolWiseStanderedDivisionTestMasterStruct
        {

            public int miStanderedDivisionTestId;

            public int miSchoolid;

            public int miStanderddivisionId;

            public int miAcadmicyearid;

            public int miSchoolWiseTestId;

            public Char msIsPublished;

            public Char msIsDeleted;

            public System.DateTime mdtInsertDate;

            public int miInsertedByid;

            public System.DateTime mdtUpdateDate;

            public int miUpdatedById;

            public int miStanderdId;
        }


        public bool IsDependent(int aiUserId, int aiSchoolId, int aiAcademicYearId)
        {
            string sSelectStatement = " SELECT COUNT(Teacher_Id) FROM vw_ClassTeacher " +
                                     " WHERE  vw_ClassTeacher.User_Id = " + aiUserId +
                                     " AND School_Id = " + aiSchoolId +
                                     " AND Academic_Year_Id = " + aiAcademicYearId +
                                     " AND vw_ClassTeacher.Standard_Id NOT IN ( select Value_Member from vw_Is_Primary_Standard " +
                                     " where School_Id=" + aiSchoolId +
                                     " and Academic_Year_Id=" + aiAcademicYearId + ")";
            int iCount;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);

            // If the count is zero there is no duplication of Buyer login. 
            if (iCount == 0)
                return false;
            else
                return true;
        }

        /// <summary>
        /// This method is used to check whether term exam is published.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiStandardDivisionId"></param>
        /// <returns></returns>
        public bool IsTermExamPublished(int aiSchoolId, int aiAcademicYearId, int aiStandardDivisionId, out string asStandardName)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardDivisionId", aiStandardDivisionId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsPublished", 0, SqlDbType.Bit, ParameterDirection.Output);
                SqlParameter aoSqlParameter = oSQLServerDbUtility.AddParameter("StandardName", 0, SqlDbType.NVarChar, ParameterDirection.Output,100);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsTermExamPublished");
                asStandardName = aoSqlParameter.Value.ToString();
                return oSqlParameter.Value.ToBool();
            }
        }

        public bool IsFinalResultPublished(int aiSchoolId, int aiAcademicYearId, int aiStandardDivisionId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StandardDivisionId", aiStandardDivisionId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsFinalPublished", 0, SqlDbType.Bit, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsFinalResultPublished");
                return oSqlParameter.Value.ToBool();
            }
        }

        public DataTable GetStudentsLastAYDetails(int aiSchoolId, int aiAcademicYearId, int aiStudentId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StudentId", aiStudentId, SqlDbType.Int);

                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetStudentsLastAYDetails");
            }
        }

        public bool IsPrelimExamPublished(int aiStdDivId, int aiSchoolId, int aiAcademicYearId)
        {
            using(SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StdDivId", aiStdDivId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("IsPrelimExamPublished", false, SqlDbType.Bit,ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_IsPrelimExamPublished");
                return oSqlParameter.Value.ToBool();
            }
        }
    }
}
