//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------

// Class Name       :- SMSMasterDC
// Purpose          :- This class is used to manage SMSMaster details.
// Date Of creation :- 3/21/2008
// Author Name      :- 

using System;
using System.Data;
using System.Collections;
using System.Data.SqlClient;
using Utility;

namespace DataCommunicator
{
    public class SMSMasterDC
    {
        #region "Constant"

        private const string S_SMS_STATUS_SENT= "3";

        #endregion "Constant"

        private SMSMasterStruct moSMSMasterStruct;

        public SMSMasterDC()
        {
        }

        public SMSMasterDC(int miSMSDetailsId)
        {
            LoadSMSMasterDetails(miSMSDetailsId);
        }

        public virtual SMSMasterStruct SMSMasterStructDetails
        {
            get
            {
                return moSMSMasterStruct;
            }
            set
            {
                moSMSMasterStruct = value;
            }
        }


        // This function is used to insert the SMSMaster Details
        public virtual String GetInsertSMSMaster()
        {
            string sInsertStatement = "INSERT INTO SMS_Master(" +
            "Sender_Name" +
            ", SMS_Text" +
            ", SMS_Count" +
            ", Display_Text" +
            ", Is_DeletedFromUser" +
            ", Sender_User_Role_Id" +
            ", Sender_User_Id" +
            ", School_Id" +
            ", academic_Year_Id" +
            ", Is_Deleted" +
            ", Inserted_By_Id" +
            ", Insert_Date"+
            ", Updated_By_Id" +
            ", StatusId" +
             ", SMSTypeId" +
             ", SMSShootId" +
            ") VALUES(" +
            " N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSenderName, false) + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSMSText, false) + "' " +
             " , N'" + moSMSMasterStruct.miSMSCount + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msDisplayText, false) + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeletedFromUser, false) + "' " +
             " , " + moSMSMasterStruct.miSenderUserRoleId +
             " , " + moSMSMasterStruct.miSenderUserId +
             " , " + moSMSMasterStruct.miSchoolId +
             " , " + moSMSMasterStruct.miAcademicYearId +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeleted, false) + "' " +
             " , " + moSMSMasterStruct.miInsertedById +
              " , N'" + moSMSMasterStruct.mdtInsertDate + "' " +
             " , " + moSMSMasterStruct.miUpdatedById +
             " , " + (moSMSMasterStruct.mbIsScheduled ? Constants.S_ONE : S_SMS_STATUS_SENT) +
             " , " + moSMSMasterStruct.miSMSTypeId +
             " , '" + moSMSMasterStruct.msSMSShootId +"'"+
            ")";
            return sInsertStatement;
        }

        /// <summary>
        /// This procedure is used to delete scheduled SMS.
        /// </summary>
        /// <param name="aiSMSId"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        public void DeleteScheduledSMS(int aiSMSId,int aiSchoolId,int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SMSId", aiSMSId, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_DeleteScheduledSMS");
            }
        }

        /// <summary>
        /// This method is used to insert SMS Details
        /// </summary>
        /// <param name="aoArrayListToUsers"></param>
        public void InsertSMSMaster(ArrayList aoArrayListToUsers)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction((String[])aoArrayListToUsers.ToArray(typeof(string)));
        }

        // This function is used to insert the SMSMaster Details
        public virtual int InsertSMSMaster()
        {
            string sInsertStatement = "INSERT INTO SMS_Master(" +
            "Sender_Name" +
            ",SMS_Text" +
            ",SMS_Count" +
            ",Display_Text" +
            ",Is_DeletedFromUser" +
            ",Sender_User_Role_Id" +
            ",Sender_User_Id" +
            ",Is_Deleted" +
            ",Insert_Date" +
            ",Inserted_By_Id" +
            ",Updated_Date" +
            ",Updated_By_Id" +
            ")VALUES(" +
            " N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSenderName, false) + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSMSText, false) + "' " +
             " , N'" + moSMSMasterStruct.miSMSCount + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msDisplayText, false) + "' " +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeletedFromUser, false) + "' " +
             " , " + moSMSMasterStruct.miSenderUserRoleId +
             " , " + moSMSMasterStruct.miSenderUserId +
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeleted, false) + "' " +
             " , N'" + moSMSMasterStruct.mdtInsertDate + "' " +
             " , " + moSMSMasterStruct.miInsertedById +
             " , N'" + moSMSMasterStruct.mdtUpdatedDate + "' " +
             " , " + moSMSMasterStruct.miUpdatedById +
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }

        // This function is used to update the SMSMaster Details
        public virtual void UpdateSMSMaster()
        {
            string sUpdateStatement = "UPDATE SMS_Master SET " +
            "Sender_Name= N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSenderName, false) + "' " +
            ",SMS_Text= N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msSMSText, false) + "' " +
            ",SMS_Count= N'" + moSMSMasterStruct.miSMSCount + "' " +
            ",Display_Text= N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msDisplayText, false) + "' " +
            ",Is_DeletedFromUser= N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeletedFromUser, false) + "' " +
            ",Sender_User_Role_Id= " + moSMSMasterStruct.miSenderUserRoleId +
            ",Sender_User_Id= " + moSMSMasterStruct.miSenderUserId +
            ",Is_Deleted= N'" + StringUtility.ReplaceSingleQuoteInString(moSMSMasterStruct.msIsDeleted, false) + "' " +
            ",Insert_Date= N'" + moSMSMasterStruct.mdtInsertDate + "' " +
            ",Inserted_By_Id= " + moSMSMasterStruct.miInsertedById +
            ",Updated_Date= N'" + moSMSMasterStruct.mdtUpdatedDate + "' " +
            ",Updated_By_Id= " + moSMSMasterStruct.miUpdatedById +
            "" +
            " WHERE SMS_Id=" + moSMSMasterStruct.miSMSDetailsId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        // This function is used to delete the SMSMaster Details
        public virtual void DeleteSMSMaster()
        {
            string sDeleteStatement = "DELETE SMS_Master WHERE SMS_Id='" + moSMSMasterStruct.miSMSDetailsId + "'";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);
        }

        // This function is used to load the SMSMaster Details
        private void LoadSMSMasterDetails(int miSMSDetailsId)
        {
            DataSet oDs = FetchSMSMasterDetailsFromDatabase(miSMSDetailsId);

            if (oDs.Tables[0].Rows[0]["SMS_Id"] != DBNull.Value)
                moSMSMasterStruct.miSMSDetailsId = Convert.ToInt32(oDs.Tables[0].Rows[0]["SMS_Id"]);
            if (oDs.Tables[0].Rows[0]["Sender_Name"] != DBNull.Value)
                moSMSMasterStruct.msSenderName = Convert.ToString(oDs.Tables[0].Rows[0]["Sender_Name"]);
            if (oDs.Tables[0].Rows[0]["SMS_Text"] != DBNull.Value)
                moSMSMasterStruct.msSMSText = Convert.ToString(oDs.Tables[0].Rows[0]["SMS_Text"]);
            if (oDs.Tables[0].Rows[0]["SMS_Count"] != DBNull.Value)
                moSMSMasterStruct.miSMSCount = Convert.ToInt32(oDs.Tables[0].Rows[0]["SMS_Count"]);
            if (oDs.Tables[0].Rows[0]["Display_Text"] != DBNull.Value)
                moSMSMasterStruct.msDisplayText = Convert.ToString(oDs.Tables[0].Rows[0]["Display_Text"]);
            if (oDs.Tables[0].Rows[0]["Is_DeletedFromUser"] != DBNull.Value)
                moSMSMasterStruct.msIsDeletedFromUser = Convert.ToString(oDs.Tables[0].Rows[0]["Is_DeletedFromUser"]);
            if (oDs.Tables[0].Rows[0]["Sender_User_Role_Id"] != DBNull.Value)
                moSMSMasterStruct.miSenderUserRoleId = Convert.ToInt32(oDs.Tables[0].Rows[0]["Sender_User_Role_Id"]);
            if (oDs.Tables[0].Rows[0]["Sender_User_Id"] != DBNull.Value)
                moSMSMasterStruct.miSenderUserId = Convert.ToInt32(oDs.Tables[0].Rows[0]["Sender_User_Id"]);
            if (oDs.Tables[0].Rows[0]["School_Id"] != DBNull.Value)
                moSMSMasterStruct.miSchoolId = Convert.ToInt32(oDs.Tables[0].Rows[0]["School_Id"]);
            if (oDs.Tables[0].Rows[0]["academic_Year_Id"] != DBNull.Value)
                moSMSMasterStruct.miAcademicYearId = Convert.ToInt32(oDs.Tables[0].Rows[0]["academic_Year_Id"]);
            if (oDs.Tables[0].Rows[0]["Is_Deleted"] != DBNull.Value)
                moSMSMasterStruct.msIsDeleted = Convert.ToString(oDs.Tables[0].Rows[0]["Is_Deleted"]);
            if (oDs.Tables[0].Rows[0]["Insert_Date"] != DBNull.Value)
                moSMSMasterStruct.mdtInsertDate = Convert.ToDateTime(oDs.Tables[0].Rows[0]["Insert_Date"]);
            if (oDs.Tables[0].Rows[0]["Inserted_By_Id"] != DBNull.Value)
                moSMSMasterStruct.miInsertedById = Convert.ToInt32(oDs.Tables[0].Rows[0]["Inserted_By_Id"]);
            if (oDs.Tables[0].Rows[0]["Updated_Date"] != DBNull.Value)
                moSMSMasterStruct.mdtUpdatedDate = Convert.ToDateTime(oDs.Tables[0].Rows[0]["Updated_Date"]);
            if (oDs.Tables[0].Rows[0]["Updated_By_Id"] != DBNull.Value)
                moSMSMasterStruct.miUpdatedById = Convert.ToInt32(oDs.Tables[0].Rows[0]["Updated_By_Id"]);

        }

        // This function is used to fetch the SMSMaster Details
        private DataSet FetchSMSMasterDetailsFromDatabase(int miSMSDetailsId)
        {
            string sSelectStatement = " SELECT  " +
                                        " SMS_Id" +
                                        " , Sender_Name" +
                                        " , SMS_Text" +
                                        " , SMS_Count" +
                                        " , Display_Text" +
                                        " , Is_DeletedFromUser" +
                                        " , Sender_User_Role_Id" +
                                        " , Sender_User_Id" +
                                        " , School_Id " +
                                        " , academic_Year_Id " +
                                        " , Is_Deleted" +
                                        " , Insert_Date" +
                                        " , Inserted_By_Id" +
                                        " , Updated_Date" +
                                        " , Updated_By_Id" +
                                        "  FROM SMS_Master" +
                                        " WHERE SMS_Id=" + miSMSDetailsId;
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataSet(sSelectStatement);
        }

        /// <summary>
        /// This method is used to get the receiver name list.
        /// </summary>
        /// <returns></returns>
        public DataTable GetListOfReceiverName()
        {
            string sSelectStatement = " SELECT TOP 1 " +
                                      " UserName " +
                                      ", Receiver_User_Id " +
                                      ", Receiver_User_Role_Id " +
                                  " FROM " +
                                      " vw_GetSMSReceiptantListForGivenSMSId " +
                                  " WHERE " +
                                      " SMS_Id=" + moSMSMasterStruct.miSMSDetailsId;

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }

        /// <summary>
        /// This method is used to get the Count for sms
        /// </summary>
        /// <returns></returns>
        public DataTable GetCountOfSentSMS(int iSchoolID, int iAcademicYearID)
        {
            string sSelectStatement = "SELECT     " +
                                            " AllowedSMS_Count " +
                                            " , SentSMS_Count " +
                                    " FROM  SchoolWise_Academic_Year_Master " +
                                    " WHERE  " +
                                            " (Academic_Year_ID = " + iAcademicYearID + ")" +
                                            " AND (School_Id = " + iSchoolID + ")";

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }

        /// <summary>
        /// This method is usedto delete messages from sent items list.
        /// </summary>
        /// <param name="aoArrMessageDetailsId"></param>
        public void DeleteSentItems(Hashtable aoHtMessageDetailsId)
        {
            string sMessageDetailsIdList = "";
            foreach (DictionaryEntry oDE in aoHtMessageDetailsId)
            {
                sMessageDetailsIdList = sMessageDetailsIdList + oDE.Value.ToString();
                sMessageDetailsIdList = sMessageDetailsIdList + ",";
            }
            sMessageDetailsIdList = sMessageDetailsIdList.Remove(sMessageDetailsIdList.Length - 1);

            string sDeleteStatement = " UPDATE " +
                                        " SMS_master " +
                                      " SET " +
                                        " Is_DeletedFromUser= N'" + Constants.C_YES + "'" +
                                      " WHERE " +
                                        " SMS_Id IN (" + sMessageDetailsIdList + ")" +
                                        " AND Is_Deleted= N'" + Constants.C_NO + "'";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);

        }

        /// <summary>
        /// This method is used to check that if any scheduled sms from selected list has been processed or not.
        /// </summary>
        /// <param name="asSMSIds"></param>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        public void DeleteScheduledSMS(string asSMSIds,int aiSchoolId, int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SMSIds", asSMSIds, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_DeleteScheduledSMS");
            }
        }

        /// <summary>
        /// This method is used to delet SMS from message inbox.
        /// </summary>
        /// <param name="aoArrMessageReceiverId"></param>
        public void DeleteSMSFromInbox(Hashtable aoHtMessageDetailsId)
        {
            string sMessageDetailsIdList = "";
            foreach (DictionaryEntry oDE in aoHtMessageDetailsId)
            {
                sMessageDetailsIdList = sMessageDetailsIdList + oDE.Value.ToString();
                sMessageDetailsIdList = sMessageDetailsIdList + ",";
            }
            sMessageDetailsIdList = sMessageDetailsIdList.Remove(sMessageDetailsIdList.Length - 1);

            string sDeleteStatement = " UPDATE " +
                                        " SMS_Receiver_Details " +
                                      " SET " +
                                        " Is_Deleted = N'" + Constants.C_YES + "'" +
                                      " WHERE " +
                                        " SMS_Receiver_Details_Id IN (" + sMessageDetailsIdList + ")" +
                                        " AND Is_Deleted= N'" + Constants.C_NO + "'";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);
        }


        public struct SMSMasterStruct
        {

            public int miSMSDetailsId;

            public string msSenderName;

            public string msSMSText;

            public int miSMSCount;

            public string msDisplayText;

            public string msIsDeletedFromUser;

            public int miSenderUserRoleId;

            public int miSenderUserId;

            public int miSchoolId;

            public int miAcademicYearId;

            public string msIsDeleted;

            public System.DateTime mdtInsertDate;

            public int miInsertedById;

            public System.DateTime mdtUpdatedDate;

            public int miUpdatedById;

            public bool mbIsScheduled;

            public DateTime ScheduleDateTime;

            public int miSMSTypeId;
            public string msSMSDetailsXML;
            public string msSMSShootId; 
        }

        public void SaveSMSDetails(string asSMSDetailsXml)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", moSMSMasterStruct.miSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", moSMSMasterStruct.miAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SenderName", moSMSMasterStruct.msSenderName, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("SenderUserId", moSMSMasterStruct.miSenderUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SenderUserRoleId", moSMSMasterStruct.miSenderUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SMSDetailsXml", asSMSDetailsXml, SqlDbType.Xml);
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_SaveSalarySMSDetails");
            }
        }

        /// <summary>
        /// This function is used to get SMS provider for website
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <returns></returns>
        public string GetSMSProviderForWebsite(int aiSchoolId, int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                SqlParameter oSqlParameter = oSQLServerDbUtility.AddParameter("SMSProvider", string.Empty, SqlDbType.NVarChar, ParameterDirection.Output, 500);                
                oSQLServerDbUtility.ExecuteStoredProcedureOnServer("usp_GetSMSProviderForWebsite");
                return oSqlParameter.Value.ToString(); 
            }   
        }
    }

    public class SMSMasterCollectionDC
    {

        /// <summary>
        /// This method is used to get the Sent Items list for logged in user.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <returns></returns>
        public static DataTable GetSentItemsForUser(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asName, String asContent, String sortExpression, int maximumRows, int startRowIndex, int aiShowAllSMS)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {

                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Receiver_User_Role_Id", aiUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("prm_StartIndex", startRowIndex, SqlDbType.Int);
                if (!string.IsNullOrEmpty(sortExpression))
                {
                    string sSortExpression = sortExpression;
                    if (sortExpression.Contains("UserName"))
                        sortExpression = "UserName";
                    if (sSortExpression.Contains("DESC") && sortExpression == "UserName")
                        sortExpression = sortExpression + " DESC";
                    sortExpression = " ORDER BY " + sortExpression;
                    oSQLServerDbUtility.AddParameter("SortExp", sortExpression, SqlDbType.NVarChar);

                }
                //oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("DivisionId", aiDivisionId, SqlDbType.Int);
                if (!string.IsNullOrEmpty(asName))
                    oSQLServerDbUtility.AddParameter("Name", asName, SqlDbType.NVarChar);
                if (!string.IsNullOrEmpty(asContent))
                    oSQLServerDbUtility.AddParameter("Content", asContent, SqlDbType.NVarChar);

                oSQLServerDbUtility.AddParameter("ViewAllSMS", aiShowAllSMS, SqlDbType.Bit);

                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetPagedSentSMS");
            }
        }

        public static int CountSentSMS(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asName, String asContent,int aiShowAllSMS)
        {
            SqlParameter oSqlParameter = new SqlParameter();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Sender_User_Role_Id", aiUserRoleId, SqlDbType.Int);

                //oSQLServerDbUtility.AddParameter("StandardId", aiStandardId, SqlDbType.Int);
                //oSQLServerDbUtility.AddParameter("DivisionId", aiDivisionId, SqlDbType.Int);
                if (!string.IsNullOrEmpty(asName))
                    oSQLServerDbUtility.AddParameter("Name", asName, SqlDbType.NVarChar);
                if (!string.IsNullOrEmpty(asContent))
                    oSQLServerDbUtility.AddParameter("Content", asContent, SqlDbType.NVarChar);

                //if (aiShowAllSMS == 0)
                //    aiShowAllSMS = false;
                //else
                //    aiShowAllSMS = true;
              
                oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.AddParameter("ViewAllSMS", aiShowAllSMS, SqlDbType.Bit);
                
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_ContSentSMS");
            }
            return Convert.ToInt32(oSqlParameter.Value);
        }

        /// <summary>
        /// This method is used to export details of Sent Items list for logged in user.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <returns></returns>
        public static DataTable GetSentItemsForUserForExport(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asName, String asContent, String sortExpression, int maximumRows, int startRowIndex, int aiShowAllSMS)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Receiver_User_Role_Id", aiUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("prm_StartIndex", startRowIndex, SqlDbType.Int);
                if (!string.IsNullOrEmpty(sortExpression))
                {
                    string sSortExpression = sortExpression;
                    if (sortExpression.Contains("UserName"))
                        sortExpression = "UserName";
                    if (sSortExpression.Contains("DESC") && sortExpression == "UserName")
                        sortExpression = sortExpression + " DESC";
                    sortExpression = " ORDER BY " + sortExpression;
                    oSQLServerDbUtility.AddParameter("SortExp", sortExpression, SqlDbType.NVarChar);
                }
                if (!string.IsNullOrEmpty(asName))
                    oSQLServerDbUtility.AddParameter("Name", asName, SqlDbType.NVarChar);
                if (!string.IsNullOrEmpty(asContent))
                    oSQLServerDbUtility.AddParameter("Content", asContent, SqlDbType.NVarChar);
                oSQLServerDbUtility.AddParameter("ViewAllSMS", aiShowAllSMS, SqlDbType.Bit);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetPagedSentSMSForExport");
            }
        }

        /// <summary>
        /// This method is used to get the received SMS Items list for logged in user.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <returns></returns>
        public static DataTable GetReceivedSMSItemsForUser(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asRegNo, String asContent, String sortExpression, int maximumRows, int startRowIndex, int aiShowAllSMS)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Receiver_User_Role_Id", aiUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("prm_StartIndex", startRowIndex, SqlDbType.Int);
                if (!string.IsNullOrEmpty(sortExpression))
                    oSQLServerDbUtility.AddParameter("SortExp", " ORDER BY " + sortExpression, SqlDbType.NVarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetPagedReceivdSMSId");
            }
        }

        /// <summary>
        /// Get Total Count of Received SMS.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="asRegNo"></param>
        /// <param name="asContent"></param>
        /// <param name="sortExpression"></param>
        /// <param name="maximumRows"></param>
        /// <param name="startRowIndex"></param>
        /// <returns></returns>
        public static int GetReceivedSMSCountUser(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asRegNo, String asContent, String sortExpression, int maximumRows, int startRowIndex)
        {
            SqlParameter oSqlParameter = new SqlParameter();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Receiver_User_Role_Id", aiUserRoleId, SqlDbType.Int);
                oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetPagedReceivdSMSCount");
                return Convert.ToInt32(oSqlParameter.Value);
            }
        }
        public static int CountSMS(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId)
        {
            SqlParameter oSqlParameter = new SqlParameter();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("iSchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Academic_Year_Id", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("User_Id", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("Receiver_User_Role_Id", aiUserRoleId, SqlDbType.Int);
                oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_ContReceivedSMS");
            }
            return Convert.ToInt32(oSqlParameter.Value);
        }

        /// <summary>
        /// This method is used to get scheduled sms details.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="asName"></param>
        /// <param name="sortExpression"></param>
        /// <param name="maximumRows"></param>
        /// <param name="startRowIndex"></param>
        /// <returns></returns>
        public static DataTable GetScheduledSMS(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asName, String sortExpression, int maximumRows, int startRowIndex)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UserId", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ReceiverUserRoleId", aiUserRoleId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("StartIndex", startRowIndex, SqlDbType.Int);
                if (!string.IsNullOrEmpty(sortExpression))
                    oSQLServerDbUtility.AddParameter("SortExp", " ORDER BY " + sortExpression, SqlDbType.NVarChar);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetScheduledSMSDetails");
            }
        }

        /// <summary>
        /// This method is used to get the count of scheduled sms.
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiUserId"></param>
        /// <param name="aiUserRoleId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="asName"></param>
        /// <returns></returns>
        public static int CountScheduledSMS(int aiSchoolId, int aiUserId, int aiUserRoleId, int aiAcademicYearId, String asName)
        {
            SqlParameter oSqlParameter = new SqlParameter();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("UserId", aiUserId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("ReceiverUserRoleId", aiUserRoleId, SqlDbType.Int);                
                oSqlParameter = oSQLServerDbUtility.AddParameter("Cnt", 0, SqlDbType.Int, ParameterDirection.Output);
                oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetCountOfScheduledSMS");
            }
            return Convert.ToInt32(oSqlParameter.Value);
        }

        /// <summary>
        /// This method is used to get existing group information.
        /// </summary>
        /// <param name="aiSMSId"></param>
        /// <returns></returns>
        public static DataTable GetExistingGroup(int aiSMSId,int aiSchoolId,int aiAcademicYearId)
        {           
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("SMSId", aiSMSId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetExistingGroupList");
            }           
        }

        /// <summary>
        /// This method is used to check is there principal is present in existing group or not.
        /// </summary>
        /// <param name="aiUserId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <returns></returns>
        public static DataTable IsPrincipal(int aiUserId,int aiAcademicYearId)
        {
            string sSelectStatement = " SELECT User_Id FROM vw_BaseTeacherDetails WHERE Designation_Id = 10 AND User_Id="+aiUserId+" AND academic_year_id="+aiAcademicYearId+"";                                        
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
               return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);
        }
    }
}
