//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.1.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- SmsTemplateDC
// Purpose          :- This class is used to manage SmsTemplate details.
// Date Of creation :- 12/7/2009
// Author Name      :- 


using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Collections.ObjectModel;
using System.Collections;
using System.Data.SqlClient;
using Utility;




namespace DataCommunicator
{
    public class SmsTemplateDC
    {
        #region -- MEMBER(s) --

        private int miSchoolId;
        private int miAcademicYearId;   
        private SmsTemplateStruct moSmsTemplateStruct;

        #endregion -- MEMBER(s) --
       

        public SmsTemplateDC()
        {
        }

        public SmsTemplateDC(int aiSchoolId, int aiAcademicYearId)
        {
            this.miSchoolId = aiSchoolId;
            this.miAcademicYearId = aiAcademicYearId;            
        }

        public SmsTemplateDC(int miTemplateId)
        {
            LoadSmsTemplateDetails(miTemplateId);
        }

        public   SmsTemplateStruct SmsTemplateStructDetails
        {
            get
            {
                return moSmsTemplateStruct;
            }
            set
            {
                moSmsTemplateStruct = value;
            }
        }        

        // This function is used to insert the SmsTemplate Details
        public   int InsertSmsTemplate()
        {
            string sInsertStatement = "INSERT INTO SmsTemplate(" +
            "SmsTemplateName" +
            ",SmsTemplateText" +
            ",School_Id" +
            ",IsSystemDefined " +
            ",Is_Deleted" +
            ",TemplateRegistrationId" +
            ")VALUES(" +
            " N'" + StringUtility.ReplaceSingleQuoteInString(moSmsTemplateStruct.msSmsName, false) +"'"+
             " , N'" + StringUtility.ReplaceSingleQuoteInString(moSmsTemplateStruct.msTemplateText, false) + "' " +
             " , " + moSmsTemplateStruct.miSchool_Id +
             " , " + 0 +
             " , N'" + moSmsTemplateStruct.mblnIsDeleted + "' " +
               " , N'" + StringUtility.ReplaceSingleQuoteInString(moSmsTemplateStruct.msTemplateRegistrationId, false) + "' " +
            ")";
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sInsertStatement);
        }

        // This function is used to update the SmsTemplate Details
        public   void UpdateSmsTemplate()
        {
            string sUpdateStatement = "UPDATE SmsTemplate SET " +
            "SmsTemplateText= N'" + StringUtility.ReplaceSingleQuoteInString(moSmsTemplateStruct.msTemplateText, false) + "' " +
            " , SmsTemplateName= N'" + StringUtility.ReplaceSingleQuoteInString(moSmsTemplateStruct.msSmsName, false) + "' " +
            "" +
            " WHERE SmsTemplateId=" + moSmsTemplateStruct.miTemplateId +
            
            " AND "+
            "School_Id= " + moSmsTemplateStruct.miSchool_Id +
            //" AND "+
           // " AcademicYearId= " + moSmsTemplateStruct.miAcademicYearId +
            " AND "+
            " Is_Deleted= N'" + moSmsTemplateStruct.mblnIsDeleted + "' ";


            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sUpdateStatement);
        }

        // This function is used to delete the SmsTemplate Details
        public void Delete(int aiTemplateId)
        {
            string sDeleteStatement = "UPDATE SmsTemplate SET Is_Deleted= 1" +
                                        " WHERE SmsTemplateId='" + aiTemplateId + "'";
                                       
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sDeleteStatement);
        }

        // This function is used to load the SmsTemplate Details
        private void LoadSmsTemplateDetails(int miTemplateId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                string sSelectStatement = FetchSmsTemplateDetailsFromDatabase(miTemplateId);
                using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {
                    if (oDR != null)
                    {
                        while (oDR.Read())
                        {
                            if (oDR["TemplateId"] != DBNull.Value)
                                moSmsTemplateStruct.miTemplateId = Convert.ToInt32(oDR["SmsTemplateId"]);
                            if (oDR["SmsId"] != DBNull.Value)
                                moSmsTemplateStruct.msSmsName = Convert.ToString(oDR["msSmsName"]);
                            if (oDR["TemplateText"] != DBNull.Value)
                                moSmsTemplateStruct.msTemplateText = Convert.ToString(oDR["SmsTemplateText"]);
                            if (oDR["School_Id"] != DBNull.Value)
                                moSmsTemplateStruct.miSchool_Id = Convert.ToInt32(oDR["School_Id"]);
                            if (oDR["AcademicYearId"] != DBNull.Value)
                                moSmsTemplateStruct.miAcademicYearId = Convert.ToInt32(oDR["AcademicYearId"]);
                            if (oDR["Is_Deleted"] != DBNull.Value)
                                moSmsTemplateStruct.mblnIsDeleted = Convert.ToBoolean(oDR["Is_Deleted"]);
                            if (oDR["TemplateRegistrationId"] != DBNull.Value)
                                moSmsTemplateStruct.msTemplateRegistrationId = Convert.ToString(oDR["TemplateRegistrationId"]);
                        }
                    }
                }
            }
        }

        // This function is used to fetch the SmsTemplate Details
        private String FetchSmsTemplateDetailsFromDatabase(int miTemplateId)
        {
            string sSelectStatement = " SELECT  " +
            "SmsTemplateId" +
            ",SmsTemplateName" +
            ",SmsTemplateText" +
            ",School_Id" +
            ",AcademicYearId" +
            ",Is_Deleted" +
            ",TemplateRegistrationId" +
            " FROM SmsTemplate" +
            " WHERE SmsTemplateId=" + miTemplateId;
            return sSelectStatement;
        }

        
        public struct SmsTemplateStruct
        {

            public int miTemplateId;

            public string msSmsName;

            public string msTemplateText;

            public int miSchool_Id;

            public int miAcademicYearId;

            public bool mblnIsDeleted;

            public string msTemplateRegistrationId;
        }

        public static DataSet FillSmsNameComboAndDyanamicVariableList(int aiSchool_Id, int aiAcademicYearId)
        {
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
            {
                oSQLServerDbUtility.AddParameter("School_Id", aiSchool_Id, SqlDbType.Int);
                oSQLServerDbUtility.AddParameter("AcademicYearId", aiAcademicYearId, SqlDbType.Int);
                return oSQLServerDbUtility.ExecuteStoredProcedureAndGetDataSet("usp_GetSmsNameAndDyanamicVariable");
            }
        }

        public static DataTable GetTemplate(int aiSmsTemplateId, int aiSchool_Id)
        {


            string sSelectStatement = " SELECT  " +
            "SmsTemplateId" +
            ",SmsTemplateName" +
            ",SmsTemplateText" +
            ",SmsType" +
            ",TemplateRegistrationId" +
            " FROM SmsTemplate" +
            " WHERE SmsTemplateId=" + aiSmsTemplateId +
            "  AND " +
            " School_Id=" + aiSchool_Id +
            " AND " +
            " Is_Deleted=" + Constants.I_ZERO.ToString();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);

        }

        public static DataTable GetTemplate(string asSMSType, int aiSchool_Id)
        {
            string sSelectStatement = " SELECT  " +
            "SmsTemplateId" +
            ",SmsTemplateName" +
            ",SmsTemplateText" +
            ",SmsType" +
            ",TemplateRegistrationId" +
            " FROM SmsTemplate" +
            " WHERE SmsTemplateName='" + asSMSType +"'"+
            "  AND " +
            " School_Id=" + aiSchool_Id +
            " AND " +
            " Is_Deleted=" + Constants.I_ZERO.ToString();
            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteSqlStatementAndGetDataTable(sSelectStatement);

        }

        /// <summary>
        /// This method is used to get all the templates into the listview with their associating status.It is called from Object data source
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiGroupId"></param>
        /// <param name="aiStartIndex"></param>
        /// <param name="aiEndIndex"></param>
        /// <param name="asSortDirection"></param>
        /// <returns></returns>
        public DataTable GetAll(int aiSchoolId, string asSortDirection, string asShowSystemDefined)
        {
            using (var oSqlDBUtility = new SQLServerDbUtility())
            {
                oSqlDBUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSqlDBUtility.AddParameter("ShowSystemDefined", asShowSystemDefined, SqlDbType.NVarChar);
                oSqlDBUtility.AddParameter("SortDirection", asSortDirection, SqlDbType.NVarChar);
                return oSqlDBUtility.ExecuteStoredProcedureAndGetDataTable("usp_GetAllSMSTemplates");
            }
        }

        /// <summary>
        /// This method is used to return a templates count to Object data source. 
        /// </summary>
        /// <param name="aiSchoolId"></param>
        /// <param name="aiAcademicYearId"></param>
        /// <param name="aiGroupId"></param>
        /// <returns></returns>
        public int Count(int aiSchoolId, string asShowSystemDefined)
        {
            using (var oSqlDBUtility = new SQLServerDbUtility())
            {
                oSqlDBUtility.AddParameter("SchoolId", aiSchoolId, SqlDbType.Int);
                oSqlDBUtility.AddParameter("ShowSystemDefined", asShowSystemDefined, SqlDbType.NVarChar);
                SqlParameter oSqlParam = oSqlDBUtility.AddParameter("Count", 0, SqlDbType.Int, ParameterDirection.Output);
                oSqlDBUtility.ExecuteStoredProcedureOnServer("usp_CountSMSTemplates");
                return Convert.ToInt32(oSqlParam.Value);
            }
        }

        /// <summary>
        /// This function is used to insert & update the template details.
        /// </summary>
        public void Insert()
        {
            using (var oSqlDBUtility = new SQLServerDbUtility())
            {
                oSqlDBUtility.AddParameter("Name", moSmsTemplateStruct.msSmsName, SqlDbType.NVarChar);
                oSqlDBUtility.AddParameter("Template", moSmsTemplateStruct.msTemplateText, SqlDbType.NVarChar);
                oSqlDBUtility.AddParameter("TemplateId", moSmsTemplateStruct.miTemplateId, SqlDbType.Int);
                oSqlDBUtility.AddParameter("SchoolId", miSchoolId, SqlDbType.Int);
                oSqlDBUtility.AddParameter("TemplateRegistrationId", moSmsTemplateStruct.msTemplateRegistrationId, SqlDbType.NVarChar);
                oSqlDBUtility.ExecuteStoredProcedureOnServer("usp_InsertSMSTemplate");
            }
        }
    }
}
