//  -----------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool.
//      Runtime Version:2.0.50727.42
//  
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
//  -----------------------------------------------------------------------------


// Class Name       :- StudentCautionMoneyChequeDetailsDC
// Purpose          :- This class is used to manage StudentCautionMoneyChequeDetails details.
// Date Of creation :- 12/31/2008
// Author Name      :- 

using System;
using System.Data.SqlClient;
using System.Text;
using Utility;
using System.Globalization;

namespace DataCommunicator
{
	public class StudentCautionMoneyChequeDetailsDC
	{
		private StudentCautionMoneyChequeDetailsStruct moStudentCautionMoneyChequeDetailsStruct;

        private StudentCautionMoneyElectronicDetailsStruct moStudentCautionMoneyElectronicDetailsStruct;

		public StudentCautionMoneyChequeDetailsDC()
		{
		}

		public StudentCautionMoneyChequeDetailsDC(int miStudentCautionMoneyChequeId)
		{
			LoadStudentCautionMoneyChequeDetailsDetails(miStudentCautionMoneyChequeId);
		}

		public StudentCautionMoneyChequeDetailsStruct StudentCautionMoneyChequeDetailsStructDetails
		{
			get
			{
				return moStudentCautionMoneyChequeDetailsStruct;
			}
			set
			{
				moStudentCautionMoneyChequeDetailsStruct = value;
			}
		}

        public StudentCautionMoneyElectronicDetailsStruct StudentCautionMoneyElectronicDetailsStructDetails
        {
            get
            {
                return moStudentCautionMoneyElectronicDetailsStruct;
            }
            set
            {
                moStudentCautionMoneyElectronicDetailsStruct = value;
            }
        }

		public string GetInsertStatementForStudentCautionMoneyChequeDetails()
		{
			return "INSERT INTO Student_Caution_Money_Cheque_Details(" +
						"Cheque_Number" +
						",Cheque_Date" +
						",Bank_Id" +
						",Remarks" +
						",Inserted_By_id" +
				   ")VALUES(" +
						" N'" + StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msChequeNumber, false) + "' " +
						 " , N'" + moStudentCautionMoneyChequeDetailsStruct.mdtChequeDate + "' " +
						 " , " + moStudentCautionMoneyChequeDetailsStruct.miBankId +
						 " , N'" + StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msRemarks, false) + "' " +
						 " , " + moStudentCautionMoneyChequeDetailsStruct.miInsertedByid +
						")";
		}

		// This function is used to insert the StudentCautionMoneyChequeDetails Details.
		public int InsertStudentCautionMoneyChequeDetails()
		{
			string sSqlStatement = String.Format("INSERT Student_Caution_Money_Cheque_Details (Cheque_Number, Cheque_Date, Bank_Id, DepositBankId, Remarks, Inserted_By_id) " +
												 "VALUES ('{0}','{1}',{2},{3},'{4}',{5})",
												 StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msChequeNumber, false),
												 moStudentCautionMoneyChequeDetailsStruct.mdtChequeDate.ToString(Constants.S_DATE_FORMAT_MARATHI,new CultureInfo("en")),
												 moStudentCautionMoneyChequeDetailsStruct.miBankId,
												 moStudentCautionMoneyChequeDetailsStruct.miDepositBankId,
												 StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msRemarks, false),
												 moStudentCautionMoneyChequeDetailsStruct.miInsertedByid);

			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
				return oSQLServerDbUtility.ExecuteTransaction(sSqlStatement);
		}

        public int InsertStudentCautionMoneyElectronicDetails()
        {
            string sSqlStatement = string.Format("INSERT INTO StudentCautionMoneyElectronicPayments (SchoolwiseStudentId, TypeId, TransactionNumber, BankId, DepositedBankId, SchoolId, IsDeleted, InsertDate, InsertedById, IsReturnRecord)" +
                                                 "VALUES ({0},{1},'{2}',{3},{4},{5},{6},'{7}',{8},{9})",
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiSchoolwiseStudentId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiTypeId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.msTxnNumber,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiBankId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiDepositBankId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiSchoolId,
                                                 Constants.I_ZERO,
                                                 moStudentCautionMoneyElectronicDetailsStruct.mdtInsertDate,
                                                 moStudentCautionMoneyElectronicDetailsStruct.miInsertedByid,
                                                    moStudentCautionMoneyElectronicDetailsStruct.aiIsReturnRecord ? 1:0
                                                 );

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                return oSQLServerDbUtility.ExecuteTransaction(sSqlStatement);
        }

		public void InsertStudentCautionMoneyChequeDetails(StudentCautionMoneyDetailsDC oStudentCautionMoneyDetailsDC, bool abIsReturnDetails)
		{
			string sFilter = string.Empty;
			if (abIsReturnDetails)
				sFilter = " Return_Cheque_Id ";
			else
				sFilter = " Payment_Cheque_Id ";

			StringBuilder sInsertStatement = new StringBuilder();
			sInsertStatement.Append("INSERT INTO Student_Caution_Money_Cheque_Details(" +
											"Cheque_Number" +
											",Cheque_Date" +
											",Bank_Id" +
											",Remarks" +
											",Inserted_By_id" +
									   ")VALUES(" +
											" N'" + StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msChequeNumber, false) + "' " +
											 " , N'" + moStudentCautionMoneyChequeDetailsStruct.mdtChequeDate.ToString(Constants.S_DATE_FORMAT_MARATHI, new CultureInfo("en")) + "' " +
											 " , " + moStudentCautionMoneyChequeDetailsStruct.miBankId +
											 " , N'" + StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msRemarks, false) + "' " +
											 " , " + moStudentCautionMoneyChequeDetailsStruct.miInsertedByid +
											")");

			sInsertStatement.Append(" DECLARE @PrimaryKey INT " +
									  "  SET @PrimaryKey = @@IDENTITY ");

			sInsertStatement.Append("UPDATE Student_Caution_Money_Details SET " +
											" Amount= " + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.miAmount +
                                            ",ConcessionAmount= " + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.miConcessionAmount +
											",Paid_By_Student= N'" + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.mblnPaidByStudent + "'" +
											",Payment_Date= N'" + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.mdtPaymentDate.ToString(Constants.S_DATE_FORMAT_MARATHI, new CultureInfo("en")) + "' " +
											",Payment_Mode= N'" + StringUtility.ReplaceSingleQuoteInString(oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.msPaymentMode, false) + "' " +
                                            ",Remarks = N'" + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.msRemark + "'" +
											",Update_Date= N'" + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.mdtUpdateDate.ToString(Constants.S_DATE_FORMAT_MARATHI, new CultureInfo("en")) + "' " +
											",Updated_By_Id= " + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.miUpdatedById +
											" , " + sFilter + "= @PrimaryKey " +
									" WHERE  " +
										" School_Id=" + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.miSchoolId +
										" AND Schoolwise_Student_Id= " + oStudentCautionMoneyDetailsDC.moStudentCautionMoneyDetailsStruct.miSchoolwiseStudentId);

			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
				oSQLServerDbUtility.ExecuteTransaction(sInsertStatement.ToString());
		}

		// This function is used to update the StudentCautionMoneyChequeDetails Details
		public void UpdateStudentCautionMoneyChequeDetails()
		{
			string sSqlStatement = String.Format("UPDATE Student_Caution_Money_Cheque_Details SET ClearanceDate = NULL, Cheque_Number = '{0}', Cheque_Date = '{1}', Bank_Id = {2}, Remarks = '{3}', DepositBankId = {4}, Update_Date = '{5}', Updated_By_Id = {6}" +
												 " WHERE Student_Caution_Money_Cheque_Id = {7}",
												 StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msChequeNumber, false),
												 moStudentCautionMoneyChequeDetailsStruct.mdtChequeDate.ToString(Constants.S_DATE_FORMAT_MARATHI, new CultureInfo("en")),
												 moStudentCautionMoneyChequeDetailsStruct.miBankId,
												 StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyChequeDetailsStruct.msRemarks, false),
												 moStudentCautionMoneyChequeDetailsStruct.miDepositBankId,
												 moStudentCautionMoneyChequeDetailsStruct.mdtUpdateDate.ToString(Constants.S_DATE_FORMAT_MARATHI, new CultureInfo("en")),
												 moStudentCautionMoneyChequeDetailsStruct.miUpdatedById,
												 moStudentCautionMoneyChequeDetailsStruct.miStudentCautionMoneyChequeId);


			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
				oSQLServerDbUtility.ExecuteTransaction(sSqlStatement);
		}

        // This function is used to update the StudentCautionMoneyChequeDetails Details
        public void UpdateStudentCautionMoneyElectronicPaymentDetails()
        {
            string sSqlStatement = String.Format("UPDATE StudentCautionMoneyElectronicPayments SET TypeId = '{0}', TransactionNumber = '{1}', BankId = {2}, DepositedBankId = {3}, UpdateDate = '{4}', UpdatedById = {5}" +
                                                 " WHERE Id = {6}",
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiTypeId,
                                                 StringUtility.ReplaceSingleQuoteInString(moStudentCautionMoneyElectronicDetailsStruct.msTxnNumber, false),
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiBankId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiDepositBankId,
                                                 moStudentCautionMoneyElectronicDetailsStruct.mdtUpdateDate,
                                                 moStudentCautionMoneyElectronicDetailsStruct.miUpdatedById,
                                                 moStudentCautionMoneyElectronicDetailsStruct.aiElePaymentId);

            using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
                oSQLServerDbUtility.ExecuteTransaction(sSqlStatement);
        }

		// This function is used to load the StudentCautionMoneyChequeDetails Details
		private void LoadStudentCautionMoneyChequeDetailsDetails(int miStudentCautionMoneyChequeId)
		{
			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
			{
				string sSelectStatement = FetchStudentCautionMoneyChequeDetailsDetailsFromDatabase(miStudentCautionMoneyChequeId);
				using(SqlDataReader oDR = oSQLServerDbUtility.ExecuteSqlStatementAndGetResults(sSelectStatement))
                {

                    if (oDR != null)
                    {
                        while (oDR.Read())
                        {
                            if (oDR["Student_Caution_Money_Cheque_Id"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.miStudentCautionMoneyChequeId = Convert.ToInt32(oDR["Student_Caution_Money_Cheque_Id"]);
                            if (oDR["Cheque_Number"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.msChequeNumber = Convert.ToString(oDR["Cheque_Number"]);
                            if (oDR["Cheque_Date"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.mdtChequeDate = Convert.ToDateTime(oDR["Cheque_Date"]);
                            if (oDR["Bank_Id"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.miBankId = Convert.ToInt32(oDR["Bank_Id"]);
                            if (oDR["Remarks"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.msRemarks = Convert.ToString(oDR["Remarks"]);
                            if (oDR["DepositBankId"] != DBNull.Value)
                                moStudentCautionMoneyChequeDetailsStruct.miDepositBankId = Convert.ToInt32(oDR["DepositBankId"]);
                        }
                    }
				}
			}
		}

		// This function is used to fetch the StudentCautionMoneyChequeDetails Details
		private string FetchStudentCautionMoneyChequeDetailsDetailsFromDatabase(int miStudentCautionMoneyChequeId)
		{
		 return string.Format("SELECT Student_Caution_Money_Cheque_Id,Cheque_Number,Cheque_Date,Bank_Id,Remarks,DepositBankId FROM Student_Caution_Money_Cheque_Details WHERE Student_Caution_Money_Cheque_Id={0} AND Is_Deleted = 0", miStudentCautionMoneyChequeId);
         }

		public struct StudentCautionMoneyChequeDetailsStruct
		{
			public int miStudentCautionMoneyChequeId;
            public int miStudentCautionMoneyId;
			public string msChequeNumber;
			public System.DateTime mdtChequeDate;
			public int miBankId;
			public int miStudentId;
			public string msRemarks;
			public int miDepositBankId;
			public System.DateTime mdtInsertDate;
			public int miInsertedByid;
			public System.DateTime mdtUpdateDate;
			public int miUpdatedById;
		}

        public struct StudentCautionMoneyElectronicDetailsStruct
        {
            public int aiElePaymentId;
            public string msTxnNumber;
            public int aiBankId;
            public int aiSchoolwiseStudentId;
            public int aiTypeId;
            public int aiDepositBankId;
            public int aiSchoolId;
            public System.DateTime mdtInsertDate;
            public int miInsertedByid;
            public System.DateTime mdtUpdateDate;
            public int miUpdatedById;
            public bool aiIsReturnRecord;
        }

		public bool IsChequeNoDuplicate()
		{
			string sWhere = string.Empty;
			if (moStudentCautionMoneyChequeDetailsStruct.miStudentCautionMoneyChequeId != Constants.I_ZERO)
			{
				sWhere = " AND Student_Caution_Money_Cheque_Id <> " + moStudentCautionMoneyChequeDetailsStruct.miStudentCautionMoneyChequeId;
			}

			string sSelectStatement = "SELECT  COUNT(*) " +
										" FROM " +
										" Student_Caution_Money_Cheque_Details " +
									" WHERE " +
										" Student_Caution_Money_Cheque_Details.Cheque_Number = N'" + moStudentCautionMoneyChequeDetailsStruct.msChequeNumber + "'" +
										"  AND Student_Caution_Money_Cheque_Details.Bank_Id = " + moStudentCautionMoneyChequeDetailsStruct.miBankId +
										"  AND Student_Caution_Money_Cheque_Details.Is_Deleted =  " + Constants.I_ZERO +
										sWhere;

			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
			{
				int iCount = oSQLServerDbUtility.PerformIntQueryOnSqlServer(sSelectStatement);
				if (iCount == 0)
					return false;
				else
					return true;
			}
		}

		public void DeleteStudentCautionMoneyChequeDetails(int aiStudentCautionMoneyChequeId)
		{
			string sDeleteChequeDetails = "DELETE " +
												" FROM [Student_Caution_Money_Cheque_Details] " +
											 " WHERE " +
												" Student_Caution_Money_Cheque_Id=" + aiStudentCautionMoneyChequeId;

			using (SQLServerDbUtility oSQLServerDbUtility = new SQLServerDbUtility())
				oSQLServerDbUtility.ExecuteTransaction(sDeleteChequeDetails);
		}
	}
}
